MozillaReality/FirefoxReality

app/src/googlevr/AndroidManifest.xml, app/src/googlevr/cpp/DeviceDelegateGoogleVR.cpp
Not tested since I don't have a 6DoF headset but doesn't break the 3DoF daydream headsets.
=> Add 6DoF head tracking support to GVR

app/build.gradle, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java, app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsStore.java, app/src/main/res/values/strings.xml
Refer #57 and [FirefoxTV](https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt#L45). Adding [Android telemetry component support](https://github.com/mozilla-mobile/android-components), we measure the session spent time when using FxR.
=> [CXB-184] Add telemetry component support.

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/BrowserWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/TopBarWidget.java, app/src/main/res/values/strings.xml
Fixes #91 
There were some situations were private sessions were not being correctly restored. For exmaple after leaving the app, in case you do not "continue" or "quit" and just go somewhere else an open the app later the app sessions were still alive but we were not restoring the private/public sessions correctly.
Please test in other headsets as I've only tested on Oculus Go and thetre might be some Android lifecycle related differences on those.
=> Better handling of the app state and opened gecko sessions.

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/KeyboardWidget.java
- Release widgets on destroy to ensure that text listeners are cleared succesfully in the duplicated activity creations
- The updateSelection command was not sent with the correct handler
=> Fix keyboard on Daydream #127

app/src/main/cpp/ExternalVR.cpp, app/src/main/cpp/moz_external_vr.h
This will be needed for compatibility with GeckoView once [Bug 1470527](https://bugzilla.mozilla.org/show_bug.cgi?id=1470527) (Implement controller support for gfxVRExternal) lands in mozilla-central.
This is currently in mozilla-inbound:
https://hg.mozilla.org/integration/mozilla-inbound/rev/1e8eca5ec5c9
=> Update to new moz_external_vr.h structures

app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/ExternalVR.cpp, app/src/main/cpp/ExternalVR.h, app/src/main/cpp/moz_external_vr.h
Firefox Reality pauses the compositor when gfxVRExternal presentation begins.
There is a edge race condition which causes a deadlock. It happens when pausing the compositor while gfxVRExternal is waiting for a SubmitFrame result.
=> Avoid deadlock when pausing the compositor in immersive mode

app/src/main/cpp/BrowserWorld.cpp
#108 
#148 
Fix resizing cases where worldWidth doesn't change but widget width does.
=> Fix browser resizing issues

app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java
Fixes #130 
We are nor hiding all jar: and resources: URLs. Now when at home the URL bar is empty, same as Firefox does
=> Filter resource and jar URLs

app/src/main/cpp/ExternalVR.cpp
Only one line needs to be added here.
GV side patch: https://bugzilla.mozilla.org/show_bug.cgi?id=1476380
=> Get rid of WebVR condition spin waits in GeckoView side

app/src/main/cpp/ExternalVR.cpp
Firefox Reality and Gecko inputFrameIds do not match each frame, they are off-by-one. So we have 1 frame inconsistency in WebVR. This is because PushSystemState() must be called after the device delegate SubmitFrame() call is done and the new pose is ready
=> Improve WebVR latency

tools/taskcluster/upload_symbols.sh
Per #117. We make the `symbolstore.py` to help us generate symbols from `libxxx-lib.so`. It will call `dump_syms` that is built from Breadpad and `arm-linux-androideab-objcopy` that is from Android SDK. Then, we pack the output symbol files to a zip file and upload it to our symbol server.
=> [CXB-183] Native code symbol generator and uploader

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/googlevr/cpp/DeviceDelegateGoogleVR.cpp, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/ControllerContainer.cpp, app/src/main/cpp/ControllerDelegate.h, app/src/main/cpp/VRBrowser.cpp, app/src/main/cpp/VRBrowser.h, app/src/main/cpp/native-lib.cpp, app/src/svr/cpp/DeviceDelegateSVR.cpp, app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
Some follow-ups:
- We may need a better name for "SetButtonCount" because immersive mode can have different count from the app. Just added a comment for now.
- We may need to add a exit dialog confirmation in Vive Focus
=> Fix #165: Map the remote controller APP button to BACK action

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Changes needed for Oculus SDK v1.15
- Enable option to send the remote back button java events to the apps (as it was before)
- Also enabled the property to reorient the headset after a controller recenter.
=> Update Oculus SDK to v1.15

app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java
More info here:  https://github.com/MozillaReality/FirefoxReality/issues/291
=> Increase max WebVR raf. Fixes delay when entering WebVR in some demos.

app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/TrayWidget.java
Fixed #298 Now when a new session is opened the previous session is stacked and unstacked when back or there is close request.
- window.open flow:
- OAuth flow:
=> Added support for stacked sessions

app/src/common/shared/org/mozilla/vrbrowser/ui/CustomKeyboardView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/KeyboardWidget.java, app/src/main/res/drawable/ic_icon_keyboard_caps.xml, app/src/main/res/drawable/ic_icon_keyboard_shift_off.xml, app/src/main/res/drawable/ic_icon_keyboard_shift_on.xml
Fixes #288 Make shift become caps lock when double clicked or long pressed.
=> 'Caps Lock' key should behave like a 'Shift' key does

app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java
The new GeckoView API has landed in nightly so update FxR so it will continue to compile on task cluster.
=> Compile fix for new onLoadError() GV API

app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/Controller.cpp, app/src/main/cpp/Controller.h
Clicking a button on controllers can cause them to move enough to cancel button presses. Add a deadzone when clicking to make button and link activation easier.
=> Add deadzone when clicking so that buttons are easier to activate

app/src/main/cpp/ExternalBlitter.cpp, app/src/main/cpp/ExternalVR.cpp
The big patch is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1482613
Do not merge this until that patch lands.
The patch also has some benefits for non-multiprocess:
- Custom SurfaceTexture sets are used for WebVR, no more conflicts with the compositor SurfaceTextures. We can even enable the compositor and WebVR works. This will be useful for link traversal (we may need to enable the compositor in the transition)
- We no longed need to dettach SurfaceTextures at the end of the VR frame. 
- It might help with #121 (didn't try yet)
I tested the implementation with multiprocess and non-multiprocess on Oculus Go, Vive and Pixel 1.
=> Make WebVR work with multiprocess enabled

app/src/googlevr/cpp/DeviceDelegateGoogleVR.cpp
Fixes https://github.com/MozillaReality/FirefoxReality/issues/121
Is not a problem anymore thanks to using a different  GLScreenBuffer for WebVR and not deatching our SurfaceTextures everyframe
=> Enable Daydream WebVR swapchain

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
`Gear VR Controller` is used in Oculus and Vive Focus
`Daydream Controller` is used in Daydream
Fixes  #434
=> Fix WebVR remote controller names

app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java
Enabling this may help aframe persomance. A-frame uses a polyfill is custom elements is not availabe, which adds overhead in a lot of calls.
=> Enable custom elements preference

app/src/common/shared/org/mozilla/vrbrowser/ui/KeyboardWidget.java
Fixes #530 Remove the keyboard back handler when it's dismissed. We were only removing the back handler if there was a focus change.
=> Remove keyboards back handler when it's dismissed

app/src/debug/AndroidManifest.xml, app/src/googlevr/AndroidManifest.xml, app/src/main/AndroidManifest.xml
This prevents FxR icon from being shown in 2D icon list in Daydream phones
It also fixes duplicated daydream activity issues when launched from 2D :)
=> Only add launcher category intent for debug builds. 

app/build.gradle, tools/taskcluster/sign_apk.py
APK file names should now contain version name and version code and staging builds should
now have staging in the name instead of release.
=> Update APK names generated on taskcluster

app/src/main/cpp/ExternalVR.cpp
This PR fixes the spinner during link traversal and for the first frame after link traversal.
We need to land this to make link traversal work reliably: https://phabricator.services.mozilla.com/D6921 but this PR is not blocked by that GV patch
I use this sample for testing: https://webvr.info/samples/test-vr-links.html
=> Fix spinner during link traversal

app/CMakeLists.txt, app/src/googlevr/cpp/DeviceDelegateGoogleVR.cpp, app/src/googlevr/cpp/DeviceDelegateGoogleVR.h, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/DeviceDelegate.h, app/src/main/cpp/DeviceUtils.cpp, app/src/main/cpp/DeviceUtils.h, app/src/noapi/cpp/DeviceDelegateNoAPI.cpp, app/src/noapi/cpp/DeviceDelegateNoAPI.h, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/oculusvr/cpp/DeviceDelegateOculusVR.h, app/src/svr/cpp/DeviceDelegateSVR.cpp, app/src/svr/cpp/DeviceDelegateSVR.h, app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp, app/src/wavevr/cpp/DeviceDelegateWaveVR.h
=> Add ability to reorient the UI while lying down

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/main/cpp/ExternalVR.cpp, app/src/main/cpp/ExternalVR.h
Fixes #538
Related Gecko PR: https://phabricator.services.mozilla.com/D6236
=> Correct ExternaVR shutdown

app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
Usage:
Ensure that the app is killed (GeckoView doesn't support changing preferences at runtime yet)
`adb shell am force-stop org.mozilla.vrbrowser`
Launch intent with the desided preference values. We have only exposed vr-user gesture and timer precision for now.
`adb shell am start -n  org.mozilla.vrbrowser/.VRBrowserActivity --es url "https://aframe.io" --ez dom.vr.require-gesture false --ez privacy.reduceTimerPrecision false`
Note, extra parameters don't work when using the android.intent.action.VIEW. That's why I added the optional `url` parameter.
`adb shell am start -a android.intent.action.VIEW -d "https://aframe.io" org.mozilla.vrbrowser/.VRBrowserActivity`
=> Support intent preferences for benchmarks

app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java
Fixes #589 Added URI null check to TelemetryWrapper for uploadPageLoadToHistogram
STR:
- Open any page that triggers a new session creation i.e. window.open
- When the new session is opened the app shouldn't crash anymore
=> Check for a null URI in the TelemertryWrapper when page is stopped.

app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java
We changed the behavior of BuildConfig.FLAVOR recently. We should update our telemetry app name to be FLAVOR_platform.
=> Update telemetry app name to be FLAVOR_platform.

app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java
Fixes #596 Avoid URL bar to override user input when it's focused.
=> Avoid overriding user input in URL bar

app/src/common/shared/org/mozilla/vrbrowser/CrashReporterService.java, app/src/common/shared/org/mozilla/vrbrowser/GlobalExceptionHandler.java, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
Fixes #592 Set a global Java exception handler using Gecko's CrashHandler implementation. Should catch any exception including OOMs happening in any thread from the current process. 
Regarding @cvan's comment on #592 the CrashHandler seems to be sending reports to **https://crash-reports.mozilla.com/**, not sure if that's the right place for it or we should  extend that to use another endpoint (he mentioned Sentry).
=> Added a Java global exception handler

app/build.gradle, build.gradle
* Updates the version used to 0.26.0
* Updates the artifacts to use the new names
During the migration phase from JCenter to maven.mozilla.org (artifacts get published on both) maven.mozilla.org needs to be listed before JCenter to avoid dependency resolution conflicts.
=> Use Mozilla Android Components 0.26.0 from maven.mozilla.org.

app/src/common/shared/org/mozilla/vrbrowser/PermissionDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/CrashDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/DeveloperOptionsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/KeyboardWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/PermissionWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/RestartDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/UIWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/prompts/ChoicePromptWidget.java, app/src/common/shared/org/mozilla/vrbrowser/utils/ValueHolder.java, app/src/main/AndroidManifest.xml, app/src/main/res/values/strings.xml
Fixes #594 Added support for general app permissions (outside Gecko) handling and support for loading content from external storage upon onLoadRequest.
=> Support added for loading local files through file:// handler

app/src/main/res/values/localpages.xml
I'm working on a larger PR to add L10n comments for all the strings in `localpages.xml` (per https://github.com/MozillaReality/FirefoxReality/pull/626#issue-223075437), but I noticed this first and thought this would be a quick fix to merge
=> fix typo in `private_browsing_title` L10n string

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/SettingsWidget.java
Fixed environment fade when clicking on Privacy and Bug Report settings
=> Fixed environment fade when clicking on Privacy and Bug Report settings

app/src/main/cpp/BrowserWorld.cpp
The background (cubemap) environment was looking pixelated due to being sampled with a box filter (GL_NEAREST).  Changing this to GL_LINEAR fixes it.  At the particular resolution of the environments, it's not necessary to create mipmaps or use GL_LINEAR_MIPMAP_LINEAR sampling, as the lower mips would only have a minor effect in the extreme corners of the cube.  If we later support a wider range of resolutions, or sample from this environment map for reflections, then we should generate mips.  Ideally, the environment would be pre-compressed with pre-generated mips, but simply using GL_LINEAR helps a lot for now.
=> Fix pixelated (cubemap) background

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/utils/ServoUtils.java, servo/src/main/java/org/mozilla/servo/ServoWhiteList.java, servo/src/main/res/values/servo_white_list.xml
This is for after #498. We only want to show the button for some urls.
I moved the button to the right of the url bar to prevent the UI to "move" too much as the user navigates.
@jdm can you look at the list and tell me if there's anything else you want to add in there?
=> Only show the servo button for few websites

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/RootWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java, app/src/main/cpp/BrowserWorld.cpp
=> Fix not throttled events and errors when pointing the remote on the background.

app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h, app/src/main/cpp/Widget.cpp, app/src/main/cpp/Widget.h
The depth sorting we are using for the widgets fails in some situations for the video mode UI (e.g. a widget on the right side vs one in the center but farther in z plane). This PR improves the depth sorting using distance to plane instead of distance to node position.
=> Improve widget depth sorting

README.md, app/build.gradle, app/src/common/shared/org/mozilla/vrbrowser/crashreporting/CrashReporterService.java
I find the restart annoying while developing because the logs/stacktraces get back on the log history and may be lost.
Related issue: https://github.com/MozillaReality/FirefoxReality/issues/651
=> Add a user property to disable app relaunch on crash

app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java
This is a problem with servo sessions. `stop` and `setActive` can't work after `close` is called.
=> Do not call anything after session.close()

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/SuggestionsWidget.java
Fixes a crash when animating the suggestions bar if it' already removed from the view tree.
STRs:
- Click on the URL bar
- Go to file:///sdcard/
Expected result:
- Permission dialog shows
Result:
- App crashes
=> Fixes a crash hiding the suggestions bar

README.md, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/PermissionWidget.java, app/src/main/res/values/localpages.xml, app/src/main/res/values/strings.xml
=> clean up various L10n strings

app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
We have checked Oculus Go browser and FxR in Oculus Go, even Firefox desktop, all of them are put touchpad button at index 0, and trigger at index 1. We should make WaveVR to be consistent with other devices.
=> Switch WaveVR controller touchpad and trigger button order

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UISurfaceTextureRenderer.java
It seems that `lockCanvas()` doesn't return a hardware accelerated canvas.
`lockHardwareCanvas()` returns a canvas that uses hardware acceleration instead. It requires a full clean on each layout update but we were already doing that.
=> Use lockHardwareCanvas on UI rendering

app/CMakeLists.txt, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h, app/src/main/cpp/Controller.cpp, app/src/main/cpp/Controller.h, app/src/main/cpp/ControllerContainer.cpp, app/src/main/cpp/ControllerContainer.h, app/src/main/cpp/Pointer.cpp, app/src/main/cpp/Pointer.h, app/src/main/cpp/VRBrowser.cpp, app/src/main/cpp/VRBrowser.h, app/src/main/cpp/VRLayer.cpp, app/src/main/cpp/VRLayer.h, app/src/main/cpp/Widget.cpp, app/src/main/cpp/Widget.h, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
- Refactor controller pointer code
- Improve quality of the pointer when layers are enabled
- Fixed depth problem when the pointer is shown on a widget that is back to another widget (e.g. dialog)
=> Refactor controller pointer code. Support layers for pointer.

app/src/common/shared/org/mozilla/vrbrowser/ui/views/MediaSeekBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MediaControlsWidget.java
Fixes https://github.com/MozillaReality/FirefoxReality/issues/776
=> Disable Media Control buttons for non-video sources

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/BookmarksWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/BrowserWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/options/DisplayOptionsWidget.java
Fixes Bookmarks resizing issues.
Also fixes an issues with a blank session visible if quitting the app while bookmarks are opened.
=> Fixes Bookmarks resizing issues

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
so I can better understand how my fix fixes the bug, can you share the context of PR #609?
specifically, in the `mMicrophoneListener` method, what does the `view.requestFocusFromTouch()` call do?
the reason I ask: on `master`, I was able to reproduce the same bug randomly twice (but I still cannot find reliable STR): I pressed the Voice Search icon in the URL bar, my Voice Search was processed and completed, but then the keyboard opened (even though I was not previously interacting with the keyboard, and the keyboard was closed). ideas? if it was a bug/oversight from PR #609, I can address this in this PR. otherwise, I'll be filing an issue.
=> keep keyboard open upon pressing Clear icon in URL bar (fixes issue #742)

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
=> Fix exit fullscreen viewport scaling issues

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/BrowserWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
=> Don't remember fullscreen resize on restart

app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/BrowserWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java
Transparent border helps a bit with aliased borders on the browser window when not using layers (e.g. Wave)
=> Improve border aliasing. Enable transparent border on all platforms.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TopBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java
Fixes #671 Tray doesn't indicate private icon on when restoring
=> Fixes #671 Tray doesn't indicate private icon on when restoring

app/src/main/res/layout/navigation_url.xml
Fixes #846 #849 #860 Avoid URL EditText to gain focus when focus changes
=> Fixes #846 #849 #860 Fixes keyboard focus issues

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayListener.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/main/res/values/dimen.xml
Fixes #834 #835 Fixed bookmarks resize issues and refactored browser and bookmarks code into a "browser window" widget so we just need to use a single surface texture for any view that belongs to the browser window space (bookmarks, history, browser, etc)
=> Fixes #834 #835 Bookmarks resize issues

README.md, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/ButtonSetting.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/DoubleEditSetting.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/RadioGroupSetting.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/RadioGroupVSetting.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/SettingsEditText.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/SingleEditSetting.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/SwitchSetting.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SettingsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/options/DeveloperOptionsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/options/DisplayOptionsWidget.java, app/src/main/res/drawable/settings_edit_cursor.xml, app/src/main/res/layout/options_developer.xml, app/src/main/res/layout/options_display.xml, app/src/main/res/layout/setting_edit.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Fixes #350 Added a setting to set a homepage in the Developer options panel. Also we now provide an adb parameter to do it from the command line.
=> Fixes #350 Personalized homepage

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Widget.java
=> Fix loading icon stuck on startup

geckoview-local/build.gradle
Without this, if we use the wrong path in user.properties, we would get this error:
```
Could not get unknown property 'geckoViewLocal' for build 'FirefoxReality' of type org.gradle.invocation.DefaultGradle.
```
=> Fix error message

app/src/main/res/values/non_L10n.xml
fixes issue #885. r? @mkaply to confirm.
<hr>
- https://github.com/MozillaReality/FirefoxReality/issues/885
- https://github.com/mozilla-mobile/android-components/issues/1563
- https://github.com/mozilla-mobile/focus-android/issues/3917
- https://github.com/sblatz/android-components/commit/f3e5cb4
- https://dxr.mozilla.org/mozilla-central/source/browser/components/search/test/browser/browser_google.js
- https://dxr.mozilla.org/mozilla-central/search?q=google.com%2Fsearch&redirect=true
=> update to new Google search codes (fixes issue #885)

app/src/main/assets/userAgentOverride.json
fixes issue #914, handling `unext.jp` (which covers `www.unext.jp`, `video.unext.jp`, etc. too)
example:
https://video.unext.jp/genre/foreigntvseries
=> add "Desktop" User-Agent Overrides for U-NEXT (fixes issue #914)

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/RestartDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/ChoicePromptWidget.java
Fixes a noapi crash that happens when a handler is accessed while the view is not attached. Use postDelayed directly so the right handler is used internally. The view life cycle must be slightly different in noapi and at some point the view gets unattached right after the back button is pressed.
=> Fixes a noapi crash when going back from fullscreen

app/CMakeLists.txt, app/build.gradle
I changed the layout of the folders to match the ones from the SDK.
jniLibs doesn't like the Debug/Release folders on the SDK path, so I had to add a copy step in Cmake. Didn't find a better way to fix this.
=> Add support for Oculus SDK v1.21

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MenuWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/SuggestionsWidget.java, app/src/main/res/layout/honeycomb_button.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/styles.xml
See #959 (tries to improve the second point)
=> Add shadow and improve text quality on widgets

app/src/main/cpp/Cylinder.cpp, app/src/main/cpp/Cylinder.h, app/src/main/cpp/WidgetResizer.cpp
See #959
Depends on https://github.com/MozillaReality/vrb/pull/60
This PR improves resize UI quality on Vive. I finally decided to switch to vertex colors instead of using a texture sample. It was more work but it provides better quality and allows for more flexibility (we can set different values per platform, e.g. disabled in Oculus)
=> Improve resize UI quality

app/src/googlevr/java/org/mozilla/vrbrowser/PlatformActivity.java, app/src/main/cpp/BrowserWorld.cpp, app/src/noapi/java/org/mozilla/vrbrowser/PlatformActivity.java
GLSurfaceView.queueEvent() calls dispatched before the surfaceView renderer is ready are dispatched before the activityCreated callback is notified to native. This can cause some nullptr device states (we had to add a if not null workaround) or issues when initializing some data (e.g curdved setting on the first widgets created)
=> Fix queue event lifecycle on googlevr and noapi platforms

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/options/DisplayOptionsWidget.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/DeviceDelegate.h, app/src/main/cpp/Widget.cpp, app/src/main/cpp/Widget.h, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/oculusvr/cpp/DeviceDelegateOculusVR.h
This PR allows to switch between flat and curved display without a restart.
With Oculus Layers it reuses the swapChain so no surfaces are created during the switch.
With GL geometries it reuses the SurfaceTexture.
=> Implement dynamic switch between flat and curved display

app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/DoubleEditSetting.java
=> Fix editing only the first field on a DoubleEditSetting

app/src/main/cpp/ControllerContainer.cpp, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Per #977. We find the second controller does not show up intermittently, and I notice it is because the `model` vector of `ControllerContainer.cpp` is not resized properly.
=> Fixed the second controller doesn't show up problem

app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
Doing some adjustments to make 6DOF controllers work on Wave devices. Currently, the 6DOF recenter function doesn't work from this new device, but it makes sense to add the same code as we did for 3DOF controllers. Besides, on this 6DOF controller, it uses `WVR_InputId_Alias1_Trigger` instead of `WVR_InputId_Alias1_Digital_Trigger` for trigger btn, we have to support both for different controllers. Furthermore, we haven't given a new 3D model for this new controller, we would give a todo list for this art work.
=> Making Wave support 6DOF controllers.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/options/DisplayOptionsWidget.java
=> Fix setting window size oddities

app/src/googlevr/java/org/mozilla/vrbrowser/PlatformActivity.java, app/src/wavevr/java/org/mozilla/vrbrowser/PlatformActivity.java
=> Discard back button presses to exit the app in WaveVR and Daydream

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/AuthPromptWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/PromptWidget.java, app/src/main/res/layout/prompt_auth.xml, app/src/main/res/values/strings.xml
Fixes  #943
Note: The text message from https://www.httpwatch.com/httpgallery/authentication/authenticatedimage/default.aspx is a bit cropped. It looks like a GeckoView issue, the string is already cropped when the GV event is received.
=> Implement basic auth prompt

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
Per #812, we should use the same gamepad id, `Oculus Go Controller`, as other browsers when running in Oculus Go display.
=> Replace Gamepad id from "Gear VR Controller" to Oculus Go/HTC HTC Vive Focus controllers

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
=> Reset keyboard layout when active editable element changes focus

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
You should use `menu` btn to exit the immersive mode instead of `b` and `y` btn like Oculus browser's behavior.
=> Replace Oculus 6DOF immersive exit btn to Menu btn.

README.md
This makes it clear that the rest of the instructions need to be executed inside the cloned directory. E.g. the third_party directory goes inside the FirefoxReality directory at the root.
=> Update README.md: Add a "cd FirefoxReality"

app/src/main/cpp/Skybox.cpp
Fixes #1021
The problem is that TextureCubemap internal initilization is triggered from two threads at the same time, the loader thread, and the main render thread when it binds the cubemap texture for the current frame. This happens because we are using a geometry already added to the scenegraph after a environment change.
=> Fix environment switch glitches

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
We are using "Oculus" instead of "Oculus Go" for the WebVR device name.
I found that this affects Sketchfab performance (with "Oculus Go" it uses a lower quality model/shader). Could this affect other engines @fernandojsg, @cvan?
@daoshengmu Please review the correct name for Quest
=> Set correct Oculus WebVR device name

app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
App controller should be hidden when system has focus.
=> Hide Wave controller if input is captured by system

app/src/main/res/drawable/dialog_background.xml, app/src/main/res/drawable/edittext_background.xml, app/src/main/res/drawable/keyboard_background.xml, app/src/main/res/drawable/main_button.xml, app/src/main/res/drawable/media_controls_background.xml, app/src/main/res/drawable/prompt_background.xml, app/src/main/res/drawable/settings_background.xml, app/src/main/res/drawable/url_background.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimen.xml
See https://github.com/MozillaReality/FirefoxReality/issues/959 (tries to improve the first point on navigation bar and rounded corner dialogs)
This is a simple approach to add some blur, just adding a semitransparent stroke between the shape and the transparent border.
We can set a different size in `<dimen name="blur_radius">2dp</dimen>`
We could also set different radius values per platform (e.g this is more needed on Wave than on Oculus right now)
Anyone else that could test this on Vive Focus? (@philip-lamb @thenadj ?)
=> Blur the edges of UI background shapes

app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java, app/src/main/assets/web_extensions/youtube_webcompat/main.css, app/src/main/assets/web_extensions/youtube_webcompat/main.js, app/src/main/assets/web_extensions/youtube_webcompat/manifest.json
- Fixes #862 
- Fixes #1019
Note: When https://bugzilla.mozilla.org/show_bug.cgi?id=1511177 lands we probably can remove the viewport change injection. That should also avoid the layout change.
=> Add Youtube webcompat webextension

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetPlacement.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/Widget.cpp, app/src/main/cpp/WidgetPlacement.cpp, app/src/main/cpp/WidgetPlacement.h
We are using pretty big textures now for UI due to the Android screen density. VR doesn't have the same density so we may be using more than needed. This PR allows to set a specific texture scaling per widget. The "big" scaling is done on the UI renderer only after each render due to layout changes instead of every frame on the GPU
I set a default value of 0.75f. There may be some better formula taking z into account but it's a starting point. I saw some improvements on the aliasing of the navigation bar on Oculus with Layers enabled (In addition to reduced texture sizes). It should have a similar aliasing effects to creating mipmaps if we are able to set the right value here.
I'd like some more testing on all the platforms. Thoughts?
=> Add support for UI texture scaling

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h, app/src/main/cpp/Device.h, app/src/main/cpp/DeviceDelegate.h, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/oculusvr/cpp/DeviceDelegateOculusVR.h
According to the Oculus docs the clock levels are a baseline, so even setting them to 2 the system can decide to increase them. However, we think something with their throttler is just wrong since with video perf we saw better performance at 4 than 2. If it were dynamic that should not be the case. On #947 some tests performed faster with cpu levels set to 4 than 2.
This PR sets the clock levels to 2 by default, and switches to 4 during WebVR and video playback. The benefit should be saving battery when we are not in WebVR and playing videos. Oculus browser does the same thing (dynamic levels while browsing but max levels in WebVR). My concern is if it affects WebGL while not in WebVR.
Thoughts? Should we use dynamic or fixed clock levels to 4?
Note: We can use the same code in this PR to …
=> User dynamic clock levels on Oculus

app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java, app/src/main/assets/web_extensions/youtube_webcompat/main.css, app/src/main/assets/web_extensions/youtube_webcompat/main.js, app/src/main/assets/web_extensions/youtube_webcompat/manifest.json
=> improve default playback quality of YouTube videos to 1440p (or `vq=`, `quality=` query-string parameter) (fixes issue #1051)

app/src/oculusvrArmDebug/AndroidManifest.xml
Required for oculus store. Tested on Go.
=> Bump OpenGLES version for Oculus

l10n.toml
Sorry for the delay here, I did a small reformat on the locale list, and added the branch data we need for android-l10n.
Philip, are you a good person to rubber-stamp this?
CC @Delphine
=> fixes 1034, minor adjustments to l10n.toml for android-l10n

app/proguard-rules.pro, app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java
Fixes #1077
Depends on: https://bugzilla.mozilla.org/show_bug.cgi?id=1544584
=> Remove android speech dependency from GV using Proguard.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/options/DeveloperOptionsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/options/PrivacyOptionsWidget.java, app/src/main/res/layout/options_privacy.xml, app/src/main/res/values/strings.xml
Fixes #1089.
Expands and corrects descriptions for translators + localize app name in two places.
=> L10n review fixes.

app/build.gradle, versions.gradle
GeckoView uses snakeyaml now, and it is included as a dependency in
the Maven POM, but that doesn't help when we're using a local
GeckoView build.
=> Add snakeyaml to deps

.taskcluster.yml, tools/taskcluster/build_targets.py
New build script allows us to control what gets build base on the release tag. Examples:
`1.1.4a` -> `assembleWavevrArmRelease assembleNoapiArmRelease assembleNoapiArm64Release assembleNoapiX86Release assembleSvrArmRelease assembleSvrArm64Release assembleOculusvrArmRelease assembleOculusvrArm64Release assembleGooglevrArmRelease assembleGooglevrArm64Release`
`1.1.4b-oculusvr:arm64` -> `assembleOculusvrArm64Release`
`1.1.4c:all` - > `assembleWavevrArm assembleNoapiArm assembleNoapiArm64 assembleNoapiX86 assembleSvrArm assembleSvrArm64 assembleOculusvrArm assembleOculusvrArm64 assembleGooglevrArm assembleGooglevrArm64`
`1.1.4d-oculusvr:arm64-wavevr:arm-noapi:x86` -> `assembleOculusvrArm64Release assembleWavevrArmRelease assembleNoapiX86Release` …
=> Allow release tags to control what APKs get built

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java
=> Hide tray when Keyboard is visible

app/src/common/shared/org/mozilla/vrbrowser/ui/views/AutoCompletionView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/main/res/layout/keyboard.xml, app/src/main/res/values/dimen.xml, app/src/main/res/xml/keyboard_numeric.xml
Includes some keyboard refinements from the latest spec published in https://github.com/MozillaReality/FirefoxReality/issues/636
- Improved margins
- Added close button
- Autocompletion view only visible when there are candidates
- Keyboard top margin is the same on all languages whether there is auto completion or not
Note: This PR still doesn't change the keyboard world size, position or angle. I prefer to move that to other PR
=> Keyboard refinements

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/EnglishKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/SpanishKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomKeyboardView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/LanguageSelectorView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/common/shared/org/mozilla/vrbrowser/utils/StringUtils.java, app/src/main/res/drawable/lang_selector_background.xml, app/src/main/res/drawable/lang_selector_button_background.xml, app/src/main/res/drawable/lang_selector_button_color.xml, app/src/main/res/layout/keyboard.xml, app/src/main/res/layout/language_selection.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/xml/keyboard_qwerty_spanish.xml
Note: This branch includes https://github.com/MozillaReality/FirefoxReality/pull/1151 to make review easier. It will be removed when #1151 lands
=> Implement Spanish keyboard

app/src/common/shared/org/mozilla/vrbrowser/utils/InternalPages.java, versions.gradle
Contains the fix for the Java CrashHandler.
https://bugzilla.mozilla.org/show_bug.cgi?id=1550185
=> Bump GeckoView to 68.0.20190509033505

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
I notice composting text are still existing after switching keyboards, we should clean them up to avoid it cause unexpected situations.
=> Clean compositing text when switching keyboard.

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/BaseKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/KeyboardInterface.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetPlacement.java, app/src/main/res/layout/keyboard.xml, app/src/main/res/values/dimen.xml
While implementing the german keyboard I had some width space problems (they have a extra letter in the same line as `enter`). I tried this as a solution but then I switched to making keys a bit smaller.
I believe @daoshengmu also needs this feature for Zhuyin keybord. It may be required for russian too.
=> Add support for resizing alphabetic keyboard with based on language

app/src/main/res/drawable/ic_icon_keyboard_caps.xml, app/src/main/res/drawable/ic_icon_keyboard_shift_off.xml, app/src/main/res/drawable/ic_icon_keyboard_shift_on.xml
- fixes issue #1188, including modified shape per new icons provided in issue #1107 and fixed the Shift On and Caps Lock sizes so they don't get smaller and larger, respectively (as it did previously w/ the old icon)
- this properly fixes the keys so we can revert the revert in PR #1192 (thanks, @MortimerGoro)
- verified there are no visual regressions by checking side by side against this branch vs. f0c5f45a (the commit before the regression in c9d06ba, PR #1107)
=> fix shift key (fixes issue #1188)

app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
It is still too fast. We should adjust it to `0.7`.
=> Adjust Focus touchpad scroll speed.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/ControllerOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DeveloperOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/EnvironmentOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/PrivacyOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/VoiceSearchLanguageOptionsView.java
=> Use the same widget texture for all settings screens

app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/BaseKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/KeyboardInterface.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/main/res/layout/navigation_url.xml
- Most of the implementation already landed in #1116 but we were missing a update call when the keyboard is changed (in addition to autocompletion candidate changes)
- I changed the URL bar action to `go`.
- Test page to try `search` action: https://developer.mozilla.org/es/docs/Web/HTML/Elemento/input/search
It seems that GV reports action `go` for Amazon and Google searches. iPhone browser reports `search`for both pages. May that be another GV bug @bluemarvin @cvan ?
=> Show correct enter key label based on input IME options

versions.gradle
fixes #786 with GeckoView fix from [bug 1543823](https://bugzilla.mozilla.org/show_bug.cgi?id=1543823#c12)
<hr>
with my Oculus Go's system locale set to **Chinese (Traditional) `zh-CN`**:
https://webxr.sh/info
https://aruljohn.com/language.php
https://webxr.sh/info
https://aruljohn.com/language.php
=> Bump GV to 68.0.20190517162900 (fixes #786: `Accept-Language` header)

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayOptionsView.java, app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp, app/src/wavevr/cpp/DeviceDelegateWaveVR.h
In Wave VR [1], doing foveated rendering by using FBO index from two eye buffers. They seem to have trouble in setting `WVR_RenderFoveation(false);`, so I have to restart the app to make it work although this API is under beta.
@MortimerGoro The changing of foveated rendering level in App is not so obvious in Oculus Go, is my feeling wrong?
Regarding to WebVR foveated rendering, we need to do it at the Gecko side, we can do a follow up research at [Bug 1553956](https://bugzilla.mozilla.org/show_bug.cgi?id=1553956) to see if it is possible to make.
[1] https://hub.vive.com/storage/app/doc/en-us/WVR_RenderFoveation.html
=> Enable Wave VR foveated rendering in App. (Fixes #1228)

app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
In WaveVR, we can't get the correct hand info from its runtime, so we have to calculate it by our own. We were using reorient action to trigger the recalculate function, but we can't make sure users do this way before entering the immersive mode. Therefore, I think we should help users do it once when they are going to in the immersive mode.
Fixes #1241. We should recalculate hands before entering the immersive mode in WaveVR.
=> Recalculating WaveVR hand change before entering the immersive mode.

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/crashreporting/CrashReporterService.java, app/src/common/shared/org/mozilla/vrbrowser/crashreporting/GlobalExceptionHandler.java, app/src/main/res/values/non_L10n.xml
See #651
@bluemarvin I can still reproduce a case of infinite restart but the restart is not originated from our CrashReporterService. Has some Gecko behavior changed or does it attempt to restart?
=> Avoid Infinite restart loop in the CrashReporterService

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/crashreporting/CrashReporterService.java, app/src/common/shared/org/mozilla/vrbrowser/crashreporting/GlobalExceptionHandler.java, app/src/main/res/values/non_L10n.xml
Java crashes did not have the correct version or build id set and were thus not showing up on crash stats.
Additionally, the infinite loop crash prevention code was bocking the app from restarting after a normal
crash. So now in addition to keeping a time stamp, a count is kept so it is know if FxR has restarted
multiple times in a short period.
=> Fix Java crash reporter

app/src/googlevr/cpp/DeviceDelegateGoogleVR.cpp, app/src/googlevr/cpp/DeviceDelegateGoogleVR.h, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/DeviceDelegate.h, app/src/main/cpp/DeviceUtils.cpp, app/src/main/cpp/DeviceUtils.h, app/src/main/cpp/ExternalVR.cpp, app/src/main/cpp/ExternalVR.h, app/src/main/cpp/moz_external_vr.h, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/oculusvr/cpp/DeviceDelegateOculusVR.h, app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp, app/src/wavevr/cpp/DeviceDelegateWaveVR.h, versions.gradle
Fixes #937
Do not merge yet, I created this to get some initial feedback of this solution. The problem is that the testcase creates a 2x canvas surface but we are still using the default size in our WebVR swapChain. This PR resizes the swapChain based on the received surface size (taking some thresholds into account).
We need a way to get the WebVR surface size received from Gecko in order to call `SetImmersiveSize` with the correct values. OpenGL ES doesn't have an API to get the texture size until 3.1. Anyway I don't like the OpenGL query solution (getters aren't good for performance). Ideally we can include the surface size in the external_vr struct or also in GeckoSurfaceTexture.java
=> Bump GV version. Fix WebVR texture sharpness issues

app/src/common/shared/org/mozilla/vrbrowser/telemetry/FxRTelemetryScheduler.java, app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java
Telemetry events were not being sent since last update. Removed setPersisted flag from the Telemetry scheduler jobs as it required the RECEIVE_BOOT_COMPLETED permission
=> Fixed the Telemetry issues

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h, app/src/main/cpp/DeviceDelegate.h, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/oculusvr/cpp/DeviceDelegateOculusVR.h, app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp, app/src/wavevr/cpp/DeviceDelegateWaveVR.h
We understand WebVR Foveated-Rendering will be impossible to do in FxR, it has to be in GV. Let's clean up them.
=> Clean up unused WebVR Foveated-Rendering code. (fixes #1275)

app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/SwitchSetting.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/PrivacyOptionsView.java, app/src/main/res/layout/options_privacy.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/strings.xml
Fixes #1231 Added support for globally enable/disable media autoplay.
Fixed a switch setting bug not showing "Off" text upon initialisation.
=> Added global autoplay support

app/src/main/assets/web_extensions/webcompat_vimeo/main.js
- Automatically select better Vimeo quality by default
- Automatically scroll viewport to make full screen icon visible by default.
=> Automatically select better Vimeo quality and make fullscreen visible

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java
Fixes #1336 Microphone permission loop when the permission is rejected.
=> Voice search permission fix

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/PrivacyOptionsView.java, app/src/oculusvr/java/org/mozilla/vrbrowser/PlatformActivity.java, app/src/oculusvrArmDebug/AndroidManifest.xml, app/src/oculusvrArmRelease/AndroidManifest.xml
Fixes #1345 Added a tag in the Oculus manifest to remove inherited camera permission from the parent manifest. Also removed it from the Privacy options just for oculus builds.
=> Remove camera permission in Oculus Go and Quest builds

app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/Pointer.cpp, app/src/main/cpp/Pointer.h
The current pointer size gets too small for widgets that are placed far on the x axis but close on the z.
=> Use real hitPoint distance for pointer scale

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/SuggestionsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/CrashDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/PermissionWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/ChoicePromptWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/PromptWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java
Fixes #1346 Refactored the show methods from UIWidget into a single method that uses a enum for readability.
=> User enum in widget show

app/src/main/res/values-de/strings.xml, app/src/main/res/values-es-rES/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml
State: mozilla-l10n/android-l10n@5d8852d69a1e353d25b241acd4b3e79fee0b4396
=> Import strings from android-l10n

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HoneycombButton.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/PrivacyOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/utils/DeviceType.java
We have added new flavors but we still do the old checks. This produces a different behavior in store builds (e.g. layers disabled in Oculus)
=> Fix BuildConfig.Flavor equality checks

app/src/common/shared/org/mozilla/vrbrowser/ui/views/AutoCompletionView.java, app/src/main/res/values/dimen.xml
=> Autocompletion layout

app/src/main/cpp/Widget.cpp
=> Fix curved-display density mismatch

app/src/googlevr/cpp/DeviceDelegateGoogleVR.cpp
On Daydream devices when the activity was paused, the controllers would get
disabled in BrowserWorld but not in the DeviceDelegate so when the activity
would resume, the controllers in the DeviceDelegate would never re-enable
the controller models in BrowserWorld.
=> Fix controller state on Daydream devices.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/ChoicePromptWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/PromptWidget.java, app/src/main/res/values/dimen.xml
Fixes #1392 Also fixed the dialog min width as we don't get the correct measured height when lists are included in the layout.
=> Fixes choice prompt crash

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/ConfirmPromptWidget.java
Fixes #1402 Fixed button order in confirm prompt
=> Fixed button order in confirm prompt

versions.gradle
Starting to split-off parts of the FxA/sync work into PRs that can land on `master` now, and PRs that will land on a feature branch.
4.0.0 is the latest version of `android-components`. By extension, this gets us a very recent version of application-services dependencies, as well.
In the future we may consider using the -SNAPSHOT variant (essentially, a nightly version)
to keep up with the latest changes in a-c and a-s.
=> Bump a-c dependency to 4.0.0

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserApplication.java, app/src/common/shared/org/mozilla/vrbrowser/browser/BookmarksStore.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/Places.kt
Starting to split-off parts of the FxA/sync work into PRs that can land on master now, and PRs that will land on a feature branch.
This lets us access storage backends from different parts of the system
at the same time. E.g. from both BookmarksStore as well as the upcoming Services
sync integration.
=> Introduce a centralized places.kt which owns storage

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
=> If resize is cancelled, resize back to the screen size it had before entering resize mode.

app/build.gradle, app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp, app/src/wavevr/cpp/native-lib.cpp, tools/taskcluster/build_targets.py, versions.gradle
=> Add Wave 64 bit support

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/main/res/values/dimen.xml
=> Do not resize fullscreen window size if the window size is actually larger than the threshold.

app/src/common/shared/org/mozilla/vrbrowser/browser/HistoryStore.kt
storage.getVisited(listOf(aURL)) returns a container instead of a ptr.
=> Fixed storage.getVisited() is always true warning.

app/src/common/shared/org/mozilla/vrbrowser/ui/views/UIButton.java
In Android > 26 there is crash when trying to show a tooltip in a Button without tooltip text.
STRs:
- Launch FxR in an Android > 26
- Open Settings
- Open languages
- Click on the back button
=> Fixes a crash in tooltips in Android > 26

versions.gradle
Fixes #1399
Also includes updated rules for #1190
=> Bump GV to 70.0.20190726094308

app/proguard-rules.pro, build.gradle, gradle.properties
This PR adds the proguard rules required to make R8 work in full mode. It will allow to reduce compiling times significantly.
In addition, we were not doing correct minification before. We had a rule to keep all classes. I removed that so it has required to add some extra rules such as `WidgetPlacement` class which fields are uses from native.
One of the problematic dependencies was `mozillaspeechlibrary`. I added some rules here but also pushed a PR to add the rules upstream: https://github.com/mozilla/androidspeech/pull/17
Other problematic dependency was Gecko. The fenix tem has already enabled full mode: https://github.com/mozilla-mobile/fenix/blob/master/gradle.properties. But it triggered a weird error in FxR. After some tries I fixed it keeping everything inside `public class …
=> Transition to R8 in full mode

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Do not save window size when resize is cancelled

app/src/main/assets/web_extensions/webcompat_youtube/main.js
Fixes #1426
Found the problem after some research. It seems that youtube processes the `disable_polymer` parameter but removes it from the URL at some point. This causes another override when going back to a previous youtube video, and the forward action is lost there.
GV doesn't have an API to override URLs. You need to cancel the current load and perform another `loadUri`. So I decided to add a history override from the webextension when the page is unloaded to get the parameter back.
=> Fix inactive forward button for videos on youtube.com

app/src/main/cpp/Cylinder.cpp
=> Fix curved mode intersection precision issues that make the laser pointer too sensitive.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayOptionsView.java
Fixes #1457 Fixes the curved display switch not being reset.
=> Fix curved mode reset not working

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryHistogram.java, app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Added telemetry events from #1329
=> Added Multi-window Telemetry

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
There is a slighty different sizing calculation that causes superfluous surface resizes when layer surfaces are created.
Affects #1459 and performance.
=> Avoid superfluous resizes with Layers

app/src/common/shared/org/mozilla/vrbrowser/ui/views/UIButton.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/main/res/values/strings.xml
Fixes #1455 Fixed stop navigation button tooltip
=> Fixed stop navigation button tooltip

app/src/main/cpp/native-lib.cpp
This fixes the missing UI on start up for Oculus and probably SVR.
=> Ensure the vrb::RunnableQueue has been created before the Activiy tries to call it in onCreate()

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
fixes #1459
GeckoView deadlocks if `surfaceChanged` is called within the `onFirstComposite` call, because `surfaceChanged` is synchronous internally.
=> Post firstDrawCallback to avoid a deadlock if the widget is resized in that callback.

app/build.gradle, tools/taskcluster/build_targets.py, versions.gradle
Fixes #1458 Added a .wavevr for non-store WaveVR builds so we can install debug and staging builds without clashing with the preinstalled app id.
Also replace noapi x86 builds with x86_64.
=> Support for WaveVR appId 

app/src/common/shared/org/mozilla/vrbrowser/crashreporting/CrashReporterService.java, app/src/common/shared/org/mozilla/vrbrowser/utils/SystemUtils.java
Code package name and application package names can be different. Explicitly set the package to avoid launching a different staging/release build.
Fixes #1499
=> Fix package name when the activities are restarted

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/ControllerOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DeveloperOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayLanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/EnvironmentOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/PrivacyOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/VoiceSearchLanguageOptionsView.java, app/src/main/res/layout/options_controller.xml, app/src/main/res/layout/options_developer.xml, app/src/main/res/layout/options_display.xml, app/src/main/res/layout/options_environment.xml, app/src/main/res/layout/options_language.xml, app/src/main/res/layout/options_language_content.xml, app/src/main/res/layout/options_language_display.xml, app/src/main/res/layout/options_language_voice.xml, app/src/main/res/layout/options_privacy.xml, app/src/main/res/layout/setting_button.xml, app/src/main/res/layout/setting_switch.xml, app/src/main/res/values/styles.xml
This fixes #1461 fixes #1462 and fixes #1460 by unifying the styling for the settings content views.
=> Unify settings content UI

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/Controller.cpp, app/src/main/cpp/Controller.h, app/src/main/cpp/WidgetMover.cpp, app/src/main/cpp/WidgetMover.h
- Fixes the pointer jump to a different widget during move gestures
- Improved curved mode keyboard movement
=> Capture pointer input during move gestures. Improve curved keyboard move.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/EnvironmentOptionsView.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/VRLayer.cpp, app/src/main/cpp/VRLayer.h, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Fixes #1493
Also makes it possible to switch between stock and custom environments without a restart, even if they have different formats.
=> Fix JPG skyboxes. Do not require restart to switch to a custom env.

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DeveloperOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/PrivacyOptionsView.java, app/src/main/res/layout/options_environment.xml, app/src/main/res/layout/options_language_content.xml, app/src/main/res/layout/options_privacy.xml, app/src/main/res/values/styles.xml
The privacy settings were not being reset correctly.
=> Fixes non working reset for privacy settings

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/AppDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java, app/src/main/res/layout/app_dialog.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/strings.xml
Fixes #641 A dialog has been added to ask the user for permission to store voice samples and transcriptions.
=> Dialog for requesting permission for storing voice samples

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/BrightnessMenuWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/VideoProjectionMenuWidget.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h
Fixes #1468. Also fixes other visual glitches in multiwindow (keyboard dissapearing on a side window depending on the position of your head).
Oculus layers don't support a depth buffer so we have to sort them manually.
=> Improve widgets depth sorting

app/src/main/res/values/dimen.xml
Please check the conversation and the images posted in #1511.
This is an attempt to try a bit higher window height. We should get feedback before landing it.
One problem we have compared to Oculus is that they have a fixed window height, so they have always centered in the same position. For us placing the window higher may feel good in the 1x size but has a bigger impact for the 2X 3X sizes. So we need to find a good balance.
=> Place the window a bit higher

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Fixes #1536 
The problems happens when the flat/curved switch is done to a widget that has never been rendered (e.g. the keyboard starts invisible). The layer waits to receive the first composite notification to allow rendering it. But when a surface is moved to a new layer (e.g. flat to curved) the old layer still receives the callback. This PR also prevents a potential crash if the callback is received after a layer is deallocated (it can happen due to UI and  native render thread differences)
=> Update SurfaceChanged callback target when a Surface is moved to a different layer

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java
Fixes #1538 This looks very much like something that got broken during the multiple multi-window rebases.
=> Fixes not updating the private browsing mode tooltip

app/src/common/shared/org/mozilla/vrbrowser/browser/PermissionDelegate.java
Fixes #1547 The parent handle from the widget was not being assigned before showing the widget and it was always using the one from the window that first created it.
=> Fixes the permission dialog showing in front of the creator window

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStack.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/AlertPromptWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/AuthPromptWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/ChoicePromptWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/ConfirmPromptWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/PromptWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/TextPromptWidget.java, app/src/main/res/layout/prompt_confirm.xml, versions.gradle
Fixes #1557 Gecko bump and new prompt API update
=> New Prompt API

app/src/main/res/values/strings.xml
Fixes #1534 Strings with CDATA should include the whole string.
=> Fixes CDATA issues

app/src/main/cpp/WidgetMover.cpp
This PR fixes the movable keyboard in lay down mode. It should also fix the jump when moving the keyboard.
The y position of they pointer still doesn't perfectly match the initial dragging position, this is due to the curvature change. We can address that as a follow-up
=> Fix movable keyboard in lay down mode

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #1571 Always stay in curved mode unless the curved setting is false and the number of windows is 1. This fixes a bug when changing the curved setting to flat and the windows number was > 1.
=> Always respect user curved mode setting

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionSettings.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStack.java, app/src/main/cpp/WidgetPlacement.cpp
=> Use original URI when switching UA on a page that was redirected

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStack.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionState.java
Fixes #1597 Handle the cases where the GeckoSession state could be null or could be not fully created. This will help to persist correctly and load the home page in a new session in those cases.
=> Fixes sessions restore crashes when the session is null

app/src/main/res/values/strings.xml
Updating legal language around voice collection permissions
=> Update voice collection strings

versions.gradle
Includes https://bugzilla.mozilla.org/show_bug.cgi?id=1574996
Fixes #1543 and #1559
=> Bump GV to 70.0.20190821095414

app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/RussianKeyboard.java
Show the correct string for the Russian keyboard, we were currently showing "Italian"
=> Show the correct string for the Russian keyboard

app/src/common/shared/org/mozilla/vrbrowser/ui/views/UIButton.java
Fixes tooltips not being displayed.
=> Fixes tooltips

app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/SwitchSetting.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsHeader.java, app/src/main/res/layout/options_language_display.xml, app/src/main/res/layout/options_privacy.xml, app/src/main/res/layout/setting_switch.xml, app/src/main/res/values/strings.xml
Replace all the hardcoded Firefox strings
=> Replace all the hardcoded Firefox strings

app/src/main/res/layout/navigation_url.xml, app/src/main/res/values/strings.xml
Fixes https://github.com/mozilla-l10n/android-l10n/pull/62 L10n fixes
=> L10n fixes

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStack.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/PrivacyOptionsView.java, app/src/main/res/layout/options_developer.xml, app/src/main/res/layout/options_privacy.xml, app/src/main/res/values/strings.xml
Fixes #1454 Adds support for clearing the cache. At the moment just clears all the caches until with have a more complete spec to do it more granular. Also I've refactored sessions code and fixed:
- Not all sessions were being recreated for methods that required session recreation
- Removed the intermediate session stack as it's not really necessary we can handle it with the linked hashmap
=> Adds support for clear cache

app/src/common/shared/org/mozilla/vrbrowser/search/suggestions/SuggestionsProvider.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Fixes #1570 Better exception handling for Places related content in suggestions. There seems to be some problem with Places in x86_64 https://mozilla.slack.com/archives/CA4JKKLSG/p1565878585191200 already informed the AC team. In the meantime this helps to show the available content in the awesome bar instead of showing nothing.
=> Added logs and handle CompletableFutures exception

app/CMakeLists.txt, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UISurfaceTextureRenderer.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetPlacement.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/common/shared/org/mozilla/vrbrowser/utils/ViewUtils.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/Cylinder.cpp, app/src/main/cpp/Cylinder.h, app/src/main/cpp/Device.h, app/src/main/cpp/Quad.cpp, app/src/main/cpp/Quad.h, app/src/main/cpp/Widget.cpp, app/src/main/cpp/Widget.h, app/src/main/cpp/WidgetBorder.cpp, app/src/main/cpp/WidgetBorder.h, app/src/main/cpp/WidgetPlacement.cpp, app/src/main/cpp/WidgetPlacement.h, app/src/main/cpp/WidgetResizer.cpp, app/src/main/res/values/colors.xml
=> Implement multiwindow hover and click border effect.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TitleBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/main/res/values/dimen.xml
Fixes #1653.
Also makes the surface for the TitleBar smaller because it was using much more width than needed:
=> Fix TitleBarWidget leak. Reduce TitleBarWidget texture.

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Fixes #1630. Fixes #1634. Fixes #1637.
=> Correctly handle surface resize after the surface is taken by another layer.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/Widget.cpp, app/src/main/cpp/Widget.h
=> Correctly layout quads on a parent cylinder. Center tray with active window.

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h, app/src/main/cpp/Widget.cpp, app/src/main/cpp/Widget.h, app/src/main/cpp/WidgetResizer.cpp, app/src/main/cpp/WidgetResizer.h
=> Set the minimum resize size to 0.5x

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java
Fixes #1640
Notes:
- The PR is build on top of #1639 to ease the testing and prevent the conflicts
- I enabled TW layer clipping during layer resize to prevent some  visual resize glitches.
=> Resize navbar on window focus change. Fix resizing glitches.

app/src/common/shared/org/mozilla/vrbrowser/ui/views/ContextMenu.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/ContextMenuWidget.java, app/src/main/res/layout/context_menu.xml, app/src/main/res/layout/context_menu_item.xml
#1469 Fix context menu size and scrolling issues
=> Fix context menu size and scrolling issues

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
=> Always add the new window to the center. Update tray when windows are moved.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
=> Correctly separate fullscreen resize placement data.

app/src/common/shared/org/mozilla/vrbrowser/browser/Media.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MediaControlsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TitleBarWidget.java
Fixes #1674 Title bar was not getting media updates when the media controls took over the delegate. Allow multiple listeners for media state updates
=> Allow multiple listeners for media state updates

app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomListView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/SuggestionsWidget.java, app/src/main/res/layout/list_popup_window.xml
=> Hide scrollbar in Awesome bar suggestion list if all the content fits.

app/src/main/res/drawable/scrollbar_thumb.xml, app/src/main/res/layout/options_language_content.xml
Fixes #1635 The scrollbar style has been updated in the specs but not in the app.
=> Updated scrollbar theme

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java
Hide notification  if tray is detached or hidden
=> Hide notification  if tray is detached or hidden

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Also restore the sessions activation state based on visibility correctly when pausing/resuming the activity.
=> Set session stack active state based on the window visibility

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #1725 Do not make the session inactive if we are in VR video mode. Also check it when back from an activity pause.
=> Do not make the session inactive if we are in VR video mode

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java
Fixes #1730 Fix tray position when exiting from fullscreen in regular and VR Videos
=> Fix tray position when exiting from fullscreen in regular and VR Videos

app/src/main/res/layout/navigation_bar.xml, app/src/main/res/layout/navigation_bar_fullscreen.xml, app/src/main/res/layout/navigation_bar_resize.xml
Fixes #1726 Fixed the gap between video control buttons
=> Fixed the gap between video control buttons

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #1738 This fixes the multi-window controls being displayed if opening the resize controls while in theatre mode.
=> Do not show the multi-window controls if the window is in theatre mode.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java
Fixes #1715 Correctly restore the bookmarks tray button state after showing a notification.
=> Correctly restore the bookmarks tray button state after showing a notification

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #1713 Hide the context when the window loses focus
=> Hide the context menu when the window loses focus

app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/BookmarkAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/HistoryAdapter.java
Fixes #1695 Hide the context buttons when the motion event moves outside the view.
=> Hide context menu when the action is canceled

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #1744 Fix focus issues when switching between regular and private modes when a non front window is focused.
=> Save the focused window between regular and private sessions

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #1746 Pause other windows when entering immersive mode.
=> Pause/resume other windows when entering/exiting immersive mode

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java
=> Fix crash when the app is closed while playing 360 videos

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Fixes #1705.
We have a array stack overflow possibility when filling the layers array. The main eye buffer is always added after the UI layers, so we need to check `ovrMaxLayerCount - 1` instead of `ovrMaxLayerCount` for UI layers.
I also changed the regular/private switch to hide windows first to make it harder to hit max layers threshold.
=> Fix Oculus layers array stack overflow

app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/BookmarkAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/LibraryItemContextMenu.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/LibraryItemContextMenuWidget.java
Fixes #1756 Fix item not being set before the menu measure is called. Also improved context menu positioning for last rows so the menu doesn't fall outside the library view.
=> Fix item not being set before the menu measure is called

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/BrightnessMenuWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/VideoProjectionMenuWidget.java, app/src/main/res/values/dimen.xml
Fixes #1727.
I tried to improve the depth sorting function with no luck yet (it breaks other things if changed). So this is a safe workaround for v1.4, and I'll try to improve the depth sorting function for v1.5
=> Fix fullscreen video control panel z-order issues

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TopBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #1774 Fixes restoring the window position and size when quitting the app while in fullscreen mode. Before this PR the restored window position was not correct and the restored windows size was the fullscreen window size when quitting the app is windows > 1.
=> Restore window size/position if the app is exited while in fullscreen

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Potential workaround for #1781
=> Do not animate navigation bar fullscreen exit in onDestroy

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetPlacement.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/main/cpp/VRLayer.cpp, app/src/main/cpp/VRLayer.h, app/src/main/cpp/Widget.cpp, app/src/main/cpp/WidgetPlacement.cpp, app/src/main/cpp/WidgetPlacement.h
It's useful to have some name when debugging actual rendered widgets in native.
Note: this is not required for 1.4.
=> Add name property to WidgetPlacement

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Because we only have one Media control, so we need to attach to the window that we want to play VR video. Fixes #1830.
=> Fixing media control misplacement when using multiple windows

.gitignore, build.gradle, gradle/wrapper/gradle-wrapper.properties
Gradle update required by AS 3.5.0
=> Gradle update required by AS 3.5.0

app/src/common/shared/org/mozilla/vrbrowser/utils/LocaleUtils.java
Simplified Chinese CN: zh-Hans-CN
Traditional Chinese TW: zh-Hant-TW
Our current logic only handles size two language code like: en-US.
=> Fixes lanaguages when using lang-script-region type.

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionUtils.java
=> Disable WebRender until it works with FxR

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java
=> Do not overwrite first draw callback on proxified layers

app/src/common/shared/org/mozilla/vrbrowser/browser/HistoryStore.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
I don't why we want to remove the previous URL from the history even though the URLs are the same. IMHO, we should just keep it because they are **HISTORY**.
=> Include VisitType.RELOAD query type when re-visiting.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/BrightnessMenuWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/VideoProjectionMenuWidget.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/res/values/dimen.xml
Also backouts workaround dimension changes included in https://github.com/MozillaReality/FirefoxReality/pull/1767
=> Improve depth sorting: do not clamp hitPoint used for ndc calculation

app/build.gradle, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserApplication.java, app/src/common/shared/org/mozilla/vrbrowser/browser/BookmarksStore.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/Services.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStack.java, app/src/common/shared/org/mozilla/vrbrowser/search/suggestions/SuggestionsProvider.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/AccountsHelper.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java, app/src/main/res/layout/bookmark_item.xml, app/src/main/res/layout/bookmarks.xml, app/src/main/res/layout/settings.xml, app/src/main/res/values/strings.xml, versions.gradle
First `feature/fxa` PR!
Combination of #1389 rebased on top of #1395, and both rebased on top of current `master` now that #1406 and #1405 have landed.
=> Combined PR: FxA+Sync+Send Tab integration & Bookmarks navigation

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TopBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #1722
It's difficult to correctly sync native widget update (move) with the Android compositor render. So I opted for switching the top bar between moving windows.
=> Fix top bar glitch when moving windows

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
=> Update keyboard IME action when input is restarted

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionSettings.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStack.java
When restoring state using session.restoreState, `onLoadRequest` is not called
which causes FxR's UA override logic to not run. To fix this, we remember the
UA override string and restore it.
=> Restore userAgentOverride when restoring state (#1125)

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/main/res/drawable/url_bar_hint_fading_edge.xml, app/src/main/res/layout/navigation_url.xml
=> Fix cropped awesome bar placeholder

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStack.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
Handles the following crashes from unhandled exceptions:
https://crash-stats.mozilla.com/report/index/a0367f38-55b1-45d4-bcfc-27d150191004
https://crash-stats.mozilla.com/report/index/1815e4cf-c2b3-4630-ab42-c15990191004
=> Handle exceptions thrown by java.net.URI

app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/BindingAdapters.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/BookmarkAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/HistoryAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/UIButton.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/LanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java, app/src/main/res/layout/bookmark_item.xml, app/src/main/res/layout/history_item.xml, app/src/main/res/layout/library_notification.xml, app/src/main/res/layout/navigation_url.xml, app/src/main/res/layout/options_header.xml, app/src/main/res/layout/options_language.xml, app/src/main/res/layout/tooltip_tray.xml, app/src/main/res/layout/tray.xml, app/src/main/res/layout/vertical_separator.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
This addresses most of the issues from #1530. Also added support for responsive library panels.
- The copy&paste issue will be addressed in the copy&paste PR
- The scrollbar standarization fix will the another PR
=> UI Polishing

app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
Fixes #1930. It looks like after the recent updates, Focus Plus only can use `WVR_InputId_Alias1_Trigger` to listen the trigger state. Otherwise, when pressing the left on the touchpad, it will send a `WVR_InputId_Alias1_Digital_Trigger`.
=> Making Focus Plus use WVR_InputId_Alias1_Trigger to check trigger only.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TitleBarWidget.java
When having >1 windows and you resize the front window the title from the side windows don't update their positions.
STRs:
- Open three windows
- Resize the front window horizontally
Actual Result:
The title bars of the side windows are not updated
Expected result:
The title bars should always be centered horizontally in the window
=> Update title bar position after neighbour window is resized

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NoInternetWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/main/res/values/dimen.xml
This PR fixes the Y position of all the dialogs that are triggered by the focused window. They were positioned too high on the Y axis when the window height is too high. This PR fixes that and always places them in front of the user.
STRs:
- Open a window
- Resize it vertically to the max
- Open the History panel
- Click on the Clear button
Actual Result
The dialog y position is too high
Expected result
The dialogs should always be in front of the user
=> Standarize dialogs y & z positions

app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomInlineAutocompleteEditText.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SelectionActionWidget.java, app/src/main/res/layout/navigation_url.xml
Fixes #1983
- Correctly update Copy/Cut actions on the URLbar when the selection changes
- Hide or commit autocompletion selection when the user starts a select gesture
- Fix conflict between URL bar scroll gesture and select text gesture
- Do not recreate the CopyPaste menu if the new gesture has the same actions as before (avoids a minor flicker)
=> Copy paste improvements

versions.gradle
This will also avoid some Taskcluster failures as it will use the cached one instead of always look for the latest one.
=> Pin sqliteassethelper library to 2.0.1

app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/DutchKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/options_values.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/keyboard_qwerty_dutch.xml
Closes #1753 Adds support for Dutch keyboard
Also fixes a bug that made the spacebar language string to reappear after clicking a key.
=> Dutch keyboard

app/src/main/cpp/moz_external_vr.h, versions.gradle
Includes a fixed regression for immersive mode. And the bugzilla patches from @daoshengmu.
=> Bump GV to 71.0.20191018095340

app/src/common/shared/org/mozilla/vrbrowser/search/SearchEngineWrapper.java, app/src/common/shared/org/mozilla/vrbrowser/search/suggestions/SuggestionsClient.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/SuggestionsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Force view redraw when showing the awesome bar

app/src/common/shared/org/mozilla/vrbrowser/browser/Services.kt
STR:
- Open Link in a new tab using the longpress menu
- Open Tabs Widget
- The Tab has about:blank instead of the correct URL
=> Fix FxA onLoadRequest breaking background tabs

app/src/main/res/layout/navigation_bar_fullscreen.xml
Reproducible in HTC Vive Focus
=> Fix gaps in the fullscreen bar

app/src/main/res/drawable/tray_background_checked_middle.xml, app/src/main/res/drawable/tray_background_checked_start.xml, app/src/main/res/drawable/tray_background_ckecked_end.xml, app/src/main/res/drawable/tray_background_end_private.xml, app/src/main/res/drawable/tray_background_middle_private.xml, app/src/main/res/drawable/tray_background_start_private.xml, app/src/main/res/drawable/tray_background_unchecked_middle.xml, app/src/main/res/drawable/tray_background_unchecked_start.xml, app/src/main/res/drawable/tray_background_unckecked_end.xml
Closes #2054 It seems that dynamically settings the background doesn't play well with animations in certain cases. I was starting to be a time sink so I've just disabled the animation for the tray and opened a follow-up #2081
The other issues should be fixed by https://github.com/MozillaReality/FirefoxReality/pull/2071
=> Disable tray animations

app/src/common/shared/org/mozilla/vrbrowser/browser/SessionChangeListener.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionState.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
- Implement tab stacking
- Improve SessionChangeListener signatures and get rid of unused listener
- Refactor boolean parameter to int enum
You can easily test it with https://www.w3schools.com/jsref/met_win_prompt.asp
=> Implement tab stacking

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionState.java
I found that SessionSettings were not saved correctly, which can cause restore issues.
Example:
- Open a page with desktop viewport
- Close app
- When FxR is reopened the page has mobile viewport
=> Correctly restore SessionSettings

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/Services.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TabsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/common/shared/org/mozilla/vrbrowser/utils/BitmapCache.java
=> Receive FxA Tabs

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/common/shared/org/mozilla/vrbrowser/utils/BitmapCache.java
Capture tab snapshots when stacking sessions and opening the tabs dialog. It uses a background display/surface when stacking sessions. For other situations we don't need to capture in background because the actions are originated from the tabs panel, which captures snapshots of active sessions now.
=> Capture tab snapshots when stacking sessions and opening the tabs dialog.

app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java, versions.gradle
Per #1854, we need to upgrade Mozilla Android Component to v.19 to avoid unnecessary Glean data migration.
=> Upgrade to Mozilla Android Component v.19.

app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java, versions.gradle
This is a minor fix for app_channel missing in AC 19.0.0. After upgrading to AC 19.0.1, it can get back. The only difference between 19.0.0 and 19.0.1 is Glean bug fixes [1]. We can either choose to merge it to Firefox Reality 6 or hold it until we start the work of the next release.
[1] https://github.com/mozilla-mobile/android-components/compare/v19.0.0...v19.0.1
=> Upgrade to AC 19.0.1 to get app_channel telemetry back.

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/Accounts.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TabsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SendTabDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/WhatsNewWidget.java
This PR fixes two things:
- Send the target tab from the tabs panel, we were sending the active session instead of the one the user is actually sending.
- The initial what's new dialog went to the tabs panel after login. Now it just stays in the browser window.
- Better handling the Send tab -> What's new flow.
=> Whats new dialog fixes

app/src/main/res/layout/navigation_url.xml
STRs:
- Load the content feed, see the left margin in the URL bar
- Open bookmarks/history, see the left margin in the URL bar
This PR fixes that misalignment along with the padding between the popup blocking icon and the secure/loading images.
=> Fixes misalignments in the url bar items

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TitleBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
- Fix wrongly displayed "Pause/Play" button.
- Take into account all windows to set CPU level based on video availability.
fixes #2098
=> Fix wrongly displayed "Pause/Play" button

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
=> Register to Window OnFullscreen changes instead of using GeckoSession.addContextListener

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Improve the UI change reaction time when loading pages. ie. when loading a history/bookmarks item it when initiating a login flow. 
Instead of reacting on page load callback we just hide on page start, helps improve the responsiveness perception.
=> Make the UI react faster to page loads

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
Fixes #2121 This fixes the underlying cause that was that the session was not being properly recreated and affected multiprocess switch and caches clear. 
We actually don't need to recreate for switching the tracking protection so just update the settings now in that case.
=> Fixes issues after switching the tracking protection

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
Fixes #2005 Display the context menu when double clicking on the URL bar
=> Display the context menu when double clicking on the URL bar

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java
Fixes #1988 Fixes #1989
The search widget would call mMozillaSpeechService.cancel() after
receiving a CANCELED status change and get stuck in a continuous loop.
=> Prevent voice search from getting stuck in a cancel loop

versions.gradle
Includes the fix for the restore issue.
fixes #1777
=> Bump GV to 72.0.20191104094118

.taskcluster.yml, README.md, tools/taskcluster/get_third_party.sh
* Use new worker pool names (provisionerId / workerType)
* Use new secret names
=> Bug 1574661 - update to use new TC deployment

app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java
Fixes #2143 There was a mIgnoreNextListener flag that was making the update after the deletion to be ignored. I guess it was added to prevent an extra update in the previous Bookmarks implementation and it's been inherited, but I don't think we need it anymore.
=> Bookmarks deletion fix

app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/main/res/layout/bookmarks.xml, app/src/main/res/layout/bookmarks_narrow.xml, app/src/main/res/layout/bookmarks_wide.xml, app/src/main/res/layout/history.xml, app/src/main/res/layout/history_narrow.xml, app/src/main/res/layout/history_wide.xml
Fixes #2141 Show the header when the history is empty and disable the clear history button when the history is empty.
=> Show the header when the history is empty

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/FxAAccountOptionsView.java
Fixes #2103 Fixes issues caused by calling UI code from the wrong thread.
This seems easier to reproduce using the emulator that a device.
STRs:
- Fresh install
- Start a login from settings
- Finish the login process and let it go back to the Account settings panel
- Go back to the main settings panel
- Click on  language settings
Actual result: The language settings is not visible although is there
Expected: All the widgets should be visible
=> Fixed wrong thread ui call

app/src/main/cpp/BrowserWorld.cpp
fixes #2014 
Invisible widgets are set 1.0f ndc z value to avoid doing unneeded computation in depth sorting. But parenting checking is still done so the pointer can be sorted after a parent that has been hidden and is using the max z 1.0 value.
=> Do not check parent sorting in invisible widgets

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
Fixes #2139 Queue history events while the session is inactive and flush when goes back to active. History events are recorded when the session is foregrounded.
=> Queue History events while the session is inactive

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #2032 We are deleting items with the sole purpose of having a nice looking history without duplicate items. This was causing other issues that the linked one. This PR fixes that moving the processing to the client side instead of Places.
=> Avoid removing history items when updating history

app/src/common/shared/org/mozilla/vrbrowser/browser/Accounts.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/BindingAdapters.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/ButtonSetting.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/FxAAccountOptionsView.java, app/src/main/res/drawable/main_button_text_color.xml, app/src/main/res/drawable/rectangle_button_background.xml, app/src/main/res/layout/bookmarks.xml, app/src/main/res/layout/bookmarks_narrow.xml, app/src/main/res/layout/bookmarks_wide.xml, app/src/main/res/layout/history.xml, app/src/main/res/layout/history_narrow.xml, app/src/main/res/layout/history_wide.xml, app/src/main/res/layout/options_fxa_account.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Fixes #2174 Fixes #2155 Fixes #2156 This PR moves all the syncing logic into the FxA panel.
- All the FxA related buttons have been removed from the History/Bookmarks panels.
- Engines are only updated after the user dismisses the panel and only in the case that the state has changed.
- The user can only sync from the FxA panel.
=> Sync updates

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/LanguageOptionsView.java
Fixes a crash when you remove all the preferred languages.
STRs:
- Open the preferred languages panel
- Remove all the preferred  languages
Result: Crash
Expected: The item should be removed without crashing
=> Fix crash when the preferred language list is empty

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
Fixes #2188
It's a regression from #2110
=> Fix the text/link is wrongly pasted at the end of the URL from the Awesomebar

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Fix context menu still displayed after clicking the clear button

app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/BookmarkAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/HistoryAdapter.java
Expands the mobile bookmarks folder when opening the Bookmarks for the first time.
=> Open the mobile bookmarks folder by default

app/src/common/shared/org/mozilla/vrbrowser/browser/Accounts.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #2201 Crash related to this AS issue: https://github.com/mozilla/application-services/issues/2131
To avoid the issue we close the FxA login tab and load the login scuess URL after a successful login.
=> Avoid the FxA crash when reloading the success page after logout

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/FxAAccountOptionsView.java
Fixes #2203 We are updating the switches state when getting sync callbacks. As we only change the sync state when dismissing the panel it makes more sense to not update the buttons as if you change them and sync, you are still getting the previous state.
=> Fix switch state when syncing in the FxA panel

app/src/main/cpp/BrowserWorld.cpp
=> Sort widgets by parent before updating all

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Do not show empty selection menu

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/AllowedPopUpsOptionsView.java
Fixes #2122 Show the popups scrollbar and make sure we always scroll to the first row when showing the popups view.
=> Show the scrollbar when popups view is shown

app/src/common/shared/org/mozilla/vrbrowser/browser/Accounts.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/Services.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
STRs:
- Log into FxA
- When the login in flow is finished close all the tabs
- Click back and quit the app
- Open the app
Expected result:
The Content feed is the only opened tab
Actual result:
The FxA authentication tab is opened on top of the content feed one
=> Avoid opening the FxA authentication success tab if the account is existing/restored

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SendTabDialogWidget.java
Fixes #2235 Hide the tabs send button until we have  updated the devices and the  devices list os not empty.
=> Hide the tabs send button until we have  updated the devices

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
Force URL bar top parent to gain focus after a URL is loaded to avoid children to get it and make the URL bar to look focused.
STRs:
- Login FxA
- Click on the URL bar
- Click on the Hamburger menu
- Share a tab from another device
- Click the home button
- Resume the app
Actual result:
- The URL bar is in a focused state
Expected result:
- The URL bar shouldn't be in a focused state
=> Fix url bar focus issues

app/src/common/shared/org/mozilla/vrbrowser/browser/Media.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TitleBarWidget.java
Fixes #2158 Fixes #2160 Only show the media controls if the media has already been played.
We will need to decide if we want to revert this when this bug is fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1524092
=> Show title media controls only if media has been already started

app/src/common/shared/org/mozilla/vrbrowser/browser/PromptDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/main/res/values/strings.xml
I used this html for testing
[index.html.zip](https://github.com/MozillaReality/FirefoxReality/files/3814444/index.html.zip)
=> Add support for GeckoSession.ContentDelegate.onSlowScript

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java
Fixes #2142 Calling beginAuthenticationAsync several times in a row seems to mess up FxA. We now avoid this hiding the settings panel right after starting the login flow.
The STRs to reproduce are:
- Launch FxA
- Open settings
- Click on the FxA login button several times in a row before the panel is dismissed
- Complete the login flow
Result:
- Login flow is not completed
Expected:
- Login flow is completed
=> Fix intermitted FxA logging issues

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NoInternetWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/UIDialog.java, app/src/common/shared/org/mozilla/vrbrowser/utils/ConnectivityReceiver.java
Fixes #1975 Moving the No Internet dialog in front of the transport controls makes it too close to the user. Instead of that we hide the transport controls when the no internet dialog is displayed. If the user clicks in the video while the no internet dialog is visible, it dismisses it and the transport controls are displayed again.
Also added a listener for the connectivity status so we can eventually listen to that events from any widget.
=> Make No internet dialog and transport controls not to collide

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/PromptDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/browser/Services.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionSettings.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionState.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #2227
To prevent memory exhaustion, this patch watches for memory trim system
callbacks and suspends inactive tabs by deleting the GeckoSession.
Additionally, when the application is started or resumed, inactive tabs will
not have a GeckoSession created until they are viewed. Any new background tab
will also not have a GeckoSession created until the tab is viewed.
=> Prevent GeckoSession creation until tab is viewed

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
=> Do not let a received tab take ownership of the window when it's full-screened or playing a immersive video

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
Fixes #2248 Hide the popup notifications when moving windows
=> Hide the popup notifications when moving windows

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
Fixes #2280 Remove the version check, always show if it's not been displayed before
=> Remove the version check, always show if it's not been displayed before

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #2281 Deactivate current session when receiving a new tab
=> Deactivate current session when receiving a new tab

app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
This fixes an issue with the window count weighted mean that was accounting for the already opened windows after the telemetry was flushed.
Also after talking to @daoshengmu we decided that is better to force a telemetry status ping every time the app is created for easier telemetry status tracking in the backend. 
After this patch the telemetry status ping is always sent:
- When the app is opened
- When the user changes the telemetry status using the privacy options switch
=> Fix the open windows weighted mean calculation

app/src/common/shared/org/mozilla/vrbrowser/ui/views/HoneycombButton.java, app/src/main/res/layout/settings.xml, app/src/main/res/values/attrs.xml
Fixes #2302 Avoid tinting the profile icon for FxA honeycomb
=> Avoid tinting the profile icon for FxA honeycomb

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SelectionActionWidget.java
=> Fix Selection Action menu alignment on the Awesome Bar

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes crash https://crash-stats.mozilla.com/report/index/0a459b83-67c7-44d3-8d61-5117e0191120
=> Ensure parent session is active before setting in Window

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Don't keep the text selected after it's copied.

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
=> Reuse the last frame and tracking when a VR frame is discarded in Oculus

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/VideoProjectionMenuWidget.java
=> Correctly update media control selected projection

app/src/common/shared/org/mozilla/vrbrowser/ui/callbacks/BookmarksCallback.java, app/src/common/shared/org/mozilla/vrbrowser/ui/callbacks/HistoryCallback.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #1955 Close the library panels explicitly after clicking on a link instead of using the Progress callbacks. This should speed up the panel dismiss after clicking on a link and also fix the reported issue.
=> Dismiss library panels explicitly

app/src/common/shared/org/mozilla/vrbrowser/browser/Accounts.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/FxAAccountOptionsView.java, app/src/main/res/values/non_L10n.xml
Fixes #2337 Adds support for multiple accounts last sync time
Related https://github.com/mozilla-mobile/android-components/issues/5118
=> Adds support for multiple accounts last sync time

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
=> Invert horizontal scrolling

app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomFastScroller.java
Fixes #1986.
There're two issues of fast scroller.
1. scrollingBy is a float but we return it as a int and forget Java is down-casting, so it make us have a small gap to the end position of top or bottom. We should make negative value to be floor() and positive value to be ceil().
2. When `absoluteOffset < totalPossibleOffset && absoluteOffset >= 0`, we still remain some offset and its absolute value is less than `mVerticalThumbHeight`. So, we need to handle this remaining values.
=> Making fast scroller still be available to scroll its last part.

app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/RadioGroupSetting.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NoInternetWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TabsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/BaseAppDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/CrashDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/PermissionWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/RestartDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/UIDialog.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/WhatsNewWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/ChoicePromptWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/ConfirmPromptWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/PromptWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java
Fixes #2329 This PR fixes the following issues:
- The "Send Tab to Device" prompt is auto dismissed when trying to send a tab from the Hamburger menu after the app is resumed issue should be fixed now.
- UIDialog focus. After coming from suspension the focus was being requested too early and for dialogs like the NoInternet dialog (that are shown right after the activity is resumed) the focus request was not being processed. Now we enqueue the focus request so it is correctly processed in those cases.
- Adds a world click listener to the UIDialog. Most dialogs were already adding this so makes sense to refactor it a to a common place. Also there is an issue when resuming the activity twice. In that case the app focus is reset and old focus is null so dialogs couldn't be dismissed clicking …
=> Fixes UIDialog focus issues

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionState.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
- Fixes #2356
- Fixes issue where switching Multiprocess in the developer panel would freeze the session.
- Fixes default private browsing page not getting displayed when recreating a private browsing session.
=> Ensure Sessions are recreated correctly when clearing data

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MediaControlsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/VideoProjectionMenuWidget.java
Fixes #1935 The Video Projection menu is not dismissed when clicking the other buttons from the on screen controls
=> Dismiss the projection menu when clicking on any other media button

app/build.gradle, app/src/common/shared/org/mozilla/vrbrowser/browser/Accounts.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/Services.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/EngineProvider.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/WhatsNewWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java, versions.gradle
Closes https://github.com/MozillaReality/FirefoxReality/issues/1397 
This addresses some comments from @grigoryk that didn't make it to the main PR. 
- getAuthenticationUrlAsync function refactoring: https://github.com/MozillaReality/FirefoxReality/pull/1973#discussion_r337533325
- Use a GeckWebExecutor for FxA requests
- Megazord integration: https://mozilla.github.io/application-services/docs/applications/consuming-megazord-libraries.html
The WorkManager auto-initialization fix is still there as crashes are still happening without this and we haven't found the cause.
=> FxA updates

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/SuggestionsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SelectionActionWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/ContextMenuWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/HamburgerMenuWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/LibraryMenuWidget.java
Fixes:
- Context menus (window, history/bookmarks) are being hidden right after being displayed. This is probably related to the fact that we are now always forcing the UIWidget to request focus after being shown and we weren't yet checking for `isEqualOrChildrenOf` in some of them.
- The awesome bar hiding animation happens in the new window when detached from a previous window.
=> Fix for disappearing context menus

app/src/common/shared/org/mozilla/vrbrowser/ui/callbacks/BookmarksCallback.java, app/src/common/shared/org/mozilla/vrbrowser/ui/callbacks/HistoryCallback.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #2366 This reverts https://github.com/MozillaReality/FirefoxReality/pull/2353 and moves the library panels dismiss to the `LoadRequest` event as it's the first event we get when a page load starts. 
This will cause a regression in https://github.com/MozillaReality/FirefoxReality/issues/1955 but there is really no better way of handling this as we need to close the panels with a new URL is loaded and that could happen from multiple places: URL buttons (back, forward, reload), Settings help/survey, history/bookmark links, voice search, etc. So looking again at the problem I think this is still our best option.
=> Use LoadRequest event to close library panels

app/src/common/shared/org/mozilla/vrbrowser/browser/Accounts.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/BookmarksStore.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/HistoryStore.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/Places.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/Services.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/Bookmark.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/CheckboxDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/FxAAccountOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/utils/ViewUtils.java, app/src/main/res/layout/bookmark_item_folder.xml, app/src/main/res/layout/checkbox_dialog.xml, app/src/main/res/layout/honeycomb_button.xml, app/src/main/res/layout/send_tabs_display.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/strings.xml
Closes #2309 Adds support for clearing bookmarks and history when signing out from the FxA account.
AC/AS doesn't support clearing History/Bookmarks. Any record deletion is synced back with the account when the user signs-in again. This is a temporary hack until https://github.com/mozilla/application-services/issues/2250 is fixed and we can safely clear the storage after an account is signed-out.
=> Support for clearing bookmarks and history when signing out

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SelectionActionWidget.java, app/src/main/res/values/dimen.xml
In some languages with longer texts the selection menu items are cropped. This PR correctly wraps the content to the text size.
=> Fix cropped items in Selection Action menu

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
Fixes #2385
Regression from #2380
=> Use the FxR canGoBack() logic instead of the GeckoSession.canGoBack logic when dispatching onCanGoBack event

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Handle potential exception capturing snapshots

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #2373 Fixes #2372 We were calling setActive twice when pausing/resuming the app and that seems to mess up GV state and triggered a JS error in the FxA login page: `throw new Error('submit already in progress');`
This could affect any other website, not only FxA.
STRs:
- SignIn using a non existing account (you can just add a `+n` to an existing account: user+n@mozilla.com)
- Fill the form and continue
- An email with the code should be received in that account
- When checking the code, click on the home button to pause the activity (otherwise it works)
- Resume the app again, put the code and click on Verify
Result: The Verify button doesn't work
=> Avoid duplicated  GeckoSession setActive calls

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/main/res/values/non_L10n.xml
=> Disable multiprocess by default

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
=> Use CopyOnWriteArrayList for all Session event listeners

app/src/main/cpp/moz_external_vr.h, versions.gradle
Includes https://bugzilla.mozilla.org/show_bug.cgi?id=1598483
Required for #2237
=> Bump GV to v72.0.20191202091209

app/proguard-rules.pro, versions.gradle
Includes:
- https://github.com/mozilla/androidspeech/pull/17
- https://github.com/mozilla/androidspeech/commit/d2f45141906fadc644d617836e6ae18255c2dfac
=> Bump mozilla-speech to v1.0.9

app/src/common/shared/org/mozilla/vrbrowser/browser/HistoryStore.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/utils/UrlUtils.java
Fixes #1839 Omit history redirects. Now we should just log the url that initiated the request.
=> Omit redirections in history

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
Fixes #2355 Add support for tab/windows adb parameters. Also improves the way we handle intent parameters. Now you don't need to supply a data URI to change the homepage/e10s.
=> Add support for tab/windows adb parameters

app/src/common/shared/org/mozilla/vrbrowser/ui/callbacks/BookmarksCallback.java, app/src/common/shared/org/mozilla/vrbrowser/ui/callbacks/HistoryCallback.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
GV doesn't generate page load events when loading an anchor of the same page. 
STRs:
- Open a site with anchors
- Click on different icons
- Open History and click on an anchor history item
Expect:
History panel should be closed
Actual:
The History panel is not closed
=> Close Library panels when clicking on an anchor

app/src/common/shared/org/mozilla/vrbrowser/browser/PermissionDelegate.java, app/src/main/cpp/moz_external_vr.h, versions.gradle
WebXR permission are landed (https://bugzilla.mozilla.org/show_bug.cgi?id=1580567 and https://bugzilla.mozilla.org/show_bug.cgi?id=1599927), so we need to bump to a new version of GV.
I also give a quick fix for WebXR permission UI in FxR, the final solution needs to wait for #2413.
=> Bump GV to v73.0.20191212095326

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Do not forward motion events to GeckoSession when library panels visible in the window

app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/Controller.cpp, app/src/main/cpp/Controller.h, app/src/main/cpp/ControllerContainer.cpp, app/src/main/cpp/ControllerContainer.h, app/src/main/cpp/ControllerDelegate.h, app/src/main/cpp/ExternalVR.cpp, app/src/main/cpp/ExternalVR.h, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
Fixes #173. In this PR, we start to support gamepad haptics feedback in the immersive mode. We also can use `ControllerContainer->SetHapticsFeedback()` to give parameters to ask perform vibration for other usages.
@bluemarvin One of my My Vive Focus controllers seems to be broken, so please help verify if it works to you. Also, it shows `W/Wave_SDK: WVR_TriggerVibration with API Level 4 is not supported by the current Runtime version 3` when using `WVR_TriggerVibration` even though I have updated WaveSDK from [sdk-updates](https://github.com/MozillaReality/FirefoxReality-android-third-party/tree/sdk-updates).
=> Making WaveVR/OculusVR controllers support haptic feedback

app/build.gradle, build.gradle, versions.gradle
Closes #2388 This PR migrates to the new Glean build system (as the previous one is tagged as deprecated).
Other than that nothing has changed, we still need to delete the generated Kotlin files and the markdown docs so they get generated again.
=> Glean build system update

app/src/main/assets/web_extensions/webcompat_youtube/background.js, app/src/main/assets/web_extensions/webcompat_youtube/main.css, app/src/main/assets/web_extensions/webcompat_youtube/main.js, app/src/main/assets/web_extensions/webcompat_youtube/manifest.json
- Fixes unneeded horizontal scrolling
- Fixes #2453
- Fixes #2463
- Fixes #2457 (I'll handle disabling high res as a follow-up in devices such as Oculus Go)
- Fixes/Improves #2016 (I fixed potential duplicated selectQuality calls)
- Fixes #870
- Fixes #2459
=> Youtube Web Extension refactor

.taskcluster.yml, app/build.gradle, app/src/common/shared/org/mozilla/vrbrowser/browser/Accounts.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/Services.kt, app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java, app/src/test/java/org/mozilla/vrbrowser/GleanMetricsServiceTest.kt, versions.gradle
=> Support Glean metric unit tests

app/src/main/assets/userAgentOverride.json, app/src/main/assets/web_extensions/webcompat_youtube/background.js, app/src/main/assets/web_extensions/webcompat_youtube/main.js
I've found a better responsive layout using the same User Agent as Oculus Browser and disabling the polymer hack we had.
- Fixes #2507
- Fixes #2506
- Fixes #2501
- Seems to fix #2016 (I was able to reproduce it before this patch but not after)
=> Improve youtube layout

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/RestartDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/PrivacyOptionsView.java, app/src/main/res/layout/options_privacy.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/strings.xml
Fixes #2354 Fixes #2436 Also make sure that we persist sessions state before restating.
=> Setting for enable/disable restoring tabs

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionSettings.java, app/src/common/shared/org/mozilla/vrbrowser/search/GeolocationLocalizationProvider.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomInlineAutocompleteEditText.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/SingleEditSetting.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SendTabDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/FxAAccountOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/utils/ViewUtils.java
Fixes #2449 After a successful FxA login if the origin was the Account panel from settings, we were toggling the panel but the user might have it opened already. Now we make sure that if it's opened just transits to the Account panel or we open it otherwise.
=> Show Settings instead of toggling after a fxa login

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fix #2553 Only show the success screen and open login origin if the account creation was user initiated
=> Only show login success if account creation was user initiated

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/EngineProvider.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/utils/InternalPages.java, app/src/main/res/raw/error_pages.html, app/src/main/res/raw/error_style.css, versions.gradle
Fixes #2512  Add invalid certificate bypass to ssl error pages. When reviewed I'll make a PR for adding this to AC `error-pages`.
=>  Add invalid certificate bypass to ssl error pages

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/ContentLanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayLanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/VoiceSearchLanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/utils/LocaleUtils.java
=> Use system language as default content language

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/VideoProjectionMenuWidget.java
=> Clear projection menu selection if there isn't one selected

app/src/main/res/values/dimen.xml
Fixes #2519 Fixes #2499 Make the base dialog taller to fit all the languages
=> Make the base dialog taller to fit all the languages

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Fixes #2448 Use show/hide instead of setVisible to ensure back handler is removed
=> Fix immersive mode exit after projection is opened

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
Fixes #2415 Session stacking events are currently sent in cascade for all the children of a session. When any of those children are already attached to a window that triggers the reported issue as the new session is attached to the parent's  and all the attached children's windows.
=> Do not send stack callbacks for child sessions

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TabsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SendTabDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/UIDialog.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/WhatsNewWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java
Fixes #2449 Fixes #2571 Stack dialogs when showing/hiding. Dialogs are pushed when showing and popped when hidden.
STRs:
- Turn Off WiFi
- Open: Settings -> Languages -> Display Languages
- Choose a different language, the restart dialog should appear
- Click on the home button
- Resume FxR
Expected Result:
You should see the connection dialog and dismissing that one should go back to the Restart dialog.
=> Dialog stacking

app/src/common/shared/org/mozilla/vrbrowser/ui/views/ClippedEventDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HoneycombButton.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/VectorClippedEventDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/VectorShape.java, app/src/main/res/values/attrs.xml
Fixes #2524 Added support for a delegate that clips input based on a vector resource. Sadly this only works for vector based drawable resources as there is no easy way of creating paths and regions from shapes, we would need to implement that to support clipping of the rest of the UI elements as most of them are shape based.
=> Fixes #2524 Honeycomb button clipping

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/SuggestionsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SelectionActionWidget.java, app/src/main/res/drawable/selection_menu_background.xml, app/src/main/res/drawable/selection_menu_background_triangle.xml, app/src/main/res/layout/list_popup_window_item.xml
Fixes #1946 Adds support for action menu in the awesome bar currently only supporting copying the row's URL. A border has been added to the actions menu (approved) as the background color it's the same as the awesome bar's background color.
=> Fixes #1946 Awesome bar copy url

app/src/main/assets/web_extensions/webcompat_youtube/main.css
=> Workaround for Yotube homepage layout

app/src/main/cpp/BrowserWorld.cpp
=> Fix skybox reverting to non-void after exiting immersive theatre mode.

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UISurfaceTextureRenderer.java, app/src/main/res/values/non_L10n.xml
=> Enable hardware renderer and don't draw after onStop/onDestroy

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes https://crash-stats.mozilla.com/signature/?product=FirefoxReality&version=72.0a1&signature=java.lang.NullPointerException%3A%20at%20org.mozilla.vrbrowser.ui.widgets.Windows.focusWindow%28Windows.java%29&date=%3E%3D2019-12-05T16%3A36%3A00.000Z&date=%3C2019-12-12T16%3A36%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1
=> Added check to avoid the nullpointerexception when focusing a window

app/src/main/res/layout/prompt_auth.xml, app/src/main/res/layout/prompt_dialog.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/styles.xml
Fixes #2594 Make the dialog bigger to fit alllanguages
=> Fixes #2594 Fixes L10n with the prompt widget

app/src/common/shared/org/mozilla/vrbrowser/browser/PermissionDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/EngineProvider.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayOptionsView.java
=> Handle the new autoplay permissions

app/src/common/shared/org/mozilla/vrbrowser/browser/Accounts.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/FxAAccountOptionsView.java
Fixes #2411 Fixes #2409 We were syncing only when the user explicitly did it or after exiting the accounts dialog but this has some side effects like the issue one. I've moved this to the same way as Fenix does it, we might encounter past issues like the sync status being reverted if changing it and syncing right away but this is more similar to how Fenix works and users shouldn't be syncing that much so I guess it's better to have real time sync.
=> FxA sync fixes

app/src/main/assets/web_extensions/webcompat_youtube/main.css, app/src/main/assets/web_extensions/webcompat_youtube/main.js
=> Fix Youtube 360 stereo video layout issues

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TitleBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Preemptive null checks for:
https://crash-stats.mozilla.com/signature/?product=FirefoxReality&version=74.0a1&signature=java.lang.NullPointerException%3A%20at%20org.mozilla.vrbrowser.ui.widgets.TitleBarWidget.setIsInsecure%28TitleBarWidget.java%29&date=%3E%3D2020-01-07T15%3A43%3A00.000Z&date=%3C2020-01-14T15%3A43%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1
=> Preemptive null checks to avoid crashes in the TitleBar widget

app/src/main/assets/web_extensions/webcompat_vimeo/main.js, app/src/main/assets/web_extensions/webcompat_youtube/main.js
Fixes #2465
Test videos:
- https://vimeo.com/214224792
- https://www.youtube.com/watch?v=vxNriWfhRRA
=> Autodetect 360 stereo projection

app/src/main/res/layout/options_footer.xml, app/src/main/res/layout/options_header.xml, app/src/main/res/layout/setting_button.xml, app/src/main/res/layout/setting_edit.xml, app/src/main/res/layout/setting_radio_group.xml, app/src/main/res/layout/setting_radio_group_v.xml, app/src/main/res/layout/setting_switch.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/styles.xml
Fixes #2529 Made all the settings custom widgets to wrap their content to avoid overflow issues with different languages. I've also made the button a bit wider so all languages fit.
=> Fixes #2529 Better L10n support in settings

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/ContentLanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayLanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/LanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/VoiceSearchLanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/utils/LocaleUtils.java
Fixes #2670 Several language fixes to support internally unsupported languages.
=> Fixes #2670 Language fixes

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #2662  Focus window can handle null windows. Revert the null check
=> Fixes #2662 Fix focus when switching to private mode

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/main/res/values/non_L10n.xml
This reverts commit 91e3eaac3a5f4c4bf6f5402ed7f31b2ee191ea4c.
=> Fixes #2684 Revert "Enable e10s by default (#2615)"

app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java
Fixes #2408 Fixes #2653 We were removing items from the adapter and also after the history update. Same for Bookmarks.
=> Fixes #2408 Fixes #2653 Avoid double removing items when deleting

app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomKeyboardView.java
Fixes #2565 The default Android implementation looks for the closes key when clicking outside of an edge key.
=> Fixes #2565 Fixes clicks outside key bounds

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
Fixes #2429 Position the caret at the start position after cutting the text
=> Fixes #2429 Position the caret at the start position after cutting the text

app/src/main/res/layout/vertical_separator.xml, app/src/main/res/values/dimen.xml
Fixes #1941 Fix the tray separator
=> Fixes #1941 Fix the tray separator

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/UIDialog.java
Fixes #2706 When quitting the app the process is not cleaned in Quest and the static memory is still alive when restarting. This forces that the Dialog is removed from the stack when the app is destroyed.
=> Fixes #2706 Remove dialog from stack when released

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/utils/UrlUtils.java
Fixes #2718 URLs with uppercase letters trigger a search
=> Fixes #2718 URLs with uppercase letters trigger a search

app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #2250 Fixes #2431 Fixes the keyboard being displayed while scrolling the library panels and also the issue with instantly hiding the context menu for the last list item.
=> Fixes #2250 Fixes #2431 Library panels polishing

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NotificationManager.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SendTabDialogWidget.java, app/src/main/res/layout/library_notification.xml
Fixes #2375 Fixes #2564 This PR addresses the referenced issues and also refactors the current notification code and exposes a NotificationManager for an easier centralized notification management.
- If the tray is visible they are displayed above the corresponding button
- If the tray is not visible they are displayed in the middle of the browser window
- If in fullscreen mode, they are diplayed under the navigation bar
=> Fixes #2375 Fixes #2564 Improve notification visibility

app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SignOutDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/ContentLanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/ControllerOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DeveloperOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayLanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/EnvironmentOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/FxAAccountOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/LanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/PopUpExceptionsOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/PrivacyOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/VoiceSearchLanguageOptionsView.java
Before this after a config change or a language change settings were reset to the main settings panel and bookmarks and history panels were closed. This PR fixes that.
=> Keep currently open dialogs after a config change

app/src/picovr/cpp/native-lib.cpp, app/src/picovr/java/org/mozilla/vrbrowser/PlatformActivity.java
For PicoVR 6dof controllers, the primary controller is the one with focus when the application
is launched. The is an additional call that determines which hand the primary controller is in.
=> Fix PicoVR 6dof hand detection

app/src/main/cpp/Skybox.cpp, app/src/main/cpp/native-lib.cpp, app/src/picovr/cpp/native-lib.cpp, app/src/wavevr/cpp/native-lib.cpp
=> Ensure RunnableQueue is reattached when new render thread starts

app/src/common/shared/org/mozilla/vrbrowser/ui/views/TabView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TabsWidget.java
Fixes #2725 Do not show the share button for private session in the tabs view
=> Fixes #2725 Do not show the share button for private session in the tabs view

app/src/main/cpp/ExternalBlitter.cpp, app/src/main/cpp/GeckoSurfaceTexture.cpp
I hit a JNI reference overflow when working on exit from WebXR. This happens because exit is not working yet and the ExternalBlitter->cancelFrame() is called every frame, leading to a crash after some seconds.
The leak also happens in WebVR but in a slower pace
=> Fix leaked JNI local reference in GeckoSurfaceTexture

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NotificationManager.java
Fixes #2760 Fixes #2759 Fixes #2762 Correct position for the Popup notification. Do not request focus for notifications.
=> Fixes #2760 Fixes #2759 Fixes #2762 Notification fixes

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
Fixes #2562 Handle shift switching also for text keys
=> Fixes #2562 Handle shift switching also for text keys

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NotificationManager.java
Fixes #2757 Remove the notification Id when closed by a back button click
=> Fixes #2757 Remove the notification Id when closed by a back button click

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/common/shared/org/mozilla/vrbrowser/utils/UrlUtils.java
Fixes #1945 Restore library panels. I really don't like to have a flag to know if the user has initiated the interaction so if there is a better alternative I'd be happy to change this. Without the flag the panels would be closed during the restore when about:blank and home are loaded as we always close them when there is a navigation event.
=> Fixes #1945 Restore library panels

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserApplication.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/Language.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/LanguagesAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/WindowViewModel.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/ContentLanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayLanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/LanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/VoiceSearchLanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/utils/LocaleUtils.java, app/src/common/shared/org/mozilla/vrbrowser/utils/StringUtils.java, app/src/main/res/layout/language_item.xml, app/src/main/res/layout/navigation_url.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/strings.xml
This adds support for a "Follow system language" placeholder that uses whatever the system locale is as long as it's supported by FxR, otherwise it falls back to en-US. 
Also fixes some issues with the correct language hot reload. Now we should be able to change the language either from the Settings or from the system settings and everything so be instantly localized in the new language.
Things to test:
- Change the language from the language setting: All the UI strings should be now localized in the new language
- Click home - Go to the system settings - Change the language - Go back to the app: All the UI strings should be now localized in the new language
- Reset the languages: The UI should show "Follow the system Language" and all the strings should be localized in the system …
=> Follow system language

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #2794 Close library panels when a new request is loaded
=> Fixes #2794 Close library panels when a new request is loaded

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/BookmarksStore.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java
Now after a language change the bookmark titles should be updated correctly.
=> Update Bookmarks strings after a language change

app/src/common/shared/org/mozilla/vrbrowser/ui/views/UIButton.java
Fixes #2809 Fixing my own mistake of not adding the version check when adding the Android 8 long click fix to UIButton.
=> Fixes #2809 Check the Android version before adding the long click fix

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #2794 Back/Forward don't trigger an onLoadRequest so we need to implement a navigation bar listener to get those. Any other GV navigation event we could rely on gets dumped at initialization time and closes the library panels when restoring.
=> Fixes #2794 Dismiss Library panels when navigating back/forward

app/src/main/res/drawable/tab_overlay_checked.xml, app/src/main/res/drawable/tab_overlay_unchecked.xml
Fixes #2722 We can ask for design if necessary, this is just the most obvious way to quickly fix it.
=> Fixes #2722 Use a dark overlay in a hover tab in select mode

app/src/common/shared/org/mozilla/vrbrowser/ui/views/TabView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TabsWidget.java
Fixes #2726 Restore the hover state after send button is clicked in a tab view
=> Fixes #2726 Restore the hover state after send button is clicked in a tab view

app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/SettingsEditText.java
Fixes #2821 Disable soft input on focus for the SettingsEditText text fields
=> Fixes #2821 Disable soft input on focus for the SettingsEditText text fields

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TabsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SendTabDialogWidget.java
Fixes #2818 Make sure only one instance on the send tab dialog is alive
=> Fixes #2818 Make sure only one instance on the send tab dialog is alive

app/src/oculusvr/cpp/OculusVRLayers.cpp
Fixes #2826 Restores lost base method calls in Oculus layers
=> Fixes #2826 Restores lost base method calls in Oculus layers

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NotificationManager.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java
Fixes #2829 Hide all notifications when clicking on tray actions. Also avoid concurrent modifications of the notifications map
=> Fixes #2829 Hide all notifications when clicking on tray actions

app/src/common/shared/org/mozilla/vrbrowser/ui/views/UIButton.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java
Fixes #2807 Fixes forward compatibility of the tooltip text tag
=> Fixes #2807 Fixes forward compatibility of the tooltip text tag

app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java
Fixes #2810 Dismiss the library menu when the list is focused. Verified that this didn't regress #2250
=> Fixes #2810 Dismiss the library menu when the list is focused

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Remove the back handler for non focused views.
STRs:
- Open two windows
- Open History/Bookmarks in one of them
- Focus the other window
- Click on the back button
Expected result: We go back in history in the currently focused window
Actual result: The History/Bookmark panel is closed in the non focused window.
=> Remove the back handler for non focused views

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #2854 Queue setview calls until the surface is ready
=> Fixes #2854 Queue setview calls until the surface is ready

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Fix deadlock when managing tabs with library panel open

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionSettings.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayOptionsView.java, app/src/main/res/layout/options_display.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/options_values.xml
This patch enables e10s which fixes a bug in setting the user agent in GV.
Additionally, it remove the option for making the desktop user agent the default.
The user must use the desktop switch in the hamburger menu now.
Fixes #2885
=> Fix user agent override

app/build.gradle, versions.gradle
The custom "fenix" megazord contains all the same code as appears in
the default appservices megazord, so consumers who are using it are
adding complexity to their build process for no gain. The appservices
team intend to stop building the fenix megazord and instead encourage
consumers to use the default full megazord. See additional discussion
in https://github.com/mozilla/application-services/issues/1466.
This PR removes the megazord substitution rules, meaning FirefoxReality
will get the full megazord by default. Fenix is making a corresponding
change over in https://github.com/mozilla-mobile/fenix/pull/8742.
=> Use the default appservices megazord, not the deprecated fenix megazord.

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/EngineProvider.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/GeckoViewFetchClient.kt, app/src/common/shared/org/mozilla/vrbrowser/geolocation/GeolocationClient.java, app/src/common/shared/org/mozilla/vrbrowser/geolocation/GeolocationWrapper.java, app/src/common/shared/org/mozilla/vrbrowser/search/SearchEngineWrapper.java, app/src/common/shared/org/mozilla/vrbrowser/search/suggestions/SuggestionsClient.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java, app/src/main/res/values/non_L10n.xml, versions.gradle
Fixes #1580 MozillaSpeechLibrary has now support for GeckoWebExecutor where available so we can safely remove all the http client dependencies that we were using from com.loopj.android and cz.mesebera.android.
This PR migrates all usage of those libraries to GWE and bumps the MozillaSpeechLibrary version to 1.0.11 which already implements support for GWE. mozilla/androidspeech#27
At some point the MLS stopped supporting requests without an API key, I saw it while debugging the GWE migration of the client. I've request an API to the MLS team. This will remain a draft until we get an API key for FxR.
=> Add support for GWE enabled MozillaSpeechLibrary

versions.gradle
- Includes a better WebGL crash fix
- Reload API
- Seems to fix #2918
=> Bump GV to 75.0.20200304084140

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayOptionsView.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h, app/src/main/cpp/DeviceDelegate.h, app/src/main/res/layout/options_display.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/options_values.xml, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/oculusvr/cpp/DeviceDelegateOculusVR.h, app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp, app/src/wavevr/cpp/DeviceDelegateWaveVR.h
=> Remote foveation level settings

app/src/common/shared/org/mozilla/vrbrowser/search/suggestions/SuggestionsProvider.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/utils/UrlUtils.java
=> Load IP based URIs instead of doing a google search

app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java, build.gradle, versions.gradle
Fixes #2924 Fixes an AC issue with FxA and the account state after rebooting.
This reverts https://github.com/MozillaReality/FirefoxReality/pull/2701
=> Fixes #2924 Fixes an AC issue with FxA and the account state after rebooting

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/EngineProvider.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DeveloperOptionsView.java, app/src/main/res/layout/options_developer.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/strings.xml
=> Permanently enable e10s

app/src/common/shared/org/mozilla/vrbrowser/ui/OffscreenDisplay.java, app/src/picovr/java/org/mozilla/vrbrowser/PlatformActivity.java
Related to #1080 
This PR fixes the issue with the headset button in Pico devices. Also re-enables the back button for quitting the app in Pico.
For some reason before the first back headset click the system `Window` has the `OffscreenPresentation` as the `Window.Callback` target. As we are not currently overriding `dispatchKeyEvent` in the `OffscreenPresentation`, that event gets lost. After that click it seems that the callback target is set to the `VRBBrowserActivity` and the following events are correctly forwarded.
Still unanswered why that first headset button press sets the `Activity` as the `Window.Callback`.
=> Fix for the Pico headset buttons

app/CMakeLists.txt, app/src/picovr/cpp/DeviceDelegatePicoVR.cpp, app/src/picovr/cpp/VRBrowserPico.cpp, app/src/picovr/cpp/VRBrowserPico.h, app/src/picovr/cpp/native-lib.cpp, app/src/picovr/java/org/mozilla/vrbrowser/PlatformActivity.java
=> Add support for haptic feedback on Pico controllers

app/src/picovr/cpp/DeviceDelegatePicoVR.cpp, app/src/picovr/cpp/DeviceDelegatePicoVR.h, app/src/picovr/cpp/native-lib.cpp, app/src/picovr/java/org/mozilla/vrbrowser/PlatformActivity.java
Adds support for the home long press to recenter event
=> Adds support for the home long press to recenter event

app/src/common/shared/org/mozilla/vrbrowser/browser/PermissionDelegate.java
Fixes #2935 Fix for getting invalid media requests for rejected permissions.
Related GV issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1621380
=> Fix for getting invalid media requests for rejected permissions

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
Fixes #2713 Always use low case for TLDs
=> Fixes #2713 Always use low case for TLDs

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TabsWidget.java, app/src/main/res/layout/tabs.xml
Fixes #2656 Fix tabs scrollbar refreshing issue
=> Fixes #2656 Fix tabs scrollbar refreshing issue

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Prevent duplicated callSurfaceChanged call when exiting immersive mode

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/input/MotionEventGenerator.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomKeyboardView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Widget.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/ControllerContainer.cpp, app/src/main/cpp/VRBrowser.cpp, app/src/main/cpp/VRBrowser.h, app/src/main/res/layout/autocompletion_bar.xml, app/src/main/res/layout/keyboard.xml
Closes #2645 Adds support for dual controller typing. 
Android doesn't support multiple device input in a clean way. The viewgroup clears the hovers from the other hovered items when a new child is hovered which causes a hover fight when more than one device is hovering elements from the same layout. When the view drawing is handled this is easier to workaround but in our case that would mean to rewrite quite a lot of code at this point. 
This implementation add support for dual hovering for the keyboard views (characters, symbols and numbers) and for the rest of the views in the keyboard widget (domains, languages and autocompletion) the first device entering them has preference.
=> Dual controller typing

app/src/common/shared/org/mozilla/vrbrowser/input/MotionEventGenerator.java
Fixes a crash where if one of the controllers has not been used and is
not part of the device table would cause a crash.
=> Only check device if it exists

app/src/picovr/cpp/DeviceDelegatePicoVR.cpp
=> Don't calculate reorientation matrix when recentering on G2

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
=> Recalculate the max window size when getting max size

app/src/common/shared/org/mozilla/vrbrowser/input/MotionEventGenerator.java
=> Prevent crash when only one controller has moved

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/utils/InternalPages.java
Crash report:
https://crash-stats.mozilla.com/report/index/edff4a20-a2d4-41a4-9dd5-773d10200319
I reproduced it sending invalid uris in intents
=> Fix crash if onLoadError uri parameter is null

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Due to https://bugzilla.mozilla.org/show_bug.cgi?id=1623712 need to
use GeckoSession.loadUri instead.
Fixes #3003
=> Work around GeckoSession.reload(GeckoSession.LOAD_FLAGS_BYPASS_CACHE) bug

app/src/common/shared/org/mozilla/vrbrowser/db/AppDatabase.java
There is a second version of the database in https://github.com/MozillaReality/FirefoxReality/pull/3019 and if QA or a user downgrades FxR currently it can crash because current master has not any migration fallback
=> Add fallback to destructive database migration.

app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChineseZhuyinKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/main/res/values/dimen.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/xml/keyboard_numeric.xml, app/src/main/res/xml/keyboard_qwerty_zhuyin.xml, app/src/main/res/xml/keyboard_symbols_zhuyin.xml
Fixes #2714.
This makes more sense based on iOS zh-TW keyboard layout.
However, I still can see we have couple of questions on `KeyboardWidget`. @keianhzo  Please take a look at this screen recording (https://drive.google.com/file/d/1m43TsivrTurHQnA19aKykkDbhLhyQ7gI/view?usp=sharing)
- I can't be easy to adjust its placement and resize the KeyboardLayout according to the parameters from `KeyboardInterface`. Although I spend an afternoon, I still feel the width of `keyboardContainer` or `keyboardLayout` is not what I expect. [0:00 - 0:23 sec in the video]
- Pinyin and Japanese keyboards didn't be placed at the the same position as others. We can see there is an offset between it and others. [0:23 - 0:41 sec in the video] I have checked their UI definitions are the same with …
=> Adjusting zh-tw keyboard layout.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java
Fixes #3015 FxA had issues in the past with the login page in desktop mode so we force a UA switch to mobile when login in FxA. That flow is broken in the latest GV and also we don't need for force the UA switch anymore.
=> Fixes #3015 Fix for the FxA login flow issue

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/main/cpp/VRBrowser.cpp, app/src/main/cpp/VRBrowser.h, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
I tried to test this using this code from a different app id:
```
ovrApplicationOptionsHandle options = ovr_ApplicationOptions_Create();
ovrID id = 2180252408763702;
ovr_ApplicationOptions_SetDeeplinkMessage(options, "https://www.mozilla.org");
ovr_Application_LaunchOtherApp(id, options);
```
But it  shows the Oculus Store page with a update button.
=> Add support for Oculus App Linking

app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/ExternalVR.cpp, app/src/main/cpp/ExternalVR.h
The `WasFirstPresentingFrame` check is fragile, it can cause a duplicated StartFrame call in some specific frame. 
Also fixes  #3043
=> Fix potential duplicated StartFrame() call

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
Fixes #3050.
The root cause is `mShiftDisabledIcon` hasn't been loaded before calling `disableShift().` [1]
[1] https://github.com/MozillaReality/FirefoxReality/blob/09d76aee488a531fdab6370b63a14f59eb18b8de/app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java#L863
=> Shift key icons need to be loaded before setup DefaultKeyboard.

app/metrics.yaml, app/pings.yaml, docs/metrics.md
Not ready for merge yet.
Requires an upgrade of android-components (for the updated sdk_generator script).
We're landing changes in the pipeline as well first.
There's no data loss. Data will still go to the same table for both `session_end` and `session-end` pings.
I'll come back here and put it out of Draft mode when we're ready to land it.
=> Rename ping to avoid underscores

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #3052 We were getting duplicated fullscreen change events because we were handling the fullscreen flow in a quite convoluted way where both the navigation bar and the window updated the viewmodel state. I've simplified it and make the window the owner of that property update
=> Fixes #3052 Avoid double fullscreen call

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Improves Room Scale support for WebXR. Related Gecko PR: https://bugzilla.mozilla.org/show_bug.cgi?id=1626053
=> Calculate standingMatrix using local floor relative pose transform

app/src/picovr/cpp/DeviceDelegatePicoVR.cpp, app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
Improve the matrix used to calculate local-floor coordinates in WebXR. 
Oculus implementation already landed in #3078
Fixes #1814
=> Improve standing transform on Pico and Wave

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Fixes #3110 Fixes #3112 Do not handle fullscreen updates if Window is not attached yet
=> Fixes #3110 Fixes #3112 Do not handle fullscreen updates if Window is not attached yet

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/oculusvr/cpp/OculusVRLayers.cpp, app/src/oculusvr/cpp/OculusVRLayers.h
=> Fix halo artifact on Oculus

app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java
Fixes #3129 
Based on the recent Glean updates ( https://github.com/mozilla/glean/blob/master/CHANGELOG.md#v2300-2020-01-07).
GleanMetricsService.start() need to be called after Glean system initialization.
=> Call Glean initialize prior to set startup metrtics.

app/src/common/shared/org/mozilla/vrbrowser/utils/UrlUtils.java
Fixes https://crash-stats.mozilla.com/report/index/76911fdf-032a-4084-9948-d61250200408
=> Convert NonNull to Nullable in UrlUtils to fix crash

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes compositor not resumed after exiting WebVR. STR:
- Open https://webvr.info/samples/03-vr-presentation.html
- Enter WebVR
- Pause and resume the application using the Oculus menu
- Sometimes the compositor is still paused
=> Ensure that compositor is resumed after onResume

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/main/cpp/ExternalVR.cpp
I found a superfluous ResumeCompositor call when starting the app. Also mWindows `enterImmersiveMode` and `exitImmersiveMode` calls are called in the render thread instead of UI. They can internally call some Gecko functions
=> Fix thread of Windows exit/enter immersive calls. Avoid superfluos call.

app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java
Reverts MozillaReality/FirefoxReality#3130
This is not a right fix, we still need to update our Glean framework.
=> Revert "Call Glean initialize prior to set startup metrtics."

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/oculusvr/cpp/OculusVRLayers.cpp, app/src/oculusvr/cpp/OculusVRLayers.h
=> Fix jniEnv not set when layer is resized after the surface has been moved

app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/Cylinder.cpp, app/src/main/cpp/Widget.cpp, app/src/main/cpp/Widget.h
When you are press and drag outside the widget bounds the input stops. This adds support for dragging outside the widget bounds. I think it is a more natural behavior for the input.
I started this branch a while ago so I guess it's a good moment to share and check if this is something that we like.
=> Support for dragging outside the widget bounds

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/LanguageOptionsView.java
1. updated getLanguageIndex function so that for text without '(' or '[' function returns full length of text instead of lenth -1 so that the getSpannedLanguageText generates the full text with bold
=> Show last letters of the selected language. Fixes #2945

app/build.gradle
This is supposed to reduce Gecko start time.
=> Prevent omni.ja compression in APK

app/src/main/cpp/BrowserWorld.cpp
Fixes #2990
Fixes #3147
Note: This only fixes the crash from #3147. The issue of the resize
not being saved is still issue #2862.
=> Ensure only focused controller is used for resize and moving

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
Fixes #3157
When GeckoView started short cutting onLoadRequest, the number of
Navigation Listeners would be larger when the GeckoRequest was finally
processed so the GeckoResult would never get completed and the load
would never start.
=> Insure onLoadRequest only waits for correct number of listeners.

app/src/main/res/values/strings.xml
=> Fix open_downloads_tooltip to say "Open Downloads"

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UISurfaceTextureRenderer.java
=> Ensure UI Hardware rending is only disabled on the tray and spinner.

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/noapi/java/org/mozilla/vrbrowser/PlatformActivity.java, app/src/oculusvr/java/org/mozilla/vrbrowser/PlatformActivity.java, app/src/picovr/java/org/mozilla/vrbrowser/PlatformActivity.java, app/src/wavevr/java/org/mozilla/vrbrowser/PlatformActivity.java
=> Prevent Gecko from consuming Pico confirm key

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/oculusvrArmDebug/AndroidManifest.xml, app/src/oculusvrArmRelease/AndroidManifest.xml
From the docs:
To enable overlay for testing purposes, enter the following commands in a terminal:
Go to Setting -> See All -> Experiments and enable New Universal Menu
adb shell setprop debug.oculus.dbg_enable_overlay 1
adb shell am force-stop com.oculus.vrshell
After entering these commands, if an app has overlay support enabled in its app manifest, pressing the Oculus button from inside the app will cause the Universal Menu to be displayed as an overlay.
To disable overlay support, enter the following commands:
adb shell setprop debug.oculus.dbg_enable_overlay 0
adb shell am force-stop com.oculus.vrshell
=> Add support for Oculus Focus Awareness

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Fixes #3176 Fixes #3116 Show/Hide the permission bubble in the correct position
=> Fixes #3176 Fixes #3116 Show/Hide the permission bubble in the correct position

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
When switching between multi-window regular an private modes, the top and title bars are still visible and cause and annoying glitch.
=> Fixes glitches when swhitching between regular and private modes

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
Fixes #3154
Previously if the content process was killed or crashed while the
application was paused, the windows would still be in fullscreen
and/or immersive VR video mode while the recreated GeckoSession
would not. This partially fixes the issue by ensuring fullscreen
and VR immersive video is exited on pause so the windows do not
get into a bad state if the crash/kills while the application is
backgrounded.
=> Ensure fullscreen and immersive VR video is exited on pause

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/VectorClippedEventDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/main/res/layout/navigation_bar_fullscreen.xml
Fixes #2861 Flushing the back handlers on Pause was closing the library panels before saving the state.
https://github.com/MozillaReality/FirefoxReality/blob/277000d756884fbfc68b4fc307f219dd7946c79c/app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java#L440-L442
Instead of that we just exit the full-screen or immersive mode in onPause.
The related issue is prior to this code so shouldn't be the cause but I couldn't really reproduce it after fixing it so I might have been fixed by other patch.
=> Fixes #2861 Fix panels being closed on pause

app/src/common/shared/org/mozilla/vrbrowser/downloads/Download.java, app/src/common/shared/org/mozilla/vrbrowser/downloads/DownloadsManager.java, app/src/main/AndroidManifest.xml, app/src/main/res/values/strings.xml
- Adds information about the download status in the progress field. Prior to this we weren't properly showing the download status , just a blank entry with 0.00kb downloaded bytes. Now when the download is not yet in progress or finished the progress should show the status.
- Allow HTTP downloads in Android > 9. Android 9 Download Manager doesn't handle downloads using HTTP using explicitly set.
=> Download improvements

app/src/common/shared/org/mozilla/vrbrowser/browser/Services.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #2933 Avoid saving FXA login sessions.
We weren't handling the `finishAuthenticationAsync` result where FxA notifies of this error. At that point the only thing that we can do is to deny the request load (if we allow it shows the success page) and notify the user. It doesn't look good to show an alert and leave the user with a loading login page so as a workaround we just avoid restoring FxA oauth flow sessions.
Ideally we should get a redirect to an error page but we get a redirect to the success page even in the case where `finishAuthenticationAsync` fails, I've notified the FxA team about that.
=> Fixes #2933 Avoid saving FXA login sessions

app/src/main/cpp/BrowserWorld.cpp
=> Reset interstitial state when exiting WebXR using the back button

app/src/common/shared/org/mozilla/vrbrowser/browser/Media.java, app/src/common/shared/org/mozilla/vrbrowser/browser/VideoAvailabilityListener.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #2545 Fixes #2559 This PR improves the handling of multiple media elements state and address the issues with the title bar media controls in pages with multiple media elements.. 
We were currently only listening for events on the latest added media element. This PR adds support for listening on events from all the currently existing media elements and sending title bar media controls actions to the latest focused element.
STRs:
- Open a page with multiple media elements (ie. https://twitter.com/AFCAjax)
- Play the first media element
- Add a new window
- See the initial window title bar
Result: The title bar doesn't show the media controls
Expected: The title bar should show the media controls and they should action the active media element.
With this PR on pages with multiple media …
=> Fixes #2545 Multiple media elements handling

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
=> Ensure all windows are restored even if an FxA session gets filtered out

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionUtils.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/Controller.cpp, app/src/main/cpp/Controller.h, app/src/main/cpp/ControllerContainer.cpp, app/src/main/cpp/ControllerContainer.h, app/src/main/cpp/ControllerDelegate.h, app/src/main/cpp/Device.h, app/src/main/cpp/ExternalVR.cpp, app/src/main/cpp/ExternalVR.h, app/src/main/cpp/moz_external_vr.h, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/picovr/cpp/DeviceDelegatePicoVR.cpp, app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp, versions.gradle
Fixes #2237 and #2095.
I have checked it works properly in my local but I am still waiting for WebXRSession and WebXRInputSource implementation from GeckoView. We might can merge it first? Or we need to wait for WebXR works in GV?
I will be away for a couple of weeks. If there are some WebXR progress from GV, maybe someone from our team can continue to work on this.
=> WebXR gamepad module support.

app/src/main/cpp/BrowserWorld.cpp
Fixes #3202 Make sure the interstitial is hidden when the immersive session is exited.
STRs:
- Open the Spiderman game
- Enter the VR session
- Click the home button
- Resume the app
- Enter the VR session
=> Fixes #3202 Hide interstitial when immersive mode exits

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/ContextMenuWidget.java, app/src/common/shared/org/mozilla/vrbrowser/utils/UrlUtils.java
Fixes #3168 
- Don't show the context menu for blob elements (ie. Youtube  video)
- In case there is no linkUri, show srcUri as title
- Hide linkUri related menu items (open in new window, open in tab, download link) in case is null or empty
=> Fixes #3168 Context menu fixes

app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/WindowViewModel.java, app/src/common/shared/org/mozilla/vrbrowser/utils/UrlUtils.java, app/src/main/res/layout/navigation_url.xml
Fixes #3169  This PR refactors the URL buttons (etp, popups, webxr, drm) and icons (loading, ssl) visibility rules to the view model as it has grown quite a lot and makes the XML very crowded and hard to read.
Also adds a number of fixes:
- Hides the ETP icon for file URIs
- Hides the URL buttons if the URL bar is focused
- Shows the file name in the title bar for file URIs (instead of just file://)
=> Fixes #3169 Hide Tracking icon for file URIs

app/src/common/shared/org/mozilla/vrbrowser/browser/content/TrackingProtectionStore.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionSettings.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/WindowViewModel.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/main/res/layout/navigation_url.xml
Fixes #3064 Fixes #3062 Hide ETP button in PB and force tracking protection for Private Sessions based on https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop?as=u&utm_source=inproduct:
> Tracking content in Private Windows only. These trackers are hidden in ads, videos, and other in-page content. Blocking them can cause some websites to break. To add this protection in all windows, visit your privacy preferences and select Strict or Custom as explained below.
=> Force tracking protection for Private Sessions

app/src/main/res/layout/tray.xml, app/src/main/res/values/non_L10n.xml
Fixes the build error:
```
line 1:87 token recognition error at: ';'
line 1:88 token recognition error at: '''
```
=> Replace ellipisis unicode for string

app/src/main/cpp/ControllerContainer.cpp
We need to clear the last immersive action frame ids to be 0 if we are away from the immersive mode.
=> Clear select and squeeze frame ids when it is not in the immersive mode.

app/src/common/shared/org/mozilla/vrbrowser/browser/PermissionDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/browser/content/TrackingProtectionStore.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/db/DataRepository.java, app/src/common/shared/org/mozilla/vrbrowser/db/SitePermissionDao.java, app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/SitePermissionViewModel.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SitePermissionsOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/TrackingPermissionsOptionsView.java
Fixes #3229 Avoid restoring/clearing exceptions list when inserting
=> Fixes #3229 Avoid restoring/clearing exceptions list when inserting

app/src/common/shared/org/mozilla/vrbrowser/ui/views/TabView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TabsWidget.java
Fixes #3228 Send only http/https tabs
=> Fixes #3228 Send only http/https tabs

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/downloads/DownloadsManager.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/DownloadsAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/library/DownloadsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/CrashDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/PermissionWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/PromptDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/RestartDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SignOutDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/WhatsNewWidget.java, app/src/main/res/layout/tray.xml
Fixes #3241 Fixes #3240 Download fixes
- Avoiding unnecessary cursor loop. Should fix the performance issue
- Fixes a typo in the tray badge when downloads number was > 100
- Report all pending downloads, we were only reporting the running ones
- Fixes deleting downloaded files when the checkbox is ticked
- Avoid showing notifications in the tray if it's not visible
- Shows an empty downloads list faster when clearing all the downloads
=> Fixes #3241 Fixes #3240 Download fixes

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WebXRInterstitialWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java
Disable webxr_interstitial and whats_new widgets as below:
`adb shell am start -n org.mozilla.vrbrowser/org.mozilla.vrbrowser.VRBrowserActivity --ez hide_whats_new true`
`adb shell am start -n org.mozilla.vrbrowser/org.mozilla.vrbrowser.VRBrowserActivity --ez hide_webxr_interstitial true`
=> Add hide_webxr_interstitial and hide_whats_new ADB commands.

app/src/common/shared/org/mozilla/vrbrowser/browser/PromptDelegate.java
Fixes  #3250
I checked we match the Firefox Desktop behavior:
- Open http://popuptest.com/popuptest2.html
- Navigate to other place. Popup website triggers another popup on page leave.
- The popup is rejected and the notification/icon are not visible in the awesome bar
=> Do not display popup icons when a popup is launched on page leave

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionUtils.java, app/src/main/res/values/non_L10n.xml, versions.gradle
Includes the antialias fix on WebGL 2
=> Bump GV to v77.0.20200428100141

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #3257 Fixes #3256 We are setting the session listeners after activating the sessions. That means that in some cases (like restoring when activating the session) the listeners are not ready. This cause issues like permissions (or anything that we do in the session listeners) not being correctly checked for restored sessions.
=> Fixes #3257 Fixes #3256 Make sure session listeners are set when first LoadRequest is called

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Fixes #3268 Do not exit fullscreen if it was autoentered.  This check got lost here: 9c338d8ab037dc6278a1ea38df9a45c94b54e7aa
=> Fixes #3268 Do not exit fullscreen if it was autoentered

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #3248.
I hope using `postValue()` is right instead of `setValue()`
=> Clear the URL bar if this file type is unsupported.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Speculative fix for https://crash-stats.mozilla.org/report/index/6b13ce7f-7f54-48f3-acf4-ebb540200428
=> Ensure mUri is not null in Window save

app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/WindowViewModel.java
Fixes #3281 Fixes #3282 We were excluding protocols individually (like file://) but we really just want to show the URL bar buttons for http/https protocols. This PR also hides the URL icon visibility when in Library mode.
=> Fixes #3281 Fixes #3282 Only show URL buttons for http/https uris

app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/SitePermissionAdapter.java
Fixes #3263 Provide an item id for the site permissions adapter
=> Fixes #3263 Provide an item id for the site permissions adapter

app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/WindowViewModel.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/main/res/layout/navigation_url.xml
Fixes #3291 We were updating based on the url update and that happens onLocationChange but the permission state change is received after that so the URL bar icons visibility property was not being updated after that. This updates the URL bar icons visibility when the permissions change.
Also this PR updates the URL bar url when a url navigated to, otherwise we were having some time until onLocationChange happened when the URL bar was showing the entered characters.
=> Fixes #3291 Update URL bar icons visibility based on permissions state

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/main/res/values/strings.xml
=> Fixes #3266 DRM string update

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #3236 Fixes:
- Tray animations to be run when focusing another window
- Glitches when hovering/clicking on the tray icons
=> Fixes #3236 Fixes tray icons animation issues

app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/WindowViewModel.java, app/src/main/res/layout/title_bar.xml
Fixes #3290 Ensure title bar text remains the same color when pressed. Also use setValue for the active window model property to force a quicker switch of the title bar visibility, otherwise when activating another widow there is a split second when both the navigation and the title bar overlaps, specially in Pico devices.
=> Fixes #3290 Pico title bar fixes

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MediaControlsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Fixes #2660 Set the correct fullscreen controls and menus curved state. Additionally it fixes an issue with the projection/brightness menus dismiss when clicked in the widget.
=> Fixes #2660 Set the correct fullscreen controls and menus curved state

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, versions.gradle
We need to adjust it as we did for Quest and Focus Plus. Luckily, for Focus controllers, we don't need it.
It needs to wait for [Bug 1634808](https://bugzilla.mozilla.org/show_bug.cgi?id=1634808) be merged to GV first.
=> Adjust Oculus Go controller transform based on WebXR input profile.

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/library/DownloadsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/library/SortingContextMenuWidget.java
Fixes #3321 Fixes #3320 Fixes #3317 Fixes the issues with sorting when there are items with the same size and name. Also fixes sorting restoration upon restart  and scrolling when sorting is changed.
=> Fixes #3321 Fixes #3320 Fixes #3317 Downloads list improvements

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
=> Call GeckoSession.setActive(true) even if the session is already active

app/src/common/shared/org/mozilla/vrbrowser/db/AppDatabase.java, app/src/common/shared/org/mozilla/vrbrowser/db/SitePermission.java
=> Fix v2 to v3 Database migration

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
STR:
1) Visit [https://yts.mx/movie/theeb-2014](https://yts.mx/movie/theeb-2014)
2) Click on page to spawn ad
3) Close ad with tab view and select https://yts.mx/movie/theeb-2014 tab
4) Reload page and click on page to spawn new add
Actual:
Spawned ad tab fails to load
Expected:
Spawned ad tab loads
Cause:
The Window.java `SessionChangeListener` was getting added multiple times so when a new tab was added it got called twice and on the second call, it was disabling the new session since it had already been set.
=> Prevent listeners from getting added more than once

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
It seems that calling setActiva(false) twice causes some issues. When we enter immersive mode we call setActive(false) on the non focused windows and we call surfaceDestroyed. If we show the Oculus menu later, setActive(false) is called again
Fixes #3375
=> Prevent duplicated setActive(false) calls

app/build.gradle, app/src/common/shared/org/mozilla/vrbrowser/browser/Accounts.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/BookmarksStore.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/Places.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/Services.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/geolocation/GeolocationWrapper.kt, app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java, build.gradle, docs/metrics.md, versions.gradle
Fixes #2697 
This modifies the build to use the Glean Gradle plugin that ships with android-components, rather than directly from Glean.
This means that updating android-components should be much smoother going forward.  Right now, you have to make sure that the version of Glean forUnitTests is the correct one for a particular version of android-components.  With this change, only the version of android-components needs to be updated, and the correct version of other Glean dependencies will be determined automatically.
I'm submitting this as a draft because it does require upgrading android-components to get this feature, and there seems to be plenty of other unrelated breakage that this upgrade causes.
When you are ready to devote effort to updating android-components, this PR should be …
=> Update to new usage of Glean Gradle plugin

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/main/cpp/ExternalVR.cpp, app/src/main/cpp/VRBrowser.cpp, app/src/main/cpp/VRBrowser.h
=> Prevent deadlock when exiting WebXR/WebVR

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NotificationManager.java
I've come across a NullPointerException when showing multiple concurrent notifications in the Tray bar during testing.
=> Null check for the notification parent view

app/src/common/shared/org/mozilla/vrbrowser/browser/PermissionDelegate.java
Fixes #3351 Always allow muted autoplay
=> Fixes #3351 Always allow muted autoplay

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/EngineProvider.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/main/assets/web_extensions/webcompat_vimeo/manifest.json, app/src/main/assets/web_extensions/webcompat_youtube/manifest.json
Fixes #2883 Web extensions are not being loaded for restored sessions after a restart.
STRs:
- Open a youtube video
- Change the MSAA setting and restart
- See the video URL (it has `app=desktop` appended)
- Change the MSAA setting and restart again
**Actual result**: The loaded url after the first restart has `app=desktop` appended, the webextension hasn't been applied, after the second restart Youtube has an incorrect layout.
**Expected result**: The correct Youtube layout should be used for restored sessions.
This would happen with any extension.
=> Fixes #2883 Ensure webexts are loaded when restoring sessions

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
We are leaking that swapChain on pause/resume if the app is not exited
=> Do not recreate clearColorSwapChain if it already exists

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/main/res/values/strings.xml
Check for available apps when opening a file otherwise we just show that the file is unsupported. It's not easy to test because of the lack of utilities in most platforms at the moment. It can be tested with:
- 3GP, TIFF in Oculus
- 3GP in Pico
=> Check for available apps when opening a file

.taskcluster.yml
I heard from @bluemarvin that when a taskcluster task is re-triggered, the status on github doesn't change. That can be changed if a newer checks API is used. This PR does exactly that
~(It is draft for now because I need to see which scopes are missing)~
ok, it actually seems to work!
As you can see, using a different taskcluster API also changes UX here a bit. You will notice there's a Checks tab up top - that's where the "Details" link will be pointing at now. This can always be changed back.
=> Use checks API in taskcluster

app/src/common/shared/org/mozilla/vrbrowser/utils/LocaleUtils.java, app/src/main/res/values/strings.xml
Fixes #3368 Add missing supported languages
=> Fixes #3368 Add missing supported languages

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/main/assets/web_extensions/webcompat_youtube/main.js
Fixes #2611 Fixes #2947 Fix Youtube queue context menu and forward issues.
=> Fixes #2611 Fixes # 2947 Youtube player fixes

app/src/oculusvr/res/layout/webxr_interstitial_controller.xml
The arrow currently points to the system button instead of the back button that we exactly wanna users to use. We should do this change.
=> Adjust Oculus Go WebXR exit arrow to the back button instead of the system button.

app/build.gradle, app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java, app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java, app/src/common/shared/org/mozilla/vrbrowser/utils/DeviceType.java, tools/taskcluster/build_targets.py
Pico now has a ROM baked version of FxR. We need to provide a suffix so QA can test staging build without colliding with the production appId.
=> Picovr suffix

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Closes #3277 Refactor of the setSession code to set the previous session active state and setup the listeners.
=> Closes #3277 Improved setSession code

app/src/main/assets/web_extensions/webcompat_youtube/main.js
Fixes #2919 Fixes #2947 Fixes #2673 Hide YouTube overlays in immersive
=> Fixes #2919 Fixes #2673 Fixes #2641 Hide Youtube fixes

app/src/main/cpp/Widget.cpp
=> Fix crash in Widget::TestControllerIntersection()

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/ContextMenuWidget.java, app/src/main/res/values/strings.xml
Until now we only supported opening links in new windows/tabs. This PR adds support for also opening elements. ie. you want to open an image element (without a link) in a new window/tab
=> Support for opening elements in new tabs

README.md, app/CMakeLists.txt, app/build.gradle, app/src/main/cpp/SplashAnimation.cpp, app/src/main/cpp/native-lib.cpp, app/src/openxr/cpp/DeviceDelegateOpenXR.cpp, app/src/openxr/cpp/DeviceDelegateOpenXR.h, app/src/openxr/cpp/OpenXRExtensions.cpp, app/src/openxr/cpp/OpenXRExtensions.h, app/src/openxr/cpp/OpenXRHelpers.h, app/src/openxr/cpp/OpenXRInput.cpp, app/src/openxr/cpp/OpenXRInput.h, app/src/openxr/cpp/OpenXRLayers.cpp, app/src/openxr/cpp/OpenXRLayers.h, app/src/openxr/cpp/OpenXRSwapChain.cpp, app/src/openxr/cpp/OpenXRSwapChain.h
Known issues (already reported to Oculus):
- Washed out colors: Seems related to having SRGB by default or not applying VRAPI_FRAME_LAYER_FLAG_INHIBIT_SRGB_FRAMEBUFFER
- Quad and Cube layers work correctly when using FBO swapchains. But when redenring compositor layers with AndroiSurface based swapChain I get a `XR_ERROR_LAYER_INVALID` error when calling xrEndFrame. AndroidSurface layers are disabled until the issue is fixed.
- Reusing the instances of input XrActions with different subactionPaths for each controller on the Quest doesn't work well: the right controller reported the same pose and buttons as the left controller. I found a workaround. It works well creating different instance XrActions for each subactionPath/Controller. I'll switch back to single XrAction instances once the …
=> OpenXR implementation

app/metrics.yaml, app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java, app/src/test/java/org/mozilla/vrbrowser/GleanMetricsServiceTest.kt, docs/metrics.md
Fixes #3212 and #3324.
In #3212, our labels should be converted to lower case, and add legacy client id in deletion request ping for #3324.
=> Resolve label metrics are _other_ and add legacy client id

app/src/main/res/values/strings.xml
Fixes https://github.com/mozilla-l10n/android-l10n/issues/99
=> Fix for l10n popup strings

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #3431
This patch changes the behavior of launching or opening a URI
from an intent. Previously the URI would be opened in the focuses window.
With this patch it matches Fenix and desktop and creates a new tab in the
focused window.
=> Wait to load URI from intent until after session restore.

app/src/main/assets/web_extensions/webcompat_youtube/main.js
Fixes https://github.com/MozillaReality/FirefoxReality/issues/2946#issuecomment-638261659 
Quality was being overridden as part of the player fixes when the player settings were clicked.
=> Do not override quality on click

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/EngineProvider.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DeveloperOptionsView.java, app/src/main/res/layout/options_developer.xml, app/src/main/res/values/strings.xml
Due to the way the settings work in gecko, having two switches
doesn't make sense. Having one switch to enable/disable Gecko
logging to logcat makes it easier to manage.
=> Merge console and debug logging settings

app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java
Fixes #3490 and #3417
It is happened when trying to find a word from the code book for replacing a substring in composing text. But, sometimes we can't. (like `n ,`) So, in that case, we can just return an empty string for composing.
=> Return an empty string when no result in zh-CN codebook

app/metrics.yaml, docs/metrics.md
**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**
1. **What questions will you answer with this data?**
* Adding a UUID uniquely identifying the legacy telemetry client id.
This is used for supporting legacy telemetry in the `deletion-request` ping.
2. **Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?**
*  Helping sunset the legacy telemetry.
3. **What alternative methods did you consider to answer these questions? Why were they not sufficient?**
* N/A. this is a new ping
4. **Can current instrumentation answer these questions?**
* N/A, this is a new ping for supporting legacy …
=> Legacy telemetry data review.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java
Fixes #3491 Handle voice state when pausing/resuming the activity.
=> Fixes #3491 Handle voice state when pausing/resuming the activity.

app/src/common/shared/org/mozilla/vrbrowser/browser/PromptDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/main/res/values/strings.xml
Fixes broken navigation after entering/exiting BabylonJS WebXR in their playground app #3472
=> Implement before unload prompt

app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChineseZhuyinKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
Fixes #3506.
When typing symbols, we can just use `AUTO_COMPOSE` mode.
I was trying to make Zh-CN and JPN keyboard have the same behavior when typing symbols, using `AUTO_COMPOSE` instead of `SHOW_CANDIDATES`. But, JPN keyboard will show `．` when inserting `/`。The only way possible is fixing their code book to avoid it, but it is not worth to do. IMO, We can still rely on their code book to feed our data, iOS JPN keyboard uses the same behavior either.
=> Avoid showing Zh-TW and Zh-CN keyboard candidate view when typing symbols.

app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java
Fixes #3526.
I didn't realize some character's code is "" from our Zh-CN code book.
=> Checking Zh-CN code length before looking for a blacklash symbol.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetPlacement.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/WidgetPlacement.cpp, app/src/main/cpp/WidgetPlacement.h
Fixes #2442
- Fixed a bug, the input controller position shouldn't affect depth sorting
- The original 2442 issue doesn't seem easy to fix without affecting other use cases. It's not possible to support a real depth buffer so I added a priority field. Unity/Unreal also use the optional priority field (https://developer.oculus.com/documentation/unity/unity-ovroverlay/)
=> Add layer priority sorting. Make pointer not affect widget sorting.

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java
Fixes #3528 Fix for the what's configuration change issue
=> Fixes #3528 Fix for the what's configuration change issue

app/src/common/shared/org/mozilla/vrbrowser/ui/views/UIButton.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MediaControlsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/main/res/layout/media_controls.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/strings.xml
Closes #3269 Adds tooltips to the video controls. Also adds support for curved tooltips, it seems it was lost in some rebase.
=> Closes #3269 Adds Tooltips to the video controls

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
=> Only load home page if session uri is blank on new intent.

app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/BaseKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChineseZhuyinKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/KeyboardInterface.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ThaiKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/main/res/layout/keyboard.xml, app/src/main/res/layout/navigation_url.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/keyboard_qwerty_thai.xml, app/src/main/res/xml/keyboard_qwerty_thai_cap.xml, app/src/main/res/xml/keyboard_symbols_swedish.xml, app/src/main/res/xml/keyboard_symbols_thai.xml
Fixes #3487.
I notice Android and iOS have different implementation when dealing vowels. Android can't display that little circle under a vowel like  'ึ`.
Besides, Android app will stack the coming vowels even though we can't see the stacked vowels in Android app (I believe they are cut-off), they indeed exist if we backspace them. We also can produce it when using Android Chrome and type a character with multiple vowels in the search bar.
So, I am looking for a way to stop showing the vowels that are out of vertical boundary. It might be an attribute in our EditText. @keianhzo do you have idea about this?
=> Support Thai keyboard.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #3495 Catch all exceptions when starting an external activity
=> Fixes #3495 Catch all exceptions when starting an external activity

app/build.gradle, versions.gradle
Fixes #3369
I could add a flavor or user property to add more dynamic options to select the branch if we consider it's worth it
=> Add support for GV beta and release builds

app/src/common/shared/org/mozilla/vrbrowser/browser/HistoryStore.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #3604 Exclude FxA login urls from history
=> Fixes #3604 Exclude FxA login urls from history

versions.gradle
=> Bump GV nightly to v80.0.20200703094420

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java
This caused a crash mostly in the emulator when restoring sessions and only in DEBUG mode (release builds are not affected):
STRs:
- Open a few sessions/windows
- Exist the app (persist sessions)
- Kill the app
- Reopen
Result: Crash
Expected: Sessions should be restored
=> Fix CocurrentlModificationException in debug mode

app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/BaseKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/KeyboardInterface.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/main/res/xml/keyboard_qwerty_thai.xml, app/src/main/res/xml/keyboard_symbols_thai.xml
=> Fixes Thai alphabetic cap keyboard switch

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
Fixes #3620 Fixes #3634 We were setting the Session State and Uri to null in the `restore` method just for handling default page loading in `shouldLoadDefaultPage` but now in `restore` we consider a null Session State as a new session creation and we notify to the `BrowserStore` in hat case so we were trying to add a new session to the `BrowserStore` but the session hasn't been removed from the store which triggered the `BrowserStore` crash as it requires unique session ids.
=> Fixes #3620 Fixes #3634 Fix private session restore crash

app/src/common/shared/org/mozilla/vrbrowser/browser/Accounts.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/views/library/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/library/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/WhatsNewWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java
Fixes #3605 Link FxA login flow to the originating session
=> Fixes #3605 Link FxA login flow to the originating session

app/src/main/res/xml/keyboard_symbols_thai.xml
Fixes #3627.
Correct the semicolon symbol according to the [design document](https://trello-attachments.s3.amazonaws.com/5a260c5d480978f87ffad6aa/5e8b6fea4b16537342cd8ab1/a17286b6b2aec8b4c3a5089dc6479291/UIS-92_Thai_Keyboard_001.pdf).
=> Replace Thai quotation with semicolon.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MediaControlsWidget.java
Fixes #3591 Support for media controls live language update
=> Fixes #3591 Support for media controls live language update

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
Fixes #3637 Null check the alphabetic caps Keyboard when entering a character. 
Also allow the alphabetic caps keyboard to be dismissed when a key is entered, I've checked other keyboards and it seems to work the same way as the rest.
=> Fixes #3637 Null check the alphabetic Caps Keyboard when switching shift

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserApplication.java, app/src/common/shared/org/mozilla/vrbrowser/utils/SystemUtils.java, app/src/test/java/org/mozilla/vrbrowser/EnvironmentsTest.kt, app/src/test/java/org/mozilla/vrbrowser/GleanMetricsServiceTest.kt, app/src/test/java/org/mozilla/vrbrowser/TestApplication.kt
Fixes #3643 The Telemetry service needs to get initialized in the Application onCreate as the service can be called when the app is not running and that only calls the Application onCreate, otherwise this crash happens.
I had to add a custom TestApplication for testing as the Unit testing initialization doesn't seems to provide a different process for the crash service as defined in the manifest and the GeckoRuntime crashes with:
`java.lang.IllegalArgumentException: Crash handler service must run in a separate process`
Also for some reason the Application onCreate is called from a different process the first time the app is launched and the GeckoRuntime is not correctly initialized and we don't get any content paints. I've added the same check as Fenix does to make sure we are running in …
=> Fixes #3643 Telemetry crash fix

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
=> Correct the keyboard layout when showing from the focus view.

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserApplication.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/EngineProvider.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionUtils.java
We have had different regressions related to not calling vrPrefsWorkAround before runtime. I'm adding a error in that case to prevent that from happenning again
=> Assert that vrPrefsWorkAround method is called before creating the Gecko Runtime

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserApplication.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/EngineProvider.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/GeckoViewFetchClient.kt
Fixes #3652
GeckoWebExecutor creation is creating the Gecko runtime and vrPrefsWorkaround must be executed before creating the runtime. Note that vrPrefsWorkaround uses the activity intent to check some extra banchmarking/testing params so we can't run that on the VRApplicationClass (We can't get the activity intent on that stage AFAIK)
=> Lazily initialize GeckoWebExecutor

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TabsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #3658 FxA login signin fix. The first time you login after install the FxA login flow does something that prevents GV from correctly replacing the History entry when loading the success page. Works good in the subsequent logins but obviously the first one is the most important. We have moved back to using new tabs instead of loadUri. I have checked that
=> Fixes #3658 FxA login signin fix

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java
Fixes #3671
Make sure to test the following scenarios:
- New Window creation: from either Tray/Context menu
- New Tab creation: from either the Tabs panel/Context menu
- New Background tab creation (Long press link and open tab from the Context menu)
- Session restore: quit and reopen app with active&suspended sessions (Suspended sessions won't be added to the Browser Store until first activated)
- Session suspension/restore: open 3+ windows in regular model, switch to private, open another 3+ windows and go back and forth between regular/private
- Session recreation: Open several active/suspeded sessions, got to Settings->Privacy and clear cache/data
**Logcat** filtering by `SessionStore` will show the `BrowserStore`-`SessionStore` sync state including the alive vs suspended totals. …
=> Fixes #3671 BrowserState-SessionStore sync

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java
Fixes #3681
It's already called in createSession
=> Do not call addSession in SessionStore.onStackSession()

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
We have to unlink when closing before removing the session from the BrowserStore.
=> Fix the unlinking/removing sessions order 

app/src/wavevr/cpp/native-lib.cpp
Fixes #3688
It turns out that WVR_RenderInit() is a blocking call that waits for the activity to be active/resumed to complete the internal work. The function is slow to react so Gecko is initialized earlier and fails all the attempts to detect VR runtimes, because the external shmem is null. We need to process InitializeJava earlier instead of waiting for the slow WVR_RenderInit to complete.
100% reproducible STR:
- Take off the HMD until the screen turns off
- Launch FxR from Android Studio
- Put the HMD AFTER the application has started
=> Fix RegisterExternalContext() life cycle issues on WaveVR

app/build.gradle, app/src/common/shared/org/mozilla/vrbrowser/browser/Services.kt, versions.gradle
Originally the `Service` instance was created in `Application` `onCreate` which happens before any other component has been created so the `WorkManager` was not initialized and that’s why we needed to initialize it during the `Service` instantiation, just to make sure that it was always ready.
We have recently done a code refactor and now the `Service` instance is create in `Activity` `onCreate` so this is not an issue anymore, as the component has already had a chance and should be initialized.
=> Remove superfluous WorkManager initialization

app/src/common/shared/org/mozilla/vrbrowser/downloads/DownloadsManager.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/EnvironmentOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/utils/EnvironmentsManager.java, app/src/main/res/values/strings.xml
Fixes #3693 Request permission to download envs in the external storage
=> Fixes #3693 Request permission to download envs in the external storage

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java
Partially fixes #3678
There is still some possibility that WebXR enters immersive after clicking private mode due to promise or external VR ipc delays. Currently we don't have a way to detect which session starts WebXR mode. It would require some Gecko patch. Ideally we should exit WebXR mode if the session is set to inactive. WebXR currently works even if the session is set to inactive state (but media get's paused, that's why it can be reproduced in DelightVR)
=> Ignore tray actions while in immersive mode

app/src/common/shared/org/mozilla/vrbrowser/downloads/DownloadsManager.java
`setDestinationInExternalPublicDir` uses `getExternalStoragePublicDirectory` which is no longer directly accessible to apps starting on Android 29
=> Avoid using the public external path as it's not accessible in Oreo

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/oculusvr/cpp/OculusSwapChain.cpp, app/src/oculusvr/cpp/OculusSwapChain.h
Fixes #3712
This is a speculative fix. The crash address is the same (0x10) if I force the FBOs to be invalid and not added to the vector. @Softvision-RemusDranca is trying to find STRs.
I tried to force the FBOs to be invalid for 50 times using a counter and the app is able to recover using the fix included in the PR.
=> Recreate SwapChain before binding if the target FBO is invalid

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java
=> Disable Vimeo Web Extension until we find a solution for the webcompat problems 

app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h, app/src/main/cpp/DeviceDelegate.h, app/src/main/cpp/VRLayer.cpp, app/src/main/cpp/VRLayer.h, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/oculusvr/cpp/DeviceDelegateOculusVR.h, app/src/oculusvr/cpp/OculusSwapChain.cpp, app/src/oculusvr/cpp/OculusSwapChain.h, app/src/oculusvr/cpp/OculusVRLayers.cpp, app/src/oculusvr/cpp/OculusVRLayers.h
This is going to be useful for adding 6DOF envs in the future without the hassle of creating separate widget textures for the alpha blending. VRProjectionLayer will also be used in the future for the WebXR surface bypass. 
High level changes:
- Refactor OculusSwapChain code
- Implement VRProjectionLayer
- Implement BrowserWorld environment render
You can check the https://github.com/MozillaReality/FirefoxReality/tree/experimental/space_env branch with an example of a enabled 6DOF environment
=> Refactor OculusSwapChain code and implement VRProjectionLayer

app/src/common/shared/org/mozilla/vrbrowser/downloads/Download.java
Fixes #3708 Catch exceptions when composing the download progress text
=> Fixes #3708 Catch exceptions when composing the download progress text 

l10n.toml
Last step in migrating FirefoxReality l10n to the main branch.
=> Use main branch for l10n

app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java, app/src/test/java/org/mozilla/vrbrowser/GleanMetricsServiceTest.kt
We were setting  `distribution_channel_name` before `Glean.initialize` and using `org_mozilla_vrbrowser.baseline` schema to query this metrics. But, it seems like the recent changes in Glean side makes us can't see `distribution_channel_name` in baseline pings.
In addition, even in `org_mozilla_vrbrowser.metrics` schema, we still have 20% chance to see the value of `distribution_channel_name` is null, and it starts from A-C around version 44 (https://sql.telemetry.mozilla.org/queries/73600/source#184108). So, I think we need to consider to move it back to `Glean.initialize` and make sure all our metric pings could have its values instead a null.
=> Set startup metrics after Glean is initialized

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
Fixes #3687.
Checking `mIsCapsLock` when switching back to the alphabetic keyboard if the input has its own alphabeticCap keyboard.
=> Keeping caps setting when switching back from the symbol keyboard.

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java
- Under some conditions `mSessions` or `browserState` can be null during session loggin. Added null checks to avoid a crash.
- Added a check upon session addition into the `BrowserStore` to avoid adding a duplicated session.
=> BrowserStore sync checks

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/HamburgerMenuWidget.java
The UA status wasn't being correctly refreshed when we got addons updates in the hamburger menu.
=> Refresh the UA hamburger icon when addons are updated.

app/src/common/shared/org/mozilla/vrbrowser/browser/PromptDelegate.java
Fixes #3772 We were dismissing if there was a single entry provided for autofill. Pretty sure that case was handled, maybe it was a rebase issue.
=> Fixes #3772 Auto-select autofill on single entry

app/src/common/shared/org/mozilla/vrbrowser/ui/views/library/LibraryPanel.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #3789 Hide hamburger menu when interacting with the library/scrolling
=> Fixes #3789 Hide hamburger menu when interacting with the library/scrolling

app/src/common/shared/org/mozilla/vrbrowser/ui/views/library/LibraryPanel.java
Fixes #3798 Keep current add-ons tittle when reopening
=> Fixes #3798 Keep current add-ons tittle when reopening

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java
Fixes #3832 Fixes #3830 Fix tray status and private button config changes refresh
=> Fixes #3832 Fixes #3830 Fix tray status and private button config changes refresh

app/src/common/shared/org/mozilla/vrbrowser/utils/EnvironmentsManager.java
Fixes #3839 Cancel env download if a new env is set
=> Fixes #3839 Cancel env download if a new env is set

app/src/common/shared/org/mozilla/vrbrowser/addons/adapters/AddonsOptionsPermissionsViewAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/addons/views/AddonOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/addons/views/AddonsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/library/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/library/DownloadsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/library/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/library/LibraryPanel.java, app/src/main/res/layout/addon_options.xml, app/src/main/res/values/strings.xml
Fixes #3805 Fixes #3808 Fixes #3809 Fixes #3829 Addons UI fixes
=> Addons UI fixes

app/src/common/shared/org/mozilla/vrbrowser/addons/views/AddonOptionsView.java
Fixes #3868 Show correct permission list when uninstalling the add-on
=> Fixes #3868 Show correct permission list when uninstalling the add-on

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
Fix for https://crash-stats.mozilla.org/signature/?app_notes=~Firefox%20Reality%2012.1&app_notes=~release&product=FirefoxReality&date=%3E%3D2020-09-01T15%3A50%3A00.000Z&date=%3C2020-12-10T00%3A00%3A00.000Z&_sort=-date&signature=java.util.ConcurrentModificationException%3A%20at%20java.util.HashMap%24HashIterator.nextNode%28HashMap.java%29
=> Concurrent Widgets fix

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
Regression from #3944
STR:
Click on the hamburger menu->addons->mozilla components
=> Fix crash if mExternalRequestDelegate is not set

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
PauseCompositor is called in WindowWidget.serView() but ResumeCompositor is never called in unsetView()
This is causing the browser window to not render anything after Bookmarks window is display and dismissed on the HVR platform (Harmony OS)
=> Add missing resumeCompositor call when WindowWidget view is unset

app/src/openxr/cpp/DeviceDelegateOpenXR.cpp
Fixes the brightness issue with the 3D rendering layer (remote controllers, beam, and more).
The skybox also has brightness issues, but I'll address that in a separate PR.
=> Fix SGBA related brightness issues in Oculus OpenXR builds
