app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java
=> Improve URL detection on the URLBar

app/src/common/shared/org/mozilla/vrbrowser/PermissionDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/Widget.java, app/src/common/shared/org/mozilla/vrbrowser/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/WidgetPlacement.java, app/src/common/shared/org/mozilla/vrbrowser/ui/BrowserHeaderWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/BrowserWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/KeyboardWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/MoreMenuWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/PermissionWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/TabOverflowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/UIWidget.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h, app/src/main/cpp/Widget.cpp, app/src/main/cpp/Widget.h, app/src/main/cpp/WidgetPlacement.cpp, app/src/main/cpp/WidgetPlacement.h
Fixes https://github.com/MozillaReality/FirefoxReality/issues/49
=> Widget API refactor

app/src/common/shared/org/mozilla/vrbrowser/ui/CustomKeyboardView.java
=> Fixed key alignment on the x_height

app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java
=> Stack the links opened in a new tab. Fixes #68

app/CMakeLists.txt, app/src/googlevr/cpp/DeviceDelegateGoogleVR.cpp, app/src/googlevr/cpp/DeviceDelegateGoogleVR.h, app/src/googlevr/cpp/native-lib.cpp, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h, app/src/main/cpp/FadeBlitter.cpp, app/src/main/cpp/FadeBlitter.h, app/src/main/cpp/Quad.cpp, app/src/main/cpp/Quad.h, app/src/main/cpp/Tray.cpp, app/src/main/cpp/Tray.h, app/src/main/cpp/Widget.cpp, app/src/main/cpp/Widget.h, app/src/main/cpp/WidgetResizer.cpp, app/src/main/cpp/WidgetResizer.h, app/src/main/cpp/native-lib.cpp, app/src/noapi/cpp/DeviceDelegateNoAPI.cpp, app/src/noapi/cpp/DeviceDelegateNoAPI.h, app/src/noapi/cpp/native-lib.cpp, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/oculusvr/cpp/DeviceDelegateOculusVR.h, app/src/svr/cpp/DeviceDelegateSVR.cpp, app/src/svr/cpp/DeviceDelegateSVR.h, app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp, app/src/wavevr/cpp/DeviceDelegateWaveVR.h, app/src/wavevr/cpp/native-lib.cpp
=> Initial support for async loading in FxR

app/src/common/shared/org/mozilla/vrbrowser/ui/CrashReportingWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/PermissionWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsWidget.java
=> Added back handlers to Permissions, Settings and Chrash Reporting dialogs

app/src/main/cpp/BrowserWorld.cpp
=> Delay loader initialization to fix a crash in Daydream

app/CMakeLists.txt
=> Upgrade to latest vrb

app/src/common/shared/org/mozilla/vrbrowser/ui/KeyboardWidget.java
=> Keyboard can not be dismissed in focus mode

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/TopBarWidget.java, app/src/main/res/layout/top_bar.xml, app/src/main/res/values/dimen.xml
=> Close button fails to update position after leaving focus mode

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h
=> Remove Tray in focus and full screen modes

app/src/main/assets/html/index.html
=> Refresh bokmark sites

app/src/main/cpp/ExternalVR.cpp
WebVR expects inverse rotation
=> Fix immersive mode quaternion and view matrices

app/src/main/res/layout/crash_reporting.xml, app/src/main/res/layout/settings.xml, app/src/main/res/layout/settings_btn.xml, app/src/main/res/values/dimen.xml
Let me know how do you feel about that, just move a bit closer to the user but maybe bigger font sie in necessary.
=> Moved settings panel closer to the user

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsWidget.java
If the settings windows was opened and the settings tray button was clicked again the settings panel was not being hidden.
=> Toggle settings when tray button is clicked

app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsWidget.java, app/src/main/res/values/strings.xml
#145 
#150 
Forgot to update the settings panel after adding private mode. Fixed.
=> Load settings URLs in the active session and improve reported URL

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/TopBarWidget.java
=> Hide close button when not is Private Mode.

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
#142 
I'll add a task to refactor all this private mode code as it doesn't really belong here and it's growing.
=> Make previous session inactive when switching sessions

app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java
Fixes #131 
The transitions between URL bar view and focus mode view is also glitching and the views are sometimes out of bounds for millisecs. I'll open a follow up issue to move the animation part to Android TransitionManager.
=> Fixed focus button glitch and button variable naming convention

app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java, app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsWidget.java
Fixes #178
- Removed previous session restoration, no longer needed
- Refactored SettingsStore outside UI
- Removed JNI warnings
=> Remove previous session restoration, no longer needed

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
We are missing some position data because this check fails:
`if (m.predictedTracking.Status & VRAPI_TRACKING_STATUS_ORIENTATION_TRACKED) {`
Even if position tracking is not supported the pose contains some position information that needs to be in the head transform (maybe some head model).
Also found the `vrapi_GetTransformFromPose` helper method in the API to which makes the code easier.
=> Fix Oculus Go head matrix

app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java
Fixes #146 
Fixed #146 
This will get refactored when I address #161
=> Fade effect gets out of sync

app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/TopBarWidget.java
Fixes #161
Cherry picked commits from #192 and #201. Should merge fine after those are merged.
=> Refactor private mode

app/src/main/cpp/Widget.cpp
=> Fix drag handles draw over pointer (#109)

app/src/main/cpp/WidgetResizer.cpp
=> Fix bottom right resizing handle overlaps focus mode buttons

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/VRBrowser.cpp, app/src/main/cpp/VRBrowser.h
Fixes #207
Depends on https://github.com/MozillaReality/vrb/pull/39/files
=> Support loading an environment from a known location. Fixes #207

app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
- Use a custom matrix to correctly set near and clip planes
- Also fixes some math error with the fovs sent to WebVR
=> Fix #244 WVR_GetProjection does not appear to use far clip

app/src/common/shared/org/mozilla/vrbrowser/ui/AnimationHelper.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java
Fix #110: Security risk with Focus Mode
=> Fix #110: Security risk with Focus Mode

app/src/main/res/layout/top_bar.xml
=> Made "X" close button icon bigger

app/src/main/res/layout/navigation_bar.xml
=> Made focus resize icon a bit larger.

app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsWidget.java, app/src/main/res/values/strings.xml
=> Need to show FxR Nightly Version number in builds

app/build.gradle, app/oculusvr/release/output.json, app/proguard-rules.pro
Fixes #266 Remove all log messages but error and warning when in release
=> Remove all log messages except for error and warning when in release

app/build.gradle, app/proguard-rules.pro, app/src/common/shared/org/mozilla/vrbrowser/PermissionDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/audio/AudioEngine.java, app/src/common/shared/org/mozilla/vrbrowser/ui/BrowserWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/KeyboardWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/UIWidget.java, app/src/main/cpp/BrowserEGLContext.cpp, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/ControllerContainer.cpp, app/src/main/cpp/ExternalBlitter.cpp, app/src/main/cpp/FadeBlitter.cpp, app/src/main/cpp/GeckoSurfaceTexture.cpp, app/src/main/cpp/JNIUtil.cpp, app/src/main/cpp/native-lib.cpp
Fixes #162 
I've tried to set the most accurate log level. Regarding removing log info, @bluemarvin  why instead of removing debug info we just strip all debug messages for release?
=> Set most accurate permission type for error logging

app/src/main/res/drawable/url_background.xml, app/src/main/res/drawable/url_background_private.xml, app/src/main/res/layout/navigation_url.xml
Fixes #67 
Fixes #223 
Fixed URL bar colors for regular and private mode.
=> Fix hover styles and text selection colors for the URL bar

app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsButton.java, app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsWidget.java, app/src/main/res/layout/crash_reporting.xml, app/src/main/res/layout/settings.xml, app/src/main/res/layout/settings_btn.xml, app/src/main/res/values/non_I10n.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Fixes #277 
Fixes#278 
Fixes #268 
Keep non non-localizable strings out of strings.xml. Automatically rewrap strings in strings.xml
=> Refactor strings.xml to better support l10n

app/src/main/cpp/ExternalVR.cpp
Updated the API but ran out of time to test it. I would recommend just trying it. Should return false on timeout.
=> Update the ExternalVR Wait

app/build.gradle
=> Add BuildConfig.GIT_HASH so that the git hash may be displayed in the settings menu

app/src/main/cpp/ExternalVR.cpp, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
=> Fix some WebVR data used on the first frame of the first Enter VR

app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsWidget.java, app/src/main/res/layout/settings.xml
=> Added showing git has code when double clicking on the version.

app/src/main/res/values/non_I10n.xml
relevant: https://github.com/MozillaReality/FirefoxReality/issues/312#issue-347179336
(I've also emailed Liz to update mzl.la/fxr, and inquired about headset-specific tiny URLs.)
=> include `label=browser-firefox-reality` to the query-string of the "Report an issue" URL (fixes #312)

issue_template
adapted from https://www.talater.com/open-source-templates/#/page/98
<hr>
the heading formatting (`##`) and the numbered steps were the main additions I was going for here. I'm open to suggestions to the other changes. let me know!
=> Issue Template: improve formatting and add helpful tips

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/Widget.java, app/src/common/shared/org/mozilla/vrbrowser/WidgetPlacement.java, app/src/common/shared/org/mozilla/vrbrowser/ui/BrowserWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/UIWidget.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/Widget.cpp, app/src/main/cpp/Widget.h, app/src/main/cpp/WidgetPlacement.cpp, app/src/main/cpp/WidgetPlacement.h
Prevent widgets from being rendered in the scene until the SurfaceTexture has content
=> Fix black flicker when widgets are shown. Fixes #367

app/src/main/res/raw/private_style.css
Fixes issue noted in comment https://github.com/MozillaReality/FirefoxReality/pull/340#issuecomment-413656693
=> fixes privacy mode page list items alignment

app/src/common/shared/org/mozilla/vrbrowser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/search/GeolocationTask.java, app/src/common/shared/org/mozilla/vrbrowser/search/SearchEngine.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java, app/src/main/res/values/non_I10n.xml
Fixes #248 Added support for custom search engines based on geolocalization data
=> Added support for geolocalized search engines

app/src/common/shared/org/mozilla/vrbrowser/search/SearchEngine.java, app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java, app/src/common/shared/org/mozilla/vrbrowser/ui/KeyboardWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java
Per #364 , sending pings when search UI events are performed at `NavigationURLBar` and `KeyboardWidget`.
=> Add telemetry probes for searches are performed. Fixes #364

app/src/main/res/raw/error_pages.html
Fixes #265 Just moved the try button a bit down, it was too close to the error description.
=> Move the try button down

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
We changed the FBO size but not report the correct size to WebVR
=> Fix Oculus WebVR size

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/KeyboardWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/UIWidget.java, app/src/main/res/drawable/ic_icon_clear.xml, app/src/main/res/xml/keyboard_qwerty.xml
Fixes #314 Added clear button and support for backspace long press clear. Also added back handler to the keyboard.
=> Added url bar clear support

app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
Fixes #429.
Gecko side PR: https://phabricator.services.mozilla.com/D4472
We need to wait for it to land this
=> Pause media when the app goes to background.

app/build.gradle, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java
Ok, this is ready to go. 
@keianhzo r?
=> Introducing VoiceSearch

app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/DeveloperOptionsWidget.java
Fixes #420 Removed restart requirement from remote debugging. Also added some error logging and null checking.
=> Remove restart requirement from multiprocess setting.

app/src/common/shared/org/mozilla/vrbrowser/ui/DeveloperOptionsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsWidget.java, app/src/main/res/layout/developer_options.xml, app/src/main/res/layout/settings.xml, app/src/main/res/values/strings.xml
Fixes #423 Add switch text for colorblind. Also fixed a bug that was not resetting the multiprocess setting.
=> Switch support for clolorblind

app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java
Fixes #409 Update homepage when there is a region update
We have to deal with this in two different places to make sure the homepage if refreshed in case the homepage has been already been loaded when the region is updated and in case the homepage is not yet loaded so we refresh it after it's loaded.
=> Update the home page content when there is a region update

app/src/common/shared/org/mozilla/vrbrowser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/DeveloperOptionsWidget.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h, app/src/main/cpp/ControllerContainer.cpp, app/src/main/cpp/VRBrowser.cpp, app/src/main/cpp/VRBrowser.h, app/src/main/cpp/Widget.cpp, app/src/main/res/layout/developer_options.xml, app/src/main/res/values/non_I10n.xml, app/src/main/res/values/strings.xml
Fixes #481 Added an option to change pointer between white/purple. Also:
- Changed black circle color
- Removed pointer color change when clicking on the env
- Made pointer a bit thinner
=> Updated pointer color

app/src/main/res/layout/developer_options.xml
Related to #467 Removed Mouse/Touch switch from the developer panel
=> Removed Mouse/Touch switch from the developer panel

app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java
Fixes #476 Always position URL bar caret at the beginning when focusing
=> Always position URL bar caret at the beginning when focusing

app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/ExternalBlitter.cpp, app/src/main/cpp/ExternalBlitter.h
=> Correctly release WebVR textures when not in a rendering state

app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java
Fixes #514 Fixed showing microphone icon when there is text in the URL after a voice search
=> Fixed showing microphone icon when there is text in the URL

app/src/common/shared/org/mozilla/vrbrowser/InternalPages.java, app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java, app/src/main/res/raw/error_pages.html, app/src/main/res/raw/error_style.css, app/src/main/res/raw/private_mode.html, app/src/main/res/raw/private_style.css, app/src/main/res/values/localpages.xml, app/src/main/res/values/non_L10n.xml
=> add SUMO help link to Private Browsing splash page; style enhancements to Private Browsing and Error pages (fixes issue #516)

app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/BrowserWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/CloseButtonWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/DeveloperOptionsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/KeyboardWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/PermissionWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/RestartDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/TopBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/UIWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/VoiceSearchWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/prompts/ChoicePromptWidget.java, app/src/main/res/drawable/choice_prompt_layout_background.xml, app/src/main/res/drawable/prompt_background.xml, app/src/main/res/drawable/prompt_button_background.xml, app/src/main/res/drawable/prompt_button_text_color.xml, app/src/main/res/drawable/prompt_item_check_color.xml, app/src/main/res/drawable/prompt_item_selected.xml, app/src/main/res/drawable/prompt_item_text_color.xml, app/src/main/res/drawable/scrollbar.xml, app/src/main/res/layout/choice_prompt.xml, app/src/main/res/layout/choice_prompt_item.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/strings.xml
Fixes #234 Added support for the select prompt.
=> Support for select prompt

app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java, app/src/main/res/layout/navigation_url.xml, app/src/main/res/values/strings.xml
Fixes #518 Fixes #358 Removed about:privatebrowsing from private session url bar and added a hint to the search bar.
=> Removed about:privatebrowsing from private session and added a hint

app/src/common/shared/org/mozilla/vrbrowser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/BrowserWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h, app/src/main/cpp/Widget.cpp, app/src/main/cpp/WidgetResizer.cpp, app/src/main/res/layout/navigation_bar.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/styles.xml
Fixes #371, Fixes #195, Fixes #254  Added resize window options in the default view
=> Added resize window options in the default view

app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java
Fixes #524 Only show clear button if URL bar doesn't have focus and there is text
=> Only show clear button if URL bar doesn't have focus and there is text

app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java
Fixes #532 Update navigation bar size always after a resize
=> Update navigation bar size always after a resize

app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java
We would like to add a telemetry to help us figure out the avg. time spent when users in the immersive mode.
@pocmo Please help review the telemetry part. I am going to ask for the data review shortly.
=> Add telemetry for immersive mode duration time.

app/src/main/res/xml/keyboard_qwerty.xml
Fixes #446 Added missing letters
=> Added missing letter to the keyboard

app/src/noapi/AndroidManifest.xml
Fixes #573 Fixed noapi launcher icon. Also fixed the emulator rotation.
=> Fixed noapi laucher icon

app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/TopBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/UIButton.java, app/src/common/shared/org/mozilla/vrbrowser/ui/VoiceSearchWidget.java, app/src/main/res/values/dimen.xml, app/src/main/res/values/non_L10n.xml
Focus improvements. Fixes focus handling for the voice search widget.
=> Fixed focus handling for VoiceSearch

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
This was causing a crash when fading the environment when a crash dialog was shown after a restart. Also migrated some anonymous interface implementations to lambdas.
STR:
- Force a crashparent crash
Current Behavior
- A crash loop happened as we were crashing when showing the crash dialog.
Expected behaviour
- The world should fade and the crash dialog show be shown
=> Null check instances when fading world

app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
Fixes #617  Hide all javascript: urls from the URL bar
=> Hide home page redirect javascript URLs

app/src/main/res/values/strings.xml
Add these before waiting for the video mode landing so they can be translated earlier
=> Add strings for video mode

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/CrashDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/DeveloperOptionsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/PermissionWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/SettingsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h, app/src/main/cpp/FadeBlitter.cpp, app/src/main/cpp/FadeBlitter.h
- Better API to set up the background dim value and go back to the previous ones. The current code breaks a lot.
- Fixes #657
- Provide more flexibility for the configurable brightness in the Video mode.
=> Improve background dim API

README.md
if there's a better place, I'm all ears
=> add `Bleeding-edge developer APKs` section at top of README

app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java, servo/build.gradle, servo/src/main/java/org/mozilla/servo/ServoSession.java
Depends on https://github.com/servo/servo/pull/22021
=> Fix switch back to Gecko

app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Fixes #738 #617 Do not refresh URL bar on load request
=> Fixes #738 Do not refresh URL bar on load request

app/src/main/res/xml/keyboard_symbols.xml, app/src/main/res/xml/keyboard_symbols2.xml
Fixes #479 Fixed the @ symbol mapping. Can't find the related issue but we talked about this in the last triage.
=> Fixed @ mapping symbol

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
Fixes #736 Fixes URL bar focus handling and cursor positioning
=> Fixes #736 Fixes URL bar focus handling and cursor positioning

app/src/main/res/values-ja/FirefoxReality_localpages.xml, app/src/main/res/values-ja/FirefoxReality_strings.xml
Fixes #804 Update strings for Japanese v1.1 version
@delphine @Pike for review
=> Fixes #804 Update strings for Japanese v1.1 version

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/SuggestionsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java, app/src/main/res/anim/popup_scaledown.xml, app/src/main/res/anim/popup_scaleup.xml
Fixes #806 Controller back button on Go stops working after suggestions dialog shown
=> Fixes #806 Controller back button on Go stops working after suggestions dialog shown

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/BrightnessMenuWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MenuWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/VideoProjectionMenuWidget.java
=> Remove vertical scrollbar in fullscreen video projection menus

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/Pointer.cpp, app/src/main/cpp/Skybox.cpp, app/src/main/cpp/SplashAnimation.cpp, app/src/main/cpp/VRBrowser.cpp, app/src/main/cpp/VRBrowser.h, app/src/main/cpp/VRLayer.cpp, app/src/main/cpp/VRLayer.h, app/src/main/cpp/Widget.cpp, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
=> Recreate SwapChain on layer resize

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
Fixes #783 Suggestion widget crash
=> Fixes #783 Suggestion widget crash

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
After the suggestions crash the domains failed to show in the suggestions bar.
=> Fixes domains not completed correctly

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/Media.java, app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/BookmarksWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/BrowserWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Widget.java
- Implement larger window on fullscreen
- Handle video quality changes during VR playback
Fixes #779 and #748
=> Implement larger window on fullscreen. Handle VR video quality changes.

README.md
As per https://github.com/MozillaReality/FirefoxReality/issues/598#issuecomment-436711115, I added a note to say why the APK isn't available on Daydream phones yet.
=> Added note about Daydream on phones

app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java
Only check the latest commit: 0abe29b
=>  Disable polymer on youtube via URL override 

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/audio/AudioEngine.java, app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/main/res/values/non_L10n.xml
let me know if there is a preferred way of disabling (commenting out) these sounds until we approach a better user response (possibly involving haptics and so on).
=> temporarily disable loud sounds for now (fixes issue #751)

app/src/common/shared/org/mozilla/vrbrowser/ui/views/UIButton.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/UITextButton.java, app/src/main/res/drawable/fullscreen_button_private.xml, app/src/main/res/drawable/fullscreen_button_private_first.xml, app/src/main/res/drawable/fullscreen_button_private_last.xml, app/src/main/res/layout/navigation_bar.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/styles.xml
Fixes #750 Wrong icon/look with new Resize Mode icons
=> Fixes #750 Wrong icon/look with new Resize Mode icons

app/build.gradle, app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/ButtonSetting.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/SingleEditSetting.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SettingsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/options/DeveloperOptionsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/options/DisplayOptionsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/options/VoiceSearchLanguageOptionsWidget.java, app/src/main/res/layout/crash_dialog.xml, app/src/main/res/layout/honeycomb_button.xml, app/src/main/res/layout/honeycomb_switch.xml, app/src/main/res/layout/options_developer.xml, app/src/main/res/layout/options_display.xml, app/src/main/res/layout/options_language.xml, app/src/main/res/layout/setting_button.xml, app/src/main/res/layout/setting_edit.xml, app/src/main/res/layout/setting_radio_group.xml, app/src/main/res/layout/setting_switch.xml, app/src/main/res/layout/settings.xml, app/src/main/res/layout/voice_search_dialog.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/styles.xml
Fixes #772 Localization UI adjustments
=> Fixes #772 Localization UI adjustments

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MediaControlsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/VideoProjectionMenuWidget.java
There is currently no API in GV that allows to enter fullscreen automatically.
At least this PR enters the video projection when users fullscreens it.
Example URL:
https://www.youtube.com/watch?v=sPyAQQklc1s&mozVideoProjection=360
=> Video projection selection via URL parameter

app/src/main/res/values-es/FirefoxReality_localpages.xml, app/src/main/res/values-es/FirefoxReality_strings.xml, app/src/main/res/values-fr/FirefoxReality_localpages.xml, app/src/main/res/values-it/FirefoxReality_localpages.xml, app/src/main/res/values-zh-rCN/FirefoxReality_localpages.xml, app/src/main/res/values-zh-rTW/FirefoxReality_localpages.xml, app/src/main/res/values-zh-rTW/FirefoxReality_strings.xml, app/src/main/res/values-zh-rTW/androidcomponents_strings.xml
for issue #858
thanks, @Delphine!
=> update v1.1 strings for "zh-TW" locale (fixes issue #858)

app/src/main/cpp/moz_external_vr.h
I'm planning to make some changes in this file. Easier if we use the exact same version of the file. It's just some formatting changes.
=> Update moz_external_vr.h from mozilla central

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Fix broken WindowWidget views when not using layers. Fixes #911

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h, app/src/main/cpp/ExternalVR.cpp, app/src/main/cpp/ExternalVR.h, app/src/main/cpp/moz_external_vr.h, servo/build.gradle, servo/src/main/java/org/mozilla/servo/ServoDisplay.java, servo/src/main/java/org/mozilla/servo/ServoSession.java, versions.gradle
This includes an update of both Gecko and Servo.
=> GeckoView update

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
This will be useful for enabling/disabling e10s via intent parameter in performance tools.
It's a boolean parameter called `e10s`
=> Add e10s intent parameter

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
=> Do not allow privatebrowsing page to be bookmarked

app/src/main/cpp/Cylinder.cpp, app/src/main/cpp/Cylinder.h, app/src/main/cpp/WidgetResizer.cpp
Depends on https://github.com/MozillaReality/vrb/pull/61
=> Fix sticking out border in curved resize mode

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
=> Fix permission listeners called on the wrong thread

CONTRIBUTING.md
Fixes #864: Added Contributing.md
=> [WIP] Fixes #864: Added Contributing.md

app/src/googlevr/cpp/DeviceDelegateGoogleVR.cpp, app/src/main/cpp/Device.h, app/src/main/cpp/DeviceDelegate.h, app/src/main/cpp/ExternalVR.cpp, app/src/main/cpp/ExternalVR.h, app/src/main/cpp/moz_external_vr.h, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp, versions.gradle
Fixes #770
We need to wait for this Gecko patch
https://bugzilla.mozilla.org/show_bug.cgi?id=1537899
=> Set WebVR sitStanding transform. Set WebVR neck model for 3DOF devices.

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/audio/AudioEngine.java, app/src/common/shared/org/mozilla/vrbrowser/audio/AudioEngineGVR.java
=> Abstract audio engine implementation. Disable GVR audio for now.

versions.gradle
=> Update GV to 68.0.20190404063228

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/RadioGroupSetting.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/options/DisplayOptionsWidget.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h, app/src/main/cpp/DeviceDelegate.h, app/src/main/res/layout/options_display.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/options_values.xml, app/src/main/res/values/strings.xml, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/oculusvr/cpp/DeviceDelegateOculusVR.h
Adds user selectable values for foveated rendering in the chrome and WebVR scenes
=> Oculus Fixed Foveated Rendering

app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomKeyboardView.java
=> Fix first key misalignments in keyboard

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SettingsWidget.java, app/src/main/res/layout/settings.xml
fixes regression #1041
also improved the clickable region and removed some unneeded attributes. and ensured no pixels were harmed in the layout change.
=> fix git-sha version in Settings (fixes issue #1041); improve click target

app/src/main/res/values/strings.xml
=> fix interpolation symbol in L10n strings for Video Seeking (fixes issue #1105)

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NoInternetWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/utils/ConnectivityReceiver.java, app/src/main/res/layout/no_internet.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/strings.xml
=> Show error message for offline WiFi/Internet connection

app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, l10n.toml
Status: mozilla-l10n/android-l10n@451b34711f082d029c9efa0b7c2d79e32be0ad9b
Starting to use a common label for these PRs to make them easier to find across the android repositories.
CC @Callek, @Delphine
=> Import strings from android-l10n

app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/ControllerContainer.cpp, app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
=> Prevent disabled controllers from getting focus

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetPlacement.java
=> Fix UI scaling issues

app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomKeyboardView.java
=> Fix missed keys on the keyboard

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/EnglishKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomKeyboardView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/LanguageSelectorView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/common/shared/org/mozilla/vrbrowser/utils/StringUtils.java, app/src/main/res/drawable/lang_selector_background.xml, app/src/main/res/drawable/lang_selector_button_background.xml, app/src/main/res/drawable/lang_selector_button_color.xml, app/src/main/res/layout/keyboard.xml, app/src/main/res/layout/language_selection.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/non_L10n.xml
=> Implement keyboard language selection popup

app/src/main/res/layout/media_controls.xml, app/src/main/res/layout/media_controls_seek_bar.xml
=> use consistent typeface in Media Transport Controls, remove "Open Sans" (fixes issue #1166)

app/src/main/cpp/Controller.cpp, app/src/main/cpp/Controller.h, app/src/main/cpp/ControllerContainer.cpp, app/src/main/cpp/Pointer.cpp, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
=> Focus hand detection

app/src/main/res/values/dimen.xml, app/src/main/res/xml/keyboard_zhuyin.xml
Enhance `Enter`, `Backspace`, and `Space` keys placement from #1161.
=> Adjust Zhuyin special keys position.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java
Fixes #1181.
I also fixed some potential duplicated event listener registrations
=> Fix Voice Search crash on a fresh install

app/src/main/res/drawable/ic_icon_keyboard_caps.xml, app/src/main/res/drawable/ic_icon_keyboard_shift_off.xml, app/src/main/res/drawable/ic_icon_keyboard_shift_on.xml
=> Fix shift icons

README.md
for https://github.com/MozillaReality/FirefoxReality/issues/647#issuecomment-489023874
=> add direct links to bleeding-edge developer APKs for each platform generated from Taskcluster builds

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/main/res/values/non_L10n.xml, app/src/main/res/xml/keyboard_qwerty.xml, app/src/main/res/xml/keyboard_qwerty_french.xml, app/src/main/res/xml/keyboard_qwerty_german.xml, app/src/main/res/xml/keyboard_qwerty_italian.xml, app/src/main/res/xml/keyboard_qwerty_spanish.xml
Refactor keyboard popup characters. Make sure that we have all the characters needed for European languages.
=> Refactor keyboard popup characters

app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/GermanKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/KeyboardInterface.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/main/res/drawable/keyboard_background.xml, app/src/main/res/layout/keyboard.xml, app/src/main/res/values/dimen.xml, app/src/main/res/xml/keyboard_qwerty_french.xml, app/src/main/res/xml/keyboard_qwerty_german.xml, app/src/main/res/xml/keyboard_qwerty_italian.xml, app/src/main/res/xml/keyboard_symbols_german.xml
- Move keyboard button to the left 
- Update german keyboard to latest spec 
- Update french keyboard to latest spec
- Update italian keyboard to latest spec
=> Keyboard latest specs

app/src/common/shared/org/mozilla/vrbrowser/ui/views/LanguageSelectorView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/main/res/drawable/lang_selector_button_background.xml, app/src/main/res/drawable/lang_selector_button_color.xml, app/src/main/res/values/dimen.xml
- Fixes layout problem when all the languages were added (chinese was splitted in 2 lines)
- Fixes correct LangSelector hide when you click on the keyboard again
- Shows the selected language
=> Lang selector layout

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/res/layout/keyboard.xml, app/src/main/res/values/dimen.xml
Do not merge yet, we are waiting for the final `keyboard_y`, `keyboard_z` and `keyboard_world_width` values from @thenadj  and @jvonitter
=> Update keyboard placement

app/src/main/res/layout/noapi_layout.xml, app/src/noapi/java/org/mozilla/vrbrowser/PlatformActivity.java
Needed a back button to get out of immersive mode for profiling.
=> Add back button to NoAPI UI

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
=> Prevent keyboard popup-keys group from wrapping to two lines

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
=> Fix uppercase keyboard popup keys

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
=> Reset shifted keyboard status when keyboard is changed

app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java
- this fixes issue #1229
- this also fixes a bug in the [`checkYoutubeOverride` helper method for handling YouTube URLs](https://github.com/MozillaReality/FirefoxReality/blob/15568c8/app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java#L1058) that resulted in a recursive chain of `onLoadRequest` calls, causing the final URL to be malformed (e.g., https://m.youtube.com/?reload=4&rdm=43qf1a4wl#/watch?v=sPyAQQklc1s&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable_polymer=1&disable …
=> properly handle mobile `m.youtube.com` YouTube URLs (fixes issue #1229)

app/src/main/res/values/styles.xml
=> Fix yellow focus outlines appearing on some UI elements

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Fixes #555
Oculus has already fixed the SDK problem we had some time ago
=> Enable 72hz display rate in Oculus Go

app/src/oculusvrArmDebug/AndroidManifest.xml, app/src/oculusvrArmRelease/AndroidManifest.xml
=> Fix manifest for Oculus Store submission

app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java, versions.gradle
=> Bump GV version. Enable MultiView draft extension.

app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/BookmarkAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayOptionsView.java
=> Fix potential parseInt crashes

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
=> Fix potential crash in DisplayComposingText()

app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/AutoCompletionView.java, app/src/main/res/drawable/autocompletion_item_active_color.xml, app/src/main/res/drawable/autocompletion_item_background.xml, app/src/main/res/drawable/autocompletion_item_background_first.xml, app/src/main/res/drawable/autocompletion_item_background_last.xml, app/src/main/res/layout/autocompletion_bar.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimen.xml, app/src/main/res/xml/keyboard_qwerty_pinyin.xml
- Add correct pinyin punctuation autocompletion (pinyin comma and dot)
- Improve autocompletion view layouts 
Fixes #1253
=> Pinyin keyboard fixes

app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/RussianKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/main/res/values/dimen.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/keyboard_qwerty_russian.xml, app/src/main/res/xml/keyboard_symbols_russian.xml
=> Implement Russian keyboard

app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/KeyboardInterface.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/KoreanKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/common/shared/org/mozilla/vrbrowser/utils/StringUtils.java, app/src/main/res/xml/keyboard_qwerty_korean.xml
=> Implement Korean keyboard

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/UIDialog.java
=> Fix crash in UIDialog releaseWidget

app/src/main/res/values/strings.xml
=> Correct translation comment.

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
STR:
- Open FxR
- Click home
- Resume the app
- Try to open the keyboard
=> Global focus getting lost after on pause/resume

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/main/res/values/non_L10n.xml
Foveated Rendering is still in experiment, we should make it off by default.
=> Turn off app foveated rendering by default.

app/src/main/res/layout/prompt_auth.xml
Fixes #1042 Quite hard to appreciate but now it's aligned.
=> Fixed password prompt misalignment

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
=> Show the window in front of the user when exitting immersive mode

app/src/common/shared/org/mozilla/vrbrowser/ui/OffscreenDisplay.java
=> Fix Vive Focus Plus casting

app/src/main/cpp/ControllerContainer.cpp
=> Fix pointer color changes before controllers are loaded

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java
Fixes #1366 Fixed curved mode switch state
=> Fixed curved mode switch

app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java
=> Call Telemetry.scheduleUpload() early

app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java
Per #1376, giving queue histogram.
=> queue histogram before telemetry upload.

app/src/main/res/drawable/separator_background.xml, app/src/main/res/layout/options_controller.xml, app/src/main/res/layout/options_developer.xml, app/src/main/res/layout/options_display.xml, app/src/main/res/layout/options_environment.xml, app/src/main/res/layout/options_language.xml, app/src/main/res/layout/options_privacy.xml, app/src/main/res/layout/setting_radio_item.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
Fixes #959
- Improve separator line quality
- Create a reusable style for all line separators
=> Improve separator line quality and create a reusable style.

app/src/main/res/layout/options_environment.xml
Fixes #1450 bad scrollbar styles in the environments dialog
=> Fixes environments scrollbar

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/PrivacyOptionsView.java
Fixes #1427 Remove camera permission also for WaveVR
=> Remove camera permission also for WaveVR

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStack.java
=> Fix crash restoring sessions

app/proguard-rules.pro
=> Keep classes used by gson

app/proguard-rules.pro
Fixes #1505 Added missing keep state classes.
=> Fixes Gson R8 crash

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Currently we are using `VRAPI_TRACKING_SPACE_LOCAL_FLOOR` tracking space in Quest but then doing some offset math to make it equivalent to `VRAPI_TRACKING_SPACE_LOCAL`. We can simplify and just use `VRAPI_TRACKING_SPACE_LOCAL` for all devices.
See related issue: #1511
=> Simplify Oculus height tracking

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
=> Discard first click when a window is focused

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Fixes #1522
Note: This PR also includes #1540. Let's merge the other one before this one when they are reviewed
=> Force curved mode in multiwindow 

app/src/common/shared/org/mozilla/vrbrowser/ui/views/UITextButton.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
=> Hide disabled resize options.

app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/Language.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/LanguagesAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/callbacks/LanguageItemCallback.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/FadingFrameLayout.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/ContentLanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/utils/LocaleUtils.java, app/src/common/shared/org/mozilla/vrbrowser/utils/ViewUtils.java, app/src/main/res/drawable/ic_icon_empty.xml, app/src/main/res/drawable/ic_icon_language_add.xml, app/src/main/res/drawable/ic_icon_language_delete.xml, app/src/main/res/drawable/ic_icon_language_move_down.xml, app/src/main/res/drawable/ic_icon_language_move_up.xml, app/src/main/res/layout/language_item.xml, app/src/main/res/layout/options_controller.xml, app/src/main/res/layout/options_developer.xml, app/src/main/res/layout/options_display.xml, app/src/main/res/layout/options_environment.xml, app/src/main/res/layout/options_footer.xml, app/src/main/res/layout/options_header.xml, app/src/main/res/layout/options_language.xml, app/src/main/res/layout/options_language_content.xml, app/src/main/res/layout/options_language_display.xml, app/src/main/res/layout/options_language_voice.xml, app/src/main/res/layout/options_privacy.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/strings.xml
Fixes #1529 and Fixes #1528 Preferred Languages fixes
=> Preferred Languages fixes

app/src/main/res/values/dimen.xml
=> Adjust window height

versions.gradle
=> Bump GV to 70.0.20190816094815

app/proguard-rules.pro
Fixes SessionSettings Proguard serialization issues in release
=> Fixes SessionSettings Proguard serialization issues

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #1621 and Fixes #1620 and Fixes #1618 and Fixes #1617 and #1615 Multiple multi-window issues fixes
=> Fixes multiwindow resize relates issues

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes url bar state not being correctly refreshed after changing focus.
=> Fixes url bar state not being correctly refreshed after changing focus.

versions.gradle
=> Bump GeckoView to 70.0.20190823094538

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
=> Fix reattach navbar and tray regression when a window is closed

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
Fixes #1654 Fixes crash when long pressing a non focused url bar
=> Fixes crash when long pressing a non focused url bar

app/src/common/shared/org/mozilla/vrbrowser/ui/views/UIButton.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TooltipWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/Widget.cpp, app/src/main/cpp/Widget.h
=> Use flat tooltips on tray. Fix math for tray tooltips.

app/src/main/res/layout/list_popup_window.xml
=> Fix suggestions list padding to avoid exceeding the dropdown's borders

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
STR:
* Have two or three windows open
* Close a not focused window
* The tray and other elements flicker a bit.
=> Fix flickering when closing a window

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/EnvironmentOptionsView.java
=> Do not dim environment when while selecting one.

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
=> Update tray when a window is closed (and focus didn't change)

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #1757 Null check focused window when entering/exiting private mode
=> Null check focused window when entering/exiting private mode

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
=> Update 1.5x resize button style when entering private mode

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/Language.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/LanguagesAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/LanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/utils/LocaleUtils.java, app/src/main/res/layout/language_item.xml
Fixes #1748 Do not keep the display language as default content language.
=> Do not keep the display language as default content langauge

app/src/main/res/drawable/ic_icon_language_add.xml, app/src/main/res/drawable/ic_icon_language_delete.xml
Fixes  #1742 Fixes the add/remove icon turning into a check icon when clicking
=> Fixes the add/remove icon turning into a check icon when clicking

app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/HistoryAdapter.java
Fixes #1783 Show empty history when the last item is manually removed
=> Show empty history when the last item is manually removed 

app/src/main/res/values/strings.xml
Fixes https://github.com/mozilla-l10n/android-l10n/pull/76#discussion_r320976532
=> Added info regarding variable substitution 

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
=> Ensure History and Bookmark labels are shown in url bar when they are visible. Fixes #1818

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStack.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Widget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetPlacement.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/Quad.cpp, app/src/main/cpp/Quad.h, app/src/main/cpp/VRLayer.cpp, app/src/main/cpp/VRLayer.h, app/src/main/cpp/Widget.cpp, app/src/main/cpp/Widget.h, app/src/main/cpp/WidgetBorder.cpp, app/src/main/cpp/WidgetPlacement.cpp, app/src/main/cpp/WidgetPlacement.h, app/src/main/cpp/shaders/clear_color.fs, app/src/main/res/values/colors.xml, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, versions.gradle
=> Add support for clearing window color before GV does the first composition

app/src/main/res/values/non_L10n.xml, app/src/main/res/values/options_values.xml
Adding Russian language in Voice and Display settings.
=> Russian language in options

app/src/main/res/layout/bookmarks.xml, app/src/main/res/layout/history.xml
Fixes #1799 Resize library panels correctly for small window sizes
=> Resize library panels correctly for small window sizes

app/src/common/shared/org/mozilla/vrbrowser/browser/BookmarksStore.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/BookmarkAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/CustomLinearLayoutManager.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/HistoryAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/LanguagesAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/main/res/color/library_panel_icon_color.xml, app/src/main/res/layout/bookmark_item.xml, app/src/main/res/layout/bookmarks.xml, app/src/main/res/layout/history.xml, app/src/main/res/layout/history_item.xml, app/src/main/res/layout/history_item_header.xml, app/src/main/res/layout/options_language_content.xml, app/src/main/res/values/styles.xml
Fixes #1842 Fixes #1832 Fixes the glitch from the first history header and issue with animations and list refresh while a library panel is opened. Also did some refactoring/polishing and fixed some colors that didn't match the spec.
=> Library fixing/polishing

app/src/common/shared/org/mozilla/vrbrowser/ui/views/LibraryItemContextMenu.java, app/src/main/res/layout/bookmark_item.xml, app/src/main/res/layout/history_item.xml, app/src/main/res/layout/library_item_context_menu.xml, app/src/main/res/values/dimen.xml
Fixes #1852 Increased the click target area and reduced the library items row height to match the spec.
=> Increase click target size for buttons inside Library views

app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h
=> Include parenting check in depth sorting. Optimize depth sorting.

app/build.gradle
=> Change app version to use new system

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Hide context menus when window activation state changes

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
=> Check long press flag in keyboard onText() callback

app/src/main/res/drawable/title_bar_background.xml, app/src/main/res/drawable/title_bar_background_private.xml, app/src/main/res/values/colors.xml
=> Replace "Caribbean" color with "Azure" color

app/src/main/res/drawable/resize_bar_background.xml, app/src/main/res/layout/navigation_bar_resize.xml
=> Fix vertical gap in resize bar

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/main/res/drawable/url_button_end_private.xml, app/src/main/res/drawable/url_button_private.xml
=> Set correct color scheme for awesomebar buttons in private mode

app/src/main/res/color/context_menu_icon_color.xml, app/src/main/res/color/context_menu_text_color.xml, app/src/main/res/drawable/context_menu_item_background_color.xml
Addresses a item from #1530
https://github.com/MozillaReality/FirefoxReality/pull/1883 will change some layouts but it's for the next release.
=> Set blue hover color for long press menu

app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomFastScroller.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomRecyclerView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomScrollView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsView.java, app/src/main/res/drawable/empty_drawable.xml, app/src/main/res/layout/bookmarks.xml, app/src/main/res/layout/context_menu.xml, app/src/main/res/layout/history.xml, app/src/main/res/layout/options_controller.xml, app/src/main/res/layout/options_developer.xml, app/src/main/res/layout/options_display.xml, app/src/main/res/layout/options_environment.xml, app/src/main/res/layout/options_language.xml, app/src/main/res/layout/options_language_content.xml, app/src/main/res/layout/options_language_display.xml, app/src/main/res/layout/options_language_voice.xml, app/src/main/res/layout/options_privacy.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/styles.xml
Fixes #1530 partially. Adds new custom implementations for RecyclerView and Scrollview so we can always keep the scrollbars visible.
=> Scrollbars standarization

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MediaControlsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java
=> Fix video projection menu position in Media Controls

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/main/res/drawable/url_bar_hint_fading_edge_end.xml, app/src/main/res/drawable/url_bar_hint_fading_edge_end_private.xml, app/src/main/res/drawable/url_bar_hint_fading_edge_private.xml
=> Fix visual glitches on the hint fading edge

app/src/common/shared/org/mozilla/vrbrowser/input/CustomKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChineseZhuyinKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/DanishKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/EnglishKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/FrenchKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/GermanKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ItalianKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/JapaneseKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/KoreanKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/PolishKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/SpanishKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomKeyboardView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/main/res/drawable/ic_icon_keyboard_shift_disabled.xml, app/src/main/res/drawable/keyboard_popupkey_background.xml, app/src/main/res/drawable/keyboard_popupkey_capend_background.xml, app/src/main/res/drawable/keyboard_popupkey_capstart_background.xml, app/src/main/res/drawable/lang_selector_button_background.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/options_values.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/keyboard_qwerty_danish.xml, app/src/main/res/xml/keyboard_qwerty_polish.xml, app/src/main/res/xml/keyboard_symbols.xml, app/src/main/res/xml/keyboard_symbols_danish.xml, app/src/main/res/xml/keyboard_symbols_german.xml, app/src/main/res/xml/keyboard_symbols_japanese.xml, app/src/main/res/xml/keyboard_symbols_polish.xml
Fixes #1751 Fixes #1750 Fixes #1733 Added Danish and Polish and updated the Spec to UIS-6_Keyboard_021. Also fixes the long press bug.
The UIS-6_Keyboard_021 updated includes:
- Updating hover styles for popup and languages menu to azure
- Show the current language in the search bar for 3secs after it's selected
- Show disabled shift buttons in the symbols keyboard 
Also added Danish and Polish to the Display and Voice languages as part of #1594
=> Keyboard updates: Polish, Danish UIS-6 and bug fixing

.gitignore, build.gradle, gradle/wrapper/gradle-wrapper.properties
This reverts commit df21d293099f34213765e295b43661a5bcef91e7.
=> Revert "Gradle update required by AS 3.5.0 (#1762)"

app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/NorwegianKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/main/res/values/dimen.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/options_values.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/keyboard_qwerty_norwegian.xml, app/src/main/res/xml/keyboard_symbols_norwegian.xml
Closes #1754 Norwegian keyboard
=> Norwegian Keyboard

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UISurfaceTextureRenderer.java
Potential workaround for #2017
=> Enable software rendering

app/src/main/cpp/shaders/clear_color.fs
Fixes broken GV window in the emulator
=> Fix floating-point suffix unsupported prior to GLSL ES 3.00

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java, app/src/main/res/values/non_L10n.xml
Closes #1477 This adds support for sending a ping when the telemetry is enabled/disabled.
=> Added support for a telemetry enabled/disabled ping

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MenuWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/ContextMenuWidget.java, app/src/main/res/values/strings.xml
=> Fix long press menu highlight state. Fixes #2047

app/src/common/shared/org/mozilla/vrbrowser/ui/views/TabView.java
=> Fix potential title shown in new tab button when view is reused

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/RootWidget.java
=> Make RootWidget focus more reliable

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java
Fixes #2064 The privacy button listener was not set.
=> Private settings button fix

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionSettings.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayOptionsView.java
=> Use user configuration to initialize session UA and viewport settings

app/src/main/cpp/moz_external_vr.h, versions.gradle
Includes:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1591949
- https://bugzilla.mozilla.org/show_bug.cgi?id=1565268
=> Bump GV to 72.0.20191029093803

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
This fixes the pop-up notification z-fighting in curved mode
=> Fix popup notification in curved mode

app/src/main/res/drawable/fullscreen_button.xml, app/src/main/res/drawable/fullscreen_button_first.xml, app/src/main/res/drawable/fullscreen_button_last.xml
Fixes #2116 There seem to be some bug with animated regular selector in Android, using animated-selector seems to fix it in some situations.
=> Fix the transparent background when changing the button state

app/src/main/res/drawable/fullscreen_button_private.xml, app/src/main/res/drawable/fullscreen_button_private_first.xml, app/src/main/res/drawable/fullscreen_button_private_last.xml
Closes #2116 I forgot to add the patch for private mode too :/
=> Fix the top ui transparent background fix for private mode too

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/search/SearchEngineWrapper.java, app/src/common/shared/org/mozilla/vrbrowser/search/suggestions/SuggestionsProvider.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/TabView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/WhatsNewWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/FxAAccountOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java
Make sure all the promises exceptions are caught and logged and printed as stacktraces.
=> Audit promises exceptions

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
Fix for the following crash: https://crash-stats.mozilla.com/report/index/99d87b4e-5135-4b2c-8930-1f69f0191104
=> Fix crash in onLoadRequest()

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/MenuWidget.java, app/src/common/shared/org/mozilla/vrbrowser/utils/ViewUtils.java
=> Fix missed clicks in menu items

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/FxAAccountOptionsView.java
fixes #2155
If a SyncStatus change operation is overlapped it doesn't complete correctly and only the first one is applied.
=> Do not overlap History/Bookmarks FxA SyncStatus change operations

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TabsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UISurfaceTextureRenderer.java
=> Ensure that tab dialog and it's surface are invalidated before they are shown

app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/BindingAdapters.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/SwitchSetting.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/FxAAccountOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java, app/src/main/res/drawable/content_panel_button_background.xml, app/src/main/res/layout/bookmarks.xml, app/src/main/res/layout/bookmarks_narrow.xml, app/src/main/res/layout/bookmarks_wide.xml, app/src/main/res/layout/history_narrow.xml, app/src/main/res/layout/history_wide.xml, app/src/main/res/layout/options_fxa_account.xml
Fixes #2151 Fixes issues with panel sync status updates. Also fixes an issue with the sync button staying in hovered stat after a sync.
=> Fix sync status updates

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
=> Fix broken UI after restoring a Youtube session

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
=> Fix resize save button color scheme

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java
Fixes #2120 Fixes the dismiss of the PopUps dialog.
=> Fixes dismiss of the PopUps dialog

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Do not show context menu for videos

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
=> Hide search suggestions when focusing a different window

app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/ButtonSetting.java, app/src/main/res/drawable/rectangle_button_background.xml
Fixes #2202 Force update the hover button state after being disabled though bindings
=> Force update the hover button state after being disabled though bindings

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java
Fixes #2205 There is some sort of race condition inside mozilla_speech and the start call fail if it's called right before a cancel.
=> Enqueue the voice start call to give time to the cancel to finish

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Fix Paste functionality in not available for empty input fields

app/src/main/res/layout/bookmarks_narrow.xml, app/src/main/res/layout/bookmarks_wide.xml, app/src/main/res/layout/history_narrow.xml, app/src/main/res/layout/history_wide.xml
Fixes #2207 Hide library panels header if empty
=> Hide library panels header if empty

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/FxAAccountOptionsView.java
Fixes #2222 Sync engines in case of a explicit sync
=> Sync engines in case of a explicit sync

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/SuggestionsWidget.java
Fixes #1993 Resets the awesome bar position to the head after showing.
=> Reset awesome bar scrollbar when showing

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java
Reverting as it seems to be working fine in Vive Focus/Go/Quest
=> Restore voice search animation

app/src/main/res/values/strings.xml
Fixes comments from https://github.com/mozilla-l10n/android-l10n/pull/98
=> Strings quarantine updates

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Hide bookmarks/history when selecting a different tab

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Fixes #2248 Remove notifications when resizing and opening library panels too
=> Remove notifications when resizing and opening library panels

app/src/common/shared/org/mozilla/vrbrowser/ui/callbacks/BookmarksCallback.java, app/src/common/shared/org/mozilla/vrbrowser/ui/callbacks/HistoryCallback.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #2265 Dismiss context menu when scrolling
=> Dismiss context menu when scrolling

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
=> Fix wrongly positioned pasted text in the URL bar

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes https://crash-stats.mozilla.com/report/index/47178285-46c5-4eb0-80e4-5ba4a0191119
=> Check if selection action is available before executing it.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Make onCheckIsTextEditor return false when the window is resizing

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UISurfaceTextureRenderer.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DeveloperOptionsView.java, app/src/main/res/layout/options_developer.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/strings.xml
=> Enable software rendering (#2019)

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
=> Request focus when clicking URL bar icon buttons

app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java
Fixes #2299 Delete all instances of the history url record
=> Delete all instances of the history url record

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
- Removes a extra resize step for captured snapshots
- Fixes #2319
- Fixes #2318
- Fixes #2315
=> Improve session snapshot captures

app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/LanguagesAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/PopUpAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/ContentLanguageOptionsView.java, app/src/main/res/drawable/ic_icon_language_delete.xml, app/src/main/res/layout/language_item.xml, app/src/main/res/layout/popup_item.xml
Fixes #2297 For consistency this PR adds hover animation to the preferred languages list too.
=> Add hover animations to the languages and popup row icons

app/src/main/res/layout/whats_new.xml
Fixes #2258 Fixes what's new dialog background color
=> Fixes what's new dialog background color

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
=> Do not release GeckoDisplay when switching visible window sessions

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
=> Do not erase the entire text when backspace is long-pressed

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
=> Fix navigation bar notification alignment

app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/BrowserWorld.h
=> Update children widgets recursively

versions.gradle
=> Bump GV to 72.0.20191126093448

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionUtils.java, app/src/main/assets/web_extensions/webcompat_youtube/background.js, app/src/main/assets/web_extensions/webcompat_youtube/main.js, app/src/main/assets/web_extensions/webcompat_youtube/manifest.json
=> Use WebExtension for youtube redirects instead of the GV API

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Refine Multiple window telemetry

app/metrics.yaml, app/src/common/shared/org/mozilla/vrbrowser/browser/Accounts.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/Services.kt, app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/WhatsNewWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/ContextMenuWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java, docs/metrics.md
Fixes #1609 Fixes #1610 Adds support for Tabs and FxA telemetry
=> Fxa & Tabs Telemetry

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DeveloperOptionsView.java
=> Handle hardware acceleration switch when reseting dev options

app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/BookmarkAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/HistoryAdapter.java, app/src/main/res/layout/bookmark_item.xml, app/src/main/res/layout/history_item.xml
Fixes #2357 Fixes #2358 Fixes #1812 Fixes styles in the library list items
=> Fix library items styles

app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomKeyboardView.java
Fixes #1838 Make keyboard keys sticky so it behaves the same as the rest of the UI.
=> Make keyboard keys sticky

versions.gradle
=> Bump GV to v73.0.20191211094640

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
=> Reposition UI in front of the user when exiting a VR video

app/metrics.yaml, app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, docs/metrics.md
=> Add telemetry for creating new windows

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MediaControlsWidget.java
=> Fix invalid play/pause button state when entering immersive videos

app/src/common/shared/org/mozilla/vrbrowser/input/MotionEventGenerator.java
Fixes #2502 (better to test this PR with #2509)
=> Use out of bounds coordinates when dispatching ACTION_HOVER_EXIT

app/src/common/shared/org/mozilla/vrbrowser/utils/SystemUtils.java
Fixes #2533 Call the crash reported form a background thread otherwise we get an exception.
=> Call the crash reported form a background thread

app/src/main/res/values/styles.xml
=> Fix focus outlines appearing on some UI elements

app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/BookmarkAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/HistoryAdapter.java, app/src/main/res/layout/bookmark_item.xml
Fixes #1812 Fixes #2483 Fixes the pressed state of the delete button from bookmarks. Also fixes he alignment of the history URLs
=> Fixed the bookmarks item delete button state

app/src/main/res/layout/media_controls.xml, app/src/main/res/values/dimen.xml
Fixes #2497 Fix cut media controls at the bottom
=> Fix cut media controls at the bottom

app/src/main/res/layout/prompt_dialog.xml
Fixes #2527  Make dialog checkbox to wrap content height
=> Make dialog checkbox to wrap content height

app/src/main/assets/web_extensions/webcompat_youtube/main.css
=> Hide youtube fullscreen share button

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TitleBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #2484 Update tittle bar media status when switching tabs
=> Update tittle bar media status when switching tabs

app/src/main/assets/web_extensions/webcompat_youtube/main.css
Fixes #2577
After enabling the good layout with the UA hack we don't need to increase font size anymore
=> Do not scale font size anymore in the youtube webextension

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/main/assets/userAgentOverride.json, app/src/main/assets/web_extensions/webcompat_youtube/main.js
=> Set youtube viewport before DOMContentLoaded

app/src/main/assets/web_extensions/webcompat_youtube/main.js
=> Set max-scale and min-scale values in Youtube's viewport

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #2623 Correctly focus front window after another is closed
=> Fixes #2623 Correctly focus front window after another is closed

app/src/main/assets/web_extensions/webcompat_youtube/main.css
=> Add 1 column Youtube CSS layout rule

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/ClearHistoryDialogWidget.java
Fixes #2664 Fixes #2665 Close dialog after clearing and reseting the radio button
=> Fixes #2664 Fixes #2665 Close dialog after clearing and reseting the radio button

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/UIDialog.java
Fixes #2677 Call dismiss instead of hide when dismissing by a world click on dialogs
=> Fixes #2677 Call dismiss instead of hide when dismissing by a world click on dialogs

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayLanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/VoiceSearchLanguageOptionsView.java
Fixes #2689 Fixes voice language issue when reset. Also force save the display one
=> Fixes #2689 Fixes voice language issue when reset. Also force save the display one

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
Fixes #2561 Support uppercase for text keys
=> Fixes #2561 Support uppercase for text keys

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
Fixes #2490 Dismiss keyboard when clicked outside buttons
=> Fixes #2490 Dismiss keyboard when clicked outside buttons

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/HamburgerMenuWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/MenuWidget.java, app/src/common/shared/org/mozilla/vrbrowser/utils/UrlUtils.java
Fixes #2432 Remove the option for sending private mode about page
=> Fixes #2432 Remove the option for sending private mode about page 

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MediaControlsWidget.java
=> Place media controls in the same y position

app/src/main/res/values/non_L10n.xml
Fixes #2560 Fixes #2566 Removed unsupported latin extended chars that rendered wrong
=> Fixes #2560 Fixes #2566 Removed unsupported latin extended chars that rendered wrong

app/src/main/res/layout/setting_edit.xml
Fixes #1978 Add ellipsis at the end of user editable fields
=> Fixes #1978 Add ellipsis at the end of user editable fields

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/Widget.cpp
=>  Do not depend on how many windows are opened to select flat/curved when entering fullscreen

app/src/common/shared/org/mozilla/vrbrowser/ui/views/VolumeControl.java
Fixes #2008 Avoid volume seeker to reset when dragging out of bounds
=> Fixes #2008 Avoid volume seeker to reset when dragging out of bounds

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
=> Fix voice search button visibility

app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/WindowViewModel.java
Fixes #2729 Always show the full url in the navigation bar
=> Fixes #2729 Always show the full url in the navigation bar

app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/WindowViewModel.java
Fixes #2734 Hide top bar when not in private mode and is single window
=> Fixes #2734 Hide top bar when not in private mode and is single window

app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/WindowViewModel.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/main/res/layout/navigation_url.xml
STRs:
- Click on the URL bar
- Type some text
Expected result: Clear button should appear
Actual result: Clear button doesn't appear
=> Fixes clear button not shown when there is text in the url bar

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/VoiceSearchLanguageOptionsView.java
Fixes #2699 Pick the voice language when committing it
=> Fixes #2699 Pick the voice language when committing it

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Check if the collapse action is available before calling collapseEnd

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TabsWidget.java
Fixes #2756 hide send button when closing a private tab
=> Fixes #2756 hide send button when closing a private tab

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
Fixes #2749 Fixes #2748 Update url bar view instead of the binding when pasting
=> Fixes #2749 Update url bar view instead of the binding when pasting

app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/WindowViewModel.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #2750 Fixes #2733 Update the bookmark button state after a new url is loaded. Also make the url the default.
=> Fixes #2750 Fixes #2733 Update the bookmark button state after a new url is loaded

app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/WindowViewModel.java
=> Fix null SpannableString construction

app/src/common/shared/org/mozilla/vrbrowser/ui/views/UIButton.java
Fixes #2777 Fix UIButton hover issue after changing enabled state
=> Fix UIButton hover issue after changing enabled state

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/PopUpExceptionsOptionsView.java
Fixes #2774 Create the adapter before adding it to the list
=> Fixes #2774 Popups list update fix

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/main/res/layout/top_bar.xml
Fixes #2683 Improve Window visibility in transitions
=> Fixes #2683 Improve Window visibility in transitions

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/main/res/values/non_L10n.xml
Fixes https://github.com/MozillaReality/FirefoxReality/issues/2789
=> Revert e10s to disabled by default

app/src/common/shared/org/mozilla/vrbrowser/ui/views/UIButton.java
Fixes #2791 Fix for the UIButton long press issue on Android 8
=> Fixes #2791 Fix for the UIButton long press issue on Android 8

app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/WindowViewModel.java
After a Windows restore the title bar should be correctly visible now.
=> Fixes the correct restoration of the title bar

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserApplication.java, app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/WindowViewModel.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/CrashDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/PermissionWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/PopUpBlockDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/RestartDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SendTabDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SignOutDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/WhatsNewWidget.java
This fixes some issues that I've seen while testing v9 with language update from the system config. Fixes the correct update of the URL and Title bars.
Also fixes the correct update of app dialogs in case the system language is changed while a dialog is opened.
=> System config changes fixes

app/src/main/res/layout/navigation_bar_fullscreen.xml
Fixes #2832 Fix styles for fullscreen controls
=> Fixes #2832 Fix styles for fullscreen controls

app/src/common/shared/org/mozilla/vrbrowser/ui/views/TabView.java
Fixes #2806 Fix Android 8 devices hover issues in tab icons
=> Fixes #2806 Fix Android 8 devices hover issues in tab icons

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/PrivacyOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/utils/DeviceType.java, app/src/picovr/java/org/mozilla/vrbrowser/PlatformActivity.java
Disable camera permissions on Pico devices
=> Disable camera permissions on Pico devices

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #2811 Update the navigation bar bookmarked flag when bookmarks are updated
=> Fixes #2811 Update the navigation bar bookmarked flag when bookmarks are updated

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/HamburgerMenuWidget.java
=> Fix hamburger menu item order

app/src/main/assets/web_extensions/webcompat_youtube/main.css
=> Fix black screen when playing immersive Youtube videos using desktop mode

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NotificationManager.java
Related to https://github.com/MozillaReality/FirefoxReality/pull/2831#discussion_r382755735
=> Use Hashmap instead of ConcurrentHashmap as Notifications storage

app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/BindingAdapters.java
Fixes #2835 Fix tooltip for Android 8.
=> Fixes #2835 Fix tooltip for Android 8

app/src/main/res/layout/navigation_url.xml
Fixes #2856 Set private mode in the navigation bar buttons
=> Fixes #2856 Set private mode in the navigation bar buttons

app/src/common/shared/org/mozilla/vrbrowser/ui/views/TabView.java
Fixes #2839 Fixes hover tab buttons hover issues in Android 26
=> Fixes #2839 Fixes hover tab buttons hover issues in Android 26

versions.gradle
=> Bump mozilla speech to 1.0.10

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #2868 Fixes the issue with the library brightness. I was mistakenly passing the runnable as the push brightness key.
=> Fixes #2868 Fixes the issue with the library brightness

versions.gradle
=> Bump GV to v75.0.20200226092757

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Initialize view model url when the window is created

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java
=> Fix crash calling hide when the activity is destroyed

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
=> Move UISurfaceTextureRenderer.setRenderActive calls to pause/resume

versions.gradle
=> Bump GV to 75.0.20200227094956

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TitleBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Do not queue WindowWidget::unsetView() calls

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/main/res/values/non_L10n.xml
=> Disable UI hard acceleration by default in Wave

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
=> Let gecko choose protocol for addresses

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TabsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/UIDialog.java
Fixes #2927
It's a regression from #2823
=> Correctly release SendTabDialog in onDestroy

app/src/main/res/layout/navigation_url.xml, app/src/main/res/values/strings.xml
Fixes #2916 Fix the bookmark navigation bar button tooltip
=> Fixes #2916 Fix the bookmark navigation bar button tooltip

app/src/main/res/layout/noapi_layout.xml
This lets you see things better with the curved corners
on newers phones like the Pixel 4.
=> Add margins to the FPS and controls in noapi

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/BindingAdapters.java, app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/BookmarksViewModel.java, app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/HistoryViewModel.java, app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/TrayViewModel.java, app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/WindowViewModel.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/BookmarksView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/UIButton.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java, app/src/main/res/layout/bookmarks.xml, app/src/main/res/layout/history.xml, app/src/main/res/layout/tray.xml
Fixes #2782  Another step forward to decouple the model and views. This one migrates the tray and the library panels. There should be any behavior changes.
=> Fixes #2782 Migrate tray and library panels to viewmodel

app/src/main/res/xml/keyboard_symbols.xml, app/src/main/res/xml/keyboard_symbols_danish.xml, app/src/main/res/xml/keyboard_symbols_finnish.xml, app/src/main/res/xml/keyboard_symbols_german.xml, app/src/main/res/xml/keyboard_symbols_japanese.xml, app/src/main/res/xml/keyboard_symbols_norwegian.xml, app/src/main/res/xml/keyboard_symbols_polish.xml, app/src/main/res/xml/keyboard_symbols_russian.xml, app/src/main/res/xml/keyboard_symbols_swedish.xml
=> Fixed duplicated quote symbols in symbol keyboards.

app/src/common/shared/org/mozilla/vrbrowser/utils/StringUtils.java
Handle version code conversion in debug builds
=> Handle version code conversion in debug builds

app/build.gradle, app/proguard-rules.pro, versions.gradle
Fixes #2992 Something has changed after the latest tools update and some classes were being obfuscated which led to a crash.
=> Fixes #2992 Update proguard rules

app/src/common/shared/org/mozilla/vrbrowser/browser/PermissionDelegate.java, versions.gradle
=> bump GV version to 76.0.20200319094444

app/src/common/shared/org/mozilla/vrbrowser/input/MotionEventGenerator.java
Fixes #2981 Exit other devices hover when clicking with another device
=> Fixes #2981 Exit other devices hover when clicking with another device

app/src/common/shared/org/mozilla/vrbrowser/input/MotionEventGenerator.java
Fixes #2996 Fixes #2999 Fixes #2982 Reset the touch when the action is cancelled
=> Reset the touch when the action is cancelled

app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomKeyboardView.java
Fixes #2994 Gaze device index (2) was not supported in the keyboard hover and caused a crash. Also fixes the Pico Flicker issue.
=> Adds support for gaze devices hover in keyboard & Pico flicker issues

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
=> Query all Oculus controllers even if we get a bad reading from one.

versions.gradle
Seems to fix https://bugzilla.mozilla.org/show_bug.cgi?id=1624489
=> Bump GV to 76.0.20200324093140

app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
We have a typo on the right controller (using Bin Y).
=> Using Btn B on the right hand in Quest.

app/src/common/shared/org/mozilla/vrbrowser/browser/PermissionDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/QuickPermissionWidget.java
=> Toggle quick permission dialog when clicking the URL bar icons

app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/ExternalVR.cpp, app/src/main/cpp/ExternalVR.h
=> Supress ExternalVR frames when Application is paused

app/src/test/java/org/mozilla/vrbrowser/GleanMetricsServiceTest.kt
Don't merge. It is for capturing logs.
=> Fix glean test for Oculus channel name.

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/LanguagesAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/UIButton.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NotificationManager.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/ContentLanguageOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/utils/AnimationHelper.java, app/src/common/shared/org/mozilla/vrbrowser/utils/SystemUtils.java, app/src/common/shared/org/mozilla/vrbrowser/utils/ThreadUtils.java, versions.gradle
The ThreadUtils functions have been removed from GV.
=> Remove org.mozilla.gecko.util.ThreadUtils usage

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
Fixes #3086 that is a regression by #2801
=> Remove showing spacebar text by regression.

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Fixes #3081 Fix in-video fullscreen exit
=> Fixes #3081 Fix in-video fullscreen exit

app/src/common/shared/org/mozilla/vrbrowser/browser/content/TrackingProtectionStore.java
=> Ensure the entire exception list is rebuilt when inserting new exception

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/MenuWidget.java
=> Make sure widget manager is not null in MenuWidget.hide()

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java, app/src/main/res/xml/keyboard_symbols_danish.xml, app/src/main/res/xml/keyboard_symbols_finnish.xml, app/src/main/res/xml/keyboard_symbols_german.xml, app/src/main/res/xml/keyboard_symbols_norwegian.xml, app/src/main/res/xml/keyboard_symbols_polish.xml, app/src/main/res/xml/keyboard_symbols_swedish.xml
Fixes #3093, #3094, #3099,  and #3100.
=> Keyboard bugs fix

app/src/main/res/layout/voice_search_dialog.xml
#3125 Fix voice dialog cut text
=> #3125 Fix voice dialog cut text

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java
Fixes #3122 Force voice search widget recreation after a language update
=> Fixes #3122 Force voice search widget recreation after a language update

app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/WindowViewModel.java
Fixes #3135 #3134 No need of refreshing the fullscreen property after a UI update
=> Fixes #3135 #3134 No need of refreshing the fullscreen property after a UI update

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Fixes #3151 Force awesome bar widget creation when detached from window
=> Fixes #3151 Force awesome bar widget creation when detached from window

app/src/main/res/layout/navigation_url.xml
=> Use correct setting for DRM tooltip

app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/BookmarkAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/DownloadsAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/HistoryAdapter.java, app/src/main/res/layout/bookmark_item.xml, app/src/main/res/layout/bookmark_item_folder.xml, app/src/main/res/layout/download_item.xml, app/src/main/res/layout/history_item.xml
Fixes #3155 In Pico STRs:
- Disable HW acceleration from the Developer settings
- Open the history panel
- Hover on any item
Expected: The row state should be hovered
Actual: The row is not hovered
=> Fixes #3155 Fix non HW accelerated Android 8 hover issues

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
Fixes #3175 Default load request to allow
=> Fixes #3175 Default load request to allow

app/build.gradle
Add missing resources dirs for Oculus flavors
=> Add missing resources dirs for Oculus flavors

app/src/common/shared/org/mozilla/vrbrowser/ui/views/UIButton.java
Better handle UIButton drawable states. Fixes the TopBar widget drawable state issues when moving windows.
=> Better handle UIButton drawable states

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Dispatch fullscreen change notification on recreated sessions

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsView.java
Fixes #3208 Reset settings view scroll when opened
=> Fixes #3208 Reset settings view scroll when opened

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Fixes #3213 Fixes full screen exit issues.
=> Fixes #3213 Fixes full screen exit issues

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Fixes #3222 Fixes fullscreen exit calls when not in fullscreen.
This fixes the linked issue and also the brightness not being popped when opening a tab from the tabs panel.
=> Fixes #3222 Avoid exiting fullscreen if not in it

app/src/common/shared/org/mozilla/vrbrowser/browser/PermissionDelegate.java
=> Fix SitePermission crash

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WebXRInterstitialWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/VRBrowser.cpp, app/src/main/cpp/VRBrowser.h
=> Pause WebXR spinner AnimatedVectorDrawable during immersive mode

app/src/common/shared/org/mozilla/vrbrowser/downloads/DownloadsManager.java
Fixes #3254 (in combination with #3255)
=> Keep downloads update thread paused when there aren't active downloads

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
Force not opened session to be activated when the state is activated
=> Force not opened session to be activated when the state is activated

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
Fixes #3274 Reset window model focused state when window is detached
=> Fixes #3274 Reset window model focused state when window is detached

app/src/main/assets/web_extensions/webcompat_youtube/main.js
=> Disable 5k youtube videos

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/PrivacyOptionsView.java
Fixes #3294 Fixes the ETP setting reset
=> Fixes #3294 Fixes the ETP setting reset

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionUtils.java, versions.gradle
Fixes #3310
Starting with GeckoView Nightly 77.0.20200430082621 user.js
needs to use user_pref() instead of pref() to set prefs.
=> Update generated user.js to use user_pref

app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/WindowViewModel.java
Fixes #3314 Fixes #3316  Fixed so it the url buttons update also based on the library visibility property.
=> Fixes #3314 Fixes #3316 Fixes url bar icons state

app/src/common/shared/org/mozilla/vrbrowser/browser/content/TrackingProtectionStore.java
Fixes #3315 Save list just once when deleting all tracking sites to avoid glitches
=> Fixes #3315 Save list just once when deleting all tracking sites to avoid glitches

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/ContextMenuWidget.java
=> Do not include copy link context menu item for file based resources

versions.gradle
=> GV bump 78.0.20200507085231

app/src/common/shared/org/mozilla/vrbrowser/browser/PromptDelegate.java
=> Compare host instead of uri when checking popup permissions

.taskcluster.yml
This is a test PR to see if tc-index works and if we have all the scopes
=> Use tc-index to get the link to the latest master builds

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NotificationManager.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #3426 Fixes fullscreen exit when opening a tab
=> Fixes #3426 Fixes fullscreen exit when opening a tab

app/src/common/shared/org/mozilla/vrbrowser/downloads/DownloadsManager.java
Fixes #3448 Null check to avoid the DownloadManager crash
=> Fixes #3448 Null check to avoid the DownloadManager crash

app/src/picovr/java/org/mozilla/vrbrowser/PlatformActivity.java
=> Do not consume the Confirm Button on Pico

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java
=> Ensure mWidgetManager isn't null in UIWidget.setVisible()

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionUtils.java
=> Disable voice routing.

app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
Fixes #3484 Fixes URL bar selection ranges
=> Fixes #3484 Fixes URL bar selection ranges

app/proguard-rules.pro
Fixes #3514 Exclude the RemoteProperties from Proguard
=> Fixes #3514 Exclude the RemoteProperties from Proguard

versions.gradle
Fixes #3472 
Fixes #3420
Fixes #3412
Fixes #3481
Fixes #3473
Fixes #3336
=> Bump GV to 79.0.20200623034439

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Closes #2764 Grey out window when resizing
=> Closes #2764 Grey out window when resizing

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java
Fixes #2782 Fix private browsing tray button state
=> Fixes #2782 Fix private browsing tray button state

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Fixes #2882 Do not show popup notifications if in library view mode
=> Fixes #2882 Do not show popup notifications if in library view mode

app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChineseZhuyinKeyboard.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/UIButton.java, app/src/main/res/drawable/main_button_icon_color_notification_private.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/styles.xml
Fixes #2856 URL bar private mode notification button style
=> Fixes #2856 URL bar private mode notification button style

app/src/main/cpp/BrowserWorld.cpp
=> Fix pointer sorting issue

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MediaControlsWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/main/res/layout/media_controls.xml
Fixes #3555 Fixes #3556 Media controls fixes
=> Fixes #3555 Fixes #3556 Media controls fixes

app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java, app/src/common/shared/org/mozilla/vrbrowser/search/SearchEngineWrapper.java, app/src/common/shared/org/mozilla/vrbrowser/search/suggestions/SearchSuggestionsClient.kt, app/src/common/shared/org/mozilla/vrbrowser/search/suggestions/SuggestionsProvider.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/PrivacyOptionsView.java, app/src/main/res/layout/options_privacy.xml, app/src/main/res/values/non_L10n.xml, app/src/main/res/values/strings.xml
Fixes #1857 Make awesome bar autocomplete optional
=> Fixes #1857 Make awesome bar autocomplete optional

app/proguard-rules.pro
Fixes #3581 Added Environment class to Proguard
=> Fixes #3581 Added Environment class to Proguard

app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java, app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java, app/src/common/shared/org/mozilla/vrbrowser/utils/StringUtils.java, app/src/common/shared/org/mozilla/vrbrowser/utils/UrlUtils.java
=> Fix validation failures of URIs with multiple hash signs.

app/src/main/res/values/strings.xml
Closes#3185 Migrate strings xml entities to CDATA
=> Closes#3185 Migrate strings xml entities to CDATA

app/src/main/res/values/non_L10n.xml
=> Update privacy URL to point to the FxR specific page

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Fixes #3617 Disable reload button in private mode
=> Fixes #3617 Disable reload button in private mode

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Fixes #3623 Avoid releasing the voice search widget on config changes
=> Fixes #3623 Avoid releasing the voice search widget on config changes

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #3607 Fixes #3606 What's new fixes
=> Fixes #3607 Fixes #3606 What's new fixes

app/src/main/res/values/strings.xml
Related to https://github.com/mozilla-l10n/android-l10n/pull/243#discussion_r449199391
=> Add comment for the web search string parameter

versions.gradle
=> Bump GV nightly to v80.0.20200707094747

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
=> Fixes space key has no effect when pressing.

versions.gradle
=> Bump GV to 80.0.20200708094217

versions.gradle
=> Bump GV to 80.0.20200709093347

app/src/main/cpp/VRVideo.cpp
Fixes #3661
It's a regression from #3232
=> Fix 180 equirect layer transform

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/ClearHistoryDialogWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SendTabDialogWidget.java
Fixes #3659 Refresh send tab on configuration changed
=> Fixes #3659 Refresh send tab on configuration changed

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
=> Ensure suspended sessions are not readded to a-c SessionStore

app/src/common/shared/org/mozilla/vrbrowser/utils/LocaleUtils.java, app/src/main/res/values/strings.xml
Relates to https://github.com/mozilla-l10n/android-l10n/pull/243#discussion_r447292984
=> Update supported languages strings comment to reflect all uses

versions.gradle
Fixes #3628 Fixes #3578 Fixes #3429
#3628 fix didn't make it to the last GV we bumped
=> Bump GV to 80.0.20200713095122

app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp, app/src/wavevr/cpp/DeviceDelegateWaveVR.h, app/src/wavevr/cpp/native-lib.cpp
=> Move WaveVR render initialization to a separate method

app/src/main/cpp/Widget.cpp
=> Check resizer before using.

l10n.toml
Lets give this a shot as was discussed in Bug 1651025
=> Bug 1651025 - Update branches in l10n.toml (main branch)

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/common/shared/org/mozilla/vrbrowser/utils/AnimationHelper.java, app/src/main/cpp/BrowserWorld.cpp, app/src/main/cpp/ControllerContainer.cpp, app/src/main/cpp/ControllerContainer.h, app/src/main/cpp/ControllerDelegate.h, app/src/main/res/layout/navigation_bar_fullscreen.xml, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, app/src/openxr/cpp/OpenXRInput.cpp, app/src/picovr/cpp/DeviceDelegatePicoVR.cpp, app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
=> Hide controllers in fullscreen mode

app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
=> Hide WaveVR controllers when in fullscreen mode

app/src/main/cpp/DeviceDelegate.h, app/src/main/cpp/ExternalVR.cpp, app/src/main/cpp/ExternalVR.h, app/src/main/cpp/moz_external_vr.h, app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp, versions.gradle
=> Implement WebXR nativeFramebufferScaleFactor

versions.gradle
=> Bump GV nightly to 81.0.20200804091327

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
=> Check if unselect action is available before calling unselect

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/PrivacyOptionsView.java
=> Reset data collection dialog when user resets privacy settings

app/src/common/shared/org/mozilla/vrbrowser/addons/views/AddonsListView.java
Scroll addon list to top after installing
=> Scroll addon list to top after installing

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/main/res/layout/tray.xml, app/src/main/res/values/dimen.xml
Show tray buttons tooltip at the bottom
=> Show tray buttons tooltip at the bottom

app/src/common/shared/org/mozilla/vrbrowser/browser/components/GeckoWebExtensionRuntime.kt
Do not set pb to false at startup time
=> Do not set pb to false at startup time

app/src/common/shared/org/mozilla/vrbrowser/ui/views/library/LibraryPanel.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Fixes #3816 Fix crash in Library when config changes are received
=> Fixes #3816 Fix crash in Library when config changes are received

app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserApplication.java, app/src/common/shared/org/mozilla/vrbrowser/browser/Accounts.kt, app/src/common/shared/org/mozilla/vrbrowser/browser/Services.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/AppServicesProvider.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java, app/src/common/shared/org/mozilla/vrbrowser/utils/ConnectivityReceiver.java, app/src/common/shared/org/mozilla/vrbrowser/utils/EnvironmentsManager.java
Fixes #3814  This should overcome this FxA bug https://github.com/mozilla-mobile/android-components/issues/7889
=> Fixes #3814 Avoid initializing to FxA if there is no internet

app/src/common/shared/org/mozilla/vrbrowser/addons/views/AddonOptionsDetailsView.java, app/src/common/shared/org/mozilla/vrbrowser/addons/views/AddonOptionsPermissionsView.java, app/src/common/shared/org/mozilla/vrbrowser/addons/views/AddonOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/addons/views/AddonsListView.java, app/src/common/shared/org/mozilla/vrbrowser/browser/Addons.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Fixes #3812 Fixes #3813 Add-ons tabs life cycle fixes
=> Fixes #3812 Fixes #3813 Add-ons tabs life cycle fixes

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/menus/HamburgerMenuWidget.java
Fixes #3820 Hide the hamburger menu when switching windows.
=> Fixes #3820 Hide the hamburger menu when switching windows.

app/src/common/shared/org/mozilla/vrbrowser/browser/PromptDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/UIDialog.java
Fixes #3790 Prompts dismiss currently visible dialogs
=> Fixes #3790 Prompts dismiss currently visible dialogs

app/src/common/shared/org/mozilla/vrbrowser/addons/views/AddonsView.java
Fixes #3834 Fixes #3833 Avoid back presses while fake dragging
=> Fixes #3834 Fixes #3833 Avoid back presses while fake dragging

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/LoginEditOptionsView.java
Fixes #3828 Cancel login edit when deleting while editing
=> Fixes #3828 Cancel login edit when deleting while editing

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java
=> Fix #3835 Fix time update

app/src/common/shared/org/mozilla/vrbrowser/addons/adapters/AddonsViewAdapter.java, app/src/common/shared/org/mozilla/vrbrowser/addons/views/AddonOptionsDetailsView.java, app/src/common/shared/org/mozilla/vrbrowser/addons/views/AddonOptionsPermissionsView.java, app/src/common/shared/org/mozilla/vrbrowser/addons/views/AddonOptionsView.java, app/src/common/shared/org/mozilla/vrbrowser/addons/views/AddonsListView.java, app/src/common/shared/org/mozilla/vrbrowser/addons/views/AddonsView.java, app/src/common/shared/org/mozilla/vrbrowser/browser/Addons.kt, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/main/res/layout/addon_options.xml, app/src/main/res/layout/addon_options_details.xml
Fixes #3802 Fix add-ons view update issues
=> Fixes #3802 Fix add-ons view update issues

app/src/common/shared/org/mozilla/vrbrowser/ui/viewmodel/WindowViewModel.java
Fixes #3779 Fix url bar title refresh issue
=> Fixes #3779 Fix url bar title refresh issue

app/src/common/shared/org/mozilla/vrbrowser/browser/PromptDelegate.java
Fixes #3845 Do not show login save/select if autofill is disabled
=> Fixes #3845 Do not show login save/select if autofill is disabled

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/main/assets/extensions/fxr_youtube/background.js, app/src/main/assets/extensions/fxr_youtube/main.js
Fixes #3778 Fix 360 desktop mode issues
=> Fixes #3778 Fix 360 desktop mode issues

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java, app/src/main/res/values/strings.xml
Fixes #3792 Status bar tooltips fixes
=> Fixes #3792 Status bar tooltips fixes

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/UIDialog.java
Fixe #3862 Null check when hiding dialogs
=> Fixe #3862 Null check when hiding dialogs

app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Fixes #3863 Focus windows when attached
=> Fixes #3863 Focus windows when attached

app/src/main/res/layout/options_edit_login.xml
Fixes #3783 Disable text suggestions in Login EditTexts
=> Fixes #3783 Disable text suggestions in Login EditTexts

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
Fixes #3778 Fix youtube viewport issues.
=> Fixes #3778 Fix youtube viewport issues.

tools/taskcluster/build_targets.py, tools/taskcluster/sign_apk.py
Disable building Oculus 3dof in TC
=> Disable building Oculus 3dof in TC

app/src/main/res/values/strings.xml
=> L10 updates

app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java
=> Null check on a glean timer

app/src/main/assets/extensions/fxr_youtube/main.js
Fixes #3899 Fixed for Youtube extension
=> Fix for Youtube extension

app/src/main/assets/extensions/fxr_youtube/background.js, app/src/main/assets/extensions/fxr_youtube/main.js
Forces Desktop mode
Fixes issues with projections and selectors.
=> Youtube playback fixes

app/src/main/AndroidManifest.xml
Add permission to allow install APKs from FxR
=> Add permission to allow install APKs from FxR

app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java
=> Fix Glean crash

app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java, app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java, app/src/common/shared/org/mozilla/vrbrowser/utils/UrlUtils.java, app/src/main/res/values/strings.xml
Handle external schemes to allow deep linking from inside FxR
Fixes #3943
=> Handle external schemes to allow deep linking from inside FxR

app/CMakeLists.txt, app/src/openxr/cpp/DeviceDelegateOpenXR.cpp
Required to use the latest Oculus OpenXR SDK
=> Implement XrLoaderInitInfoAndroidKHR

app/src/main/cpp/VRBrowser.cpp, app/src/main/cpp/VRBrowser.h, app/src/main/cpp/VRLayer.cpp
It happens when using layers and a widget is destroyed
=> Fix OpenXR JNI crash

app/CMakeLists.txt, app/build.gradle, app/src/hvr/AndroidManifest.xml, app/src/hvr/java/org/mozilla/vrbrowser/PlatformActivity.java, app/src/hvr/res/layout/webxr_interstitial_controller.xml, app/src/main/cpp/BrowserEGLContext.cpp, app/src/main/cpp/BrowserEGLContext.h, app/src/main/cpp/native-lib.cpp, app/src/openxr/cpp/DeviceDelegateOpenXR.cpp, app/src/openxr/cpp/OpenXRExtensions.cpp, app/src/openxr/cpp/OpenXRExtensions.h, app/src/openxr/cpp/OpenXRInput.cpp
=> Add support for HVR platform

.gitignore, app/build.gradle, app/src/common/shared/org/mozilla/vrbrowser/VRBrowserApplication.java, app/src/common/shared/org/mozilla/vrbrowser/speech/MozillaSpeechRecognizer.java, app/src/common/shared/org/mozilla/vrbrowser/speech/SpeechRecognizer.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/AppServicesProvider.java, app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java, app/src/hvr/java/org/mozilla/vrbrowser/HVRSpeechRecognizer.java, app/src/hvr/java/org/mozilla/vrbrowser/PlatformActivity.java, build.gradle, versions.gradle
Android speech recognition is not supported on HVR devices. This platform has an specific SDK.
This PR abstracts out the SpeechRecognizer so we can provide different implementations (MozillaSpeechRecognizer, HVRSpeechRecognizer and potentially stock Android SpeechRecognizer in the future)
=> Implement HVR ASR
